feat(wallet): Detect Reorgs And RBFs
synonymdev/bitkit-react-native pull request #1081
Opened 2023-05-26 19:36 UTC by coreyphillips

### Description

- Bitkit now tracks transactions with less than 6-confirmations and notifies users of a relevant reorg or RBF.
- Added `unconfirmedTransactions` to `wallet` reducer.
- Created several new methods for tracking unconfirmed txs.
- Added a button to inject a fake transaction in the Dev menu.
- Added `exists` to `IActivityItem` types.
- Updated `mergeActivityItems` method.
- Added methods to clear store objects when rescanning.

With this update we're concerned with two main things that can happen to transactions with less than 6 confirmations.
 1. A transaction can get pushed back to the mempool due to a reorg.
 2. A zero-conf transaction can get removed from the mempool if it has insufficient fees for the given fee environment or a reorg occurs that knocks it from the mempool.

In the event number one occurs, Bitkit will detect that a previously confirmed transaction is now no longer confirmed and notify the user accordingly. This is a best-case scenario where a user may only need to wait for the tx to confirm again. The only action that needs to be taken is ensuring the activity item is no longer marked as confirmed.

In the event number two occurs, Bitkit will detect that a tracked transaction is no longer in the mempool and alert the user accordingly of a potential reorg or RBF. This situation is more severe since the transaction in question is now gone, reverting ownership of any received or sent funds. In this situation, Bitkit will set the `exist` state to false in the activity list item and highlight the tx entry in red in the activity list. Bitkit will also perform a rescan of the wallet to ensure funds and stored transactions are accurate.

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Tests

- [x] No test

### Screenshot / Video
![ghost-tx](https://github.com/synonymdev/bitkit/assets/8532651/224ad542-594f-4599-9f74-5c5036ea2ee1)
![reorg](https://github.com/synonymdev/bitkit/assets/8532651/faf92e5c-a585-410c-adc2-813ff646079e)
![removed-from-mempool](https://github.com/synonymdev/bitkit/assets/8532651/ecffea60-dbef-4298-841f-c8f5a58d54a6)

### QA Notes

To test a reorg:
 1. Send funds to the wallet: `/regtest-deposit<address> 0.00005000`
 2. Mine a block: `/regtest-mine 1`
 3. Invalidate the block you just mined: `/regtest-invalidate-block <blockhash>`
 Expected: A blue notification should appear that matches the attached screenshot after detecting the reorg. The transaction should no longer appear as confirmed in the activity list.

To test an RBF or getting bumped from the mempool:
 1. Navigate to "Settings->Dev Settings->Inject Fake Transaction"
Expected: A red notification should appear that matches the attached screenshot after detecting the ghost/invalid tx. The tx in question should be red in the activity list. When tapping the activity list item the status should display "Removed from Mempool".

### Notes

- I added translations for the new notifications using Google translate. Please let me know if they need further adjustments.

2023-05-29 11:41 UTC, limpbrains requested changes
LN transactions are now shown in red too

<img width="381" alt="image" src="https://github.com/synonymdev/bitkit/assets/155891/6ca51e57-0c4e-4d6d-85f2-c4c8d5e67f75">

2023-05-29 11:41 UTC, limpbrains commented on src/utils/i18n/locales/ru/wallet.json
> +	"activity_removed_msg": "Пожалуйста, проверьте свой список действий. Любые затронутые транзакции будут выделены красным цветом.",
Thank you for the translation :) 
In future I think it is better to ingore languages, other than english. If new string is missing, english will be shown anyway. And we better use Transifex as a main store of translations, so we don't have to sync it back and forth.

2023-05-29 11:42 UTC, limpbrains commented
Also I've pushed fix for e2e tests

2023-05-29 12:03 UTC, pwltr requested changes

2023-05-29 12:03 UTC, pwltr commented on src/store/migrations/index.ts
> +	},
With our current state reconciler setting it's not possible to write migrations for state nested this deep, see note at the top of this file. Maybe we should switch to `hardSet` as state reconciler but this will have to be tested.

2023-05-29 12:03 UTC, pwltr commented on src/store/types/activity.ts
> +	exists: boolean;
This field seems unnecessary for a LN activity item.

2023-05-29 13:36 UTC, coreyphillips commented on src/utils/i18n/locales/ru/wallet.json
> +	"activity_removed_msg": "Пожалуйста, проверьте свой список действий. Любые затронутые транзакции будут выделены красным цветом.",
> LN transactions are now shown in red too
> 
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/155891/241723254-6ca51e57-0c4e-4d6d-85f2-c4c8d5e67f75.png">

Thanks. Updated default params/checks [here](https://github.com/synonymdev/bitkit/pull/1081/commits/fccb8d74ebd98d3eeb1cf43cd0b58cd2f5f531cf).

2023-05-29 13:37 UTC, coreyphillips commented on src/store/types/activity.ts
> +	exists: boolean;
Removed exists from types [here](https://github.com/synonymdev/bitkit/pull/1081/commits/fccb8d74ebd98d3eeb1cf43cd0b58cd2f5f531cf).

2023-05-29 13:52 UTC, coreyphillips commented on src/store/migrations/index.ts
> +	},
Thanks for pointing that out. I'll set it to `hardSet` and run some tests on my end to ensure it's behaving as expected.

2023-05-29 14:00 UTC, coreyphillips commented on src/store/migrations/index.ts
> +	},
Updated [here](https://github.com/synonymdev/bitkit/pull/1081/commits/dbebbb99fee1d14c8e64db7382af5f8738854706).

2023-05-29 16:11 UTC, coreyphillips commented on src/store/migrations/index.ts
> +	},
`hardSet` seems to prevent the app from starting. I changed `hardSet` back to `autoMergeLevel2` for now while I attempt to figure out the cause of the issue.

2023-05-29 16:27 UTC, coreyphillips commented on src/store/migrations/index.ts
> +	},
Updated the migration for `unconfirmedTransactions` [here](https://github.com/synonymdev/bitkit/pull/1081/commits/60200af4d3afee5785e44ffd24d9e7808b857e0f). Should be good to go.

2023-05-29 19:55 UTC, coreyphillips commented
Tested the `unconfirmedTransactions` migration from old state to new without issue on my end. Please let me know if you encounter any issues during your testing.

2023-05-30 10:42 UTC, limpbrains approved these changes

2023-05-30 13:03 UTC, pwltr requested changes

2023-05-30 13:03 UTC, pwltr commented on src/screens/Activity/ActivityDetail.tsx
> +	if (activityType === EActivityType.onchain && !exists) {
this will always be true since we're in `OnchainActivityDetail`

2023-05-30 13:03 UTC, pwltr commented on src/store/actions/wallet.ts
> +export const addUnconfirmedTransactions = async ({
unnecessary usage of `async`

2023-05-30 13:03 UTC, pwltr commented on src/store/actions/wallet.ts
> +			await showInfoNotification({
unnecessary `await`

2023-05-30 13:05 UTC, coreyphillips commented on src/screens/Activity/ActivityDetail.tsx
> +	if (activityType === EActivityType.onchain && !exists) {
This is to appease typescript. Otherwise, exists would have to be added to each ActivityItem type.

2023-05-30 13:08 UTC, pwltr commented on src/screens/Activity/ActivityDetail.tsx
> +	if (activityType === EActivityType.onchain && !exists) {
No this is not true. TS will know that `activityType` will always be `EActivityType.onchain` here and that `exists` will be there.

2023-05-30 13:11 UTC, coreyphillips commented on src/store/actions/wallet.ts
> +export const addUnconfirmedTransactions = async ({
Updated [here](https://github.com/synonymdev/bitkit/pull/1081/commits/2e01f0f1948de799bdf3ca188cd9cdf85fee885c).

2023-05-30 13:11 UTC, coreyphillips commented on src/store/actions/wallet.ts
> +			await showInfoNotification({
Update [here](https://github.com/synonymdev/bitkit/pull/1081/commits/2e01f0f1948de799bdf3ca188cd9cdf85fee885c).

2023-05-30 13:19 UTC, pwltr approved these changes

2023-05-30 13:19 UTC, pwltr approved these changes

2023-05-30 13:40 UTC, merged