feat: change unit switch logic
synonymdev/bitkit-react-native pull request #1168
Opened 2023-07-20 11:33 UTC by limpbrains

### Description

To simplify logic of choosing the format of displaying amounts, I've merged settings.bitcoinUnit and settings.balanceUnit into new settings.unit option. Also I've removed showFiat from <Money /> component and replaced it with unitType = primary | secondary. It is primary by default.

Primary is a unit from settings.unit, secondary is "opposite". This allows to easily show some amount in bitcoin / fiat, without bothering which is which, just <Money sats={100} size="big" /> and <Money sats={100} size="small" />

Also I've added primaryUnitSelector and secondaryUnitSelector to reflect these changes.

Also I've added ability to change unit by tapping on Amount for a few more screens.

### Type of change

Refactoring

### Tests

No test

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/155891/2e9ff397-83a9-4790-a69d-6df04343b815

### QA Notes

Make sure that changing unit works fine across all screens.

2023-07-22 06:39 UTC, pwltr requested changes

2023-07-22 06:39 UTC, pwltr commented on src/screens/Lightning/QuickSetup.tsx
> -						reverse={true}
`reverse={true}` still needed

2023-07-22 06:39 UTC, pwltr commented on src/store/types/wallet.ts
> -	BTC = 'BTC',
Can you please change the variable name for the enum? I find it confusing that `EBitcoinUnit` contains a member 'fiat'. Also assignments like `bitcoinUnit` etc. Sorry nitpicking but helps with readability.

2023-07-22 06:39 UTC, pwltr commented on src/screens/Wallets/Send/Amount.tsx
> +		console.info('result', result);
debug leftover

2023-07-22 06:39 UTC, pwltr commented on src/utils/displayValues/index.ts
> +		}
Can remove this block because `bitcoinUnit` is now required

2023-07-22 06:39 UTC, pwltr commented on src/screens/Wallets/Send/Amount.tsx
> -		...(unit !== EBalanceUnit.fiat ? { symbol: true } : { showFiat: true }),
Symbol missing for BTC & sats

2023-07-22 06:39 UTC, pwltr commented on src/screens/Transfer/Setup.tsx
> -						reverse={true}
revert

2023-07-22 06:39 UTC, pwltr commented on src/screens/Transfer/Setup.tsx
> -						reverse={true}
and I think there should be a "Custom Amount" button here as well like in QuickSetup?

2023-07-22 06:39 UTC, pwltr commented on src/screens/Wallets/Send/ReviewAndSend.tsx
> +					</TouchableOpacity>
secondary (fiat/sats) is missing, also if coin selection is active then `onPress` should still navigate to Amount screen

2023-07-22 06:39 UTC, pwltr commented on src/screens/Activity/ActivityDetail.tsx
>  					<Money sats={value} sign={isSend ? '- ' : '+ '} />
Fiat has the symbol here but not BTC/sats, looks inconsistent

2023-07-22 06:39 UTC, pwltr commented on src/screens/Wallets/WalletsDetail/index.tsx
> +										/>
again, fiat has the symbol but not BTC/sats, maybe need to clarify with Aldert

2023-07-24 11:06 UTC, limpbrains commented on src/store/types/wallet.ts
> -	BTC = 'BTC',
np, these are all valid concerns

2023-07-24 12:30 UTC, limpbrains commented on src/screens/Activity/ActivityDetail.tsx
>  					<Money sats={value} sign={isSend ? '- ' : '+ '} />
I've asked Alders, will fix it in another PR, if needed

2023-07-24 12:30 UTC, limpbrains commented on src/screens/Wallets/WalletsDetail/index.tsx
> +										/>
I've asked Alders, will fix it in another PR, if needed

2023-07-24 12:44 UTC, limpbrains commented
@pwltr thx for awesome review! 
I think I've fixed all the problems, please take a look again

2023-07-24 14:18 UTC, pwltr requested changes

2023-07-24 14:18 UTC, pwltr commented on src/store/types/wallet.ts
> +
this was merged back in, should be removed

2023-07-24 14:18 UTC, pwltr commented on src/utils/helpers.ts
> +
also merged back in, should be removed

2023-07-24 14:18 UTC, pwltr commented on src/utils/helpers.ts
> -
keep this

2023-07-24 14:19 UTC, pwltr commented
Please squash commits

2023-07-24 14:31 UTC, limpbrains commented on src/utils/helpers.ts
> +
fixed

2023-07-24 14:31 UTC, limpbrains commented on src/utils/helpers.ts
> -
fixed

2023-07-24 14:32 UTC, limpbrains commented
> Please squash commits

I will, after review is complete

2023-07-24 14:33 UTC, pwltr approved these changes

2023-07-25 08:58 UTC, merged