feat(lightning): sync stored ldk txs with activity list
synonymdev/bitkit-react-native pull request #1171
Opened 2023-07-21 18:46 UTC by Jasonvdb

### Description

- Continues to show incoming tx animation even when invoice might not be tracked
- Syncs stored claimed and sent txs from react-native-ldk with activity list

### Linked Issues/Tasks
https://github.com/synonymdev/bitkit/issues/1007

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### QA Notes

Hoping incoming animation shows up but if it doesn't at least tx history won't be missing

2023-07-26 14:56 UTC, coreyphillips requested changes

2023-07-26 14:56 UTC, coreyphillips commented on src/utils/lightning/index.ts
> +};
To keep all dispatch actions together the `syncLightningTxsWithActivityList` method should be moved to `src/store/actions/lightning.ts`

2023-07-27 09:47 UTC, Jasonvdb commented on src/utils/lightning/index.ts
> +};
Fixed here https://github.com/synonymdev/bitkit/pull/1171/commits/230ef2d0f861d49bd7eb8e415571717bb180c81d

2023-07-27 11:20 UTC, coreyphillips submitted a review, later dismissed

2023-07-27 11:20 UTC, coreyphillips commented
Not sure why the tests are failing.

2023-07-27 18:14 UTC, coreyphillips approved these changes

2023-07-27 18:16 UTC, Jasonvdb commented
> Channel seems to remain as pending in Bitkit

Ah thanks might have been a race condition, channel was confirmed when I was testing receiving

2023-07-27 18:16 UTC, merged