fix: activity total = value + fee
synonymdev/bitkit-react-native pull request #1174
Opened 2023-07-25 15:45 UTC by limpbrains

### Description

- Money now uses decimalLength=long by default
- convert onchain fee to sats, so it matches value and LN activity 
- show real fee for LN payments
- LN activity items value should be positive. I'm adding a migration for that
- show activity total as value + fee

### Linked Issues/Tasks

https://app.asana.com/0/1189635884316057/1205072416958950/f

### Type of change

Bug fix

### Tests

No test

### Screenshot / Video

![image](https://github.com/synonymdev/bitkit/assets/155891/aa782571-6064-48e7-b4ea-bacd7606b239)

![image](https://github.com/synonymdev/bitkit/assets/155891/f05189f5-4a96-4dd6-b55e-e77a5e1e5dbe)

![image](https://github.com/synonymdev/bitkit/assets/155891/414cd7c8-d134-4723-aadd-5af8cfe10233)

### QA Notes

Make sure that activity represents tx history

2023-07-31 21:08 UTC, pwltr commented
Onchain Receive screen looks different compared to design, I think fees should not be included for receive? 

![Simulator Screenshot - iPhone 14 - 2023-07-31 at 23 06 45](https://github.com/synonymdev/bitkit/assets/8538369/321a7fad-67b7-4313-ae56-52a8e8fd3391)

2023-07-31 21:10 UTC, pwltr requested changes

2023-07-31 21:10 UTC, pwltr commented on src/screens/Activity/ListItem.tsx
> +	const amount = isSend ? value + fee : value;
In `utils/activity/index` we are subtracting the fee for onchain send, maybe cleaner to remove the code there?

2023-08-01 11:21 UTC, limpbrains commented
> Onchain Receive screen looks different compared to design, I think fees should not be included for receive?
fixed

2023-08-01 11:22 UTC, limpbrains commented on src/screens/Activity/ListItem.tsx
> +	const amount = isSend ? value + fee : value;
Yes, but we can't do this for LN payments, since activity list there is the only sorce of truth for now.
So I would prefer to keep it this way for now

2023-08-02 20:11 UTC, pwltr approved these changes

2023-08-03 06:59 UTC, merged