feat: add lugano feed widget
synonymdev/bitkit-react-native pull request #1237
Opened 2023-09-08 10:43 UTC by Nuhvi

### Description

Add Lugano feed widget.

### Linked Issues/Tasks

[Event widget feed timetable](https://app.asana.com/0/1200529269167147/1205322182636536)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

![Simulator Screen Shot - iPhone 14 - 2023-09-08 at 13 34 34](https://github.com/synonymdev/bitkit/assets/40009100/d45307d2-d4f5-450c-8518-0e9e642f5b66)

2023-09-08 12:43 UTC, pwltr commented
Resolve conflicts please.

2023-09-08 12:58 UTC, limpbrains requested changes
Did you remove yarn.lock ? Please do not do this. You have upgraded a lot of peer dependencies. 
Can you please revert yarn.lock, ios/Podfile.lock, install packages you need and add yarn.lock again. 
Upgrading packages can break things, we better do it gradually and in separate PR

2023-09-11 10:13 UTC, pwltr commented
Can you fix the tests? It looks to me like your `react-native-fetch-hack` is trying to use `node-fetch` on the native mobile side, will that work? https://github.com/synonymdev/bitkit/actions/runs/6122214804/job/16617501219?pr=1237

2023-09-11 10:20 UTC, Nuhvi commented
> Can you fix the tests? It looks to me like your `react-native-fetch-hack` is trying to use `node-fetch` on the native mobile side, will that work? https://github.com/synonymdev/bitkit/actions/runs/6122214804/job/16617501219?pr=1237

You know better, but it is the only way I know of to load binary data, in this case images. If you know how to do it otherwise with the provided `fetch()` function, let me know, or just revert to the published npm version of the web-relay.

2023-09-11 10:34 UTC, pwltr commented
> You know better, but it is the only way I know of to load binary data, in this case images. If you know how to do it otherwise with the provided fetch() function, let me know, or just revert to the published npm version of the web-relay.

I don't know without looking into it, but trying to run `node-fetch` on the mobile client sounds like a massive workaround and judging by the tests it doesn't seem to work? Simple solution for this case would be to just render a static image for the banner in this widget since, the design looks like it has only one image. Would that work?

2023-09-11 10:47 UTC, Nuhvi commented
@pwltr This issue needs to be solved, the simple solution doesn't work for the rest of the Web Relay use-cases, when someone uploads a profile picture or whatever.

Isn't `node-fetch` already using the normal `globalThis.fetch` in browser environment as in Bitkit? so this is only a CI issue? I will try to make the CI hapyp, but it works in Bitkit fine.

If @rbndg thinks we should just hardcode these images fine.

2023-09-11 10:56 UTC, limpbrains commented
I was able to fix tests locally by chaning 
```patch
- import { Client } from '@synonymdev/web-relay';
+ import { Client } from '@synonymdev/web-relay/lib/client';
```
in src/components/SlashtagsProvider2.tsx

2023-09-11 11:03 UTC, Nuhvi commented
@limpbrains Can you push that with the correct `ios/bitkit.xcodeproj/project.pbxproj`?

2023-09-11 11:08 UTC, Nuhvi commented
Pushed a version where `node-fetch` isn't required at all https://github.com/slashtags/web-relay/blob/react-native-fetch-hack/lib/client/fetch-react-native.js

2023-09-11 11:51 UTC, Nuhvi commented
Ok this latest error doesn't seem the web relay's fault @pwltr

2023-09-11 16:55 UTC, pwltr commented
Feeds are not working for me:

![Simulator Screenshot - iPhone 14 - 2023-09-11 at 18 53 15](https://github.com/synonymdev/bitkit/assets/8538369/3c2fa513-d168-407a-88a2-10fa8646f204)

2023-09-12 08:11 UTC, Nuhvi commented
@pwltr @limpbrains all checks passed

2023-09-12 09:16 UTC, limpbrains commented
Works now!

2023-09-12 09:36 UTC, limpbrains commented
On android:
`LOG  Error while reading banner png [TypeError: Cannot read property 'byteLength' of null]`

2023-09-12 09:38 UTC, Nuhvi commented
@limpbrains Sigh... I will just read images as base64 and be done with it, but this is not sustainable.

2023-09-13 11:29 UTC, MiguelMedeiros commented on src/components/Widgets.tsx
> +				case SUPPORTED_FEED_TYPES.LUGAON_FEED:
```suggestion
				case SUPPORTED_FEED_TYPES.LUGANO_FEED:
```
typo mistake :)

2023-09-13 11:29 UTC, MiguelMedeiros commented on src/hooks/widgets.ts
> +					reader.config.type === SUPPORTED_FEED_TYPES.LUGAON_FEED
```suggestion
					reader.config.type === SUPPORTED_FEED_TYPES.LUGANO_FEED
```
typo mistake :)

2023-09-13 11:30 UTC, MiguelMedeiros commented on src/screens/Widgets/Widget.tsx
> +										case SUPPORTED_FEED_TYPES.LUGAON_FEED:
```suggestion
										case SUPPORTED_FEED_TYPES.LUGANO_FEED:
```

typo mistake :)

2023-09-13 11:30 UTC, MiguelMedeiros commented on src/utils/widgets/index.ts
> +	LUGAON_FEED = 'to.synonym.lugano-feed',
```suggestion
	LUGANO_FEED = 'to.synonym.lugano-feed',
```
typo mistake :)

2023-09-13 11:40 UTC, MiguelMedeiros commented
@Nuhvi,

I've observed an inconsistency with the timestamp format on the client side. It currently displays as HH:M (e.g., 6:4). For better clarity, I believe it should be in the HH:MM format, such as 6:40.

Could you please confirm this?



![simulator_screenshot_36B12486-AE92-46AF-AF3B-0FB8FF7ED42E](https://github.com/synonymdev/bitkit/assets/5798170/8c59f499-80a0-48f4-bfd0-9e739a21ba8d)

2023-09-13 11:42 UTC, MiguelMedeiros commented on package.json
> +    "@synonymdev/web-relay": "^1.0.2",
```suggestion
    "@synonymdev/web-relay": "1.0.2",
```
Let's remove the ^ to ensure we have explicit control over dependency versions.

2023-09-13 12:45 UTC, MiguelMedeiros commented
@Nuhvi  I noticed that when we add the widget, or when we click to see its settings, a screen appears with part of the widget appearing behind another layer of the app. Is it possible to make everything fit there without the user having to scroll down? Otherwise, I think it would be better if the user could scroll down to see the preview of the widget.

![simulator_screenshot_98F490D3-97A7-402B-A3FD-647B473F54E8](https://github.com/synonymdev/bitkit/assets/5798170/b671c69e-d160-49f7-bc28-74aaaecbcc9a)

2023-09-13 12:50 UTC, Nuhvi commented
> @Nuhvi I noticed that when we add the widget, or when we click to see its settings, a screen appears with part of the widget appearing behind another layer of the app. Is it possible to make everything fit there without the user having to scroll down? Otherwise, I think it would be better if the user could scroll down to see the preview of the widget.
> 

I agree. However, this is out of the scope of this widget so I don't want to couple the delivery of this widget with changes to how the Edit Widget screen behaves. Happy to do what @pwltr and @limpbrains suggest.

2023-09-13 12:54 UTC, MiguelMedeiros commented
> > 
> I agree. However, this is out of the scope of this widget so I don't want to couple the delivery of this widget with changes to how the Edit Widget screen behaves. Happy to do what @pwltr and @limpbrains suggest.

I agree with you that this change would be out of scope for this PR. I don't want to add any unnecessary complexity to the PR, so I'll create an issue to track this change and we can address it in a separate PR. 👍

2023-09-13 13:08 UTC, MiguelMedeiros commented
I've noticed an issue in the calendar events table where the event titles are being truncated in the middle of the text, resulting in something like "Bitcoin p...ments are." 

To improve the user experience, I suggest modifying the text truncation behavior to cut off the end of the string instead. For example, it should display as "Bitcoin payments..." 

I believe there's a function in the code that handles string truncation to fit within the screen, but it seems optimized for invoices, where we need to see both the beginning and end of the string. In this case, it would greatly enhance the user's ability to read and understand the event title if only the beginning of the presentation title is displayed. Do you agree, @Nuhvi ?

![simulator_screenshot_7D9CB60E-46E9-4307-A55D-48A9A697529C](https://github.com/synonymdev/bitkit/assets/5798170/47643e20-81d9-4045-8929-4152a9065459)

2023-09-14 06:04 UTC, pwltr requested changes

2023-09-14 06:04 UTC, pwltr commented on src/components/LuganoFeedWidget.tsx
> +import { TouchableOpacity } from 'react-native-gesture-handler';
Rather import from `react-native` as this one will cause issues

```suggestion
import { TouchableOpacity } from 'react-native';
```

2023-09-14 06:04 UTC, pwltr commented on src/components/LuganoFeedWidget.tsx
> +	'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAABQrSURBVHgB7V0LkJTVlf7+ZmCY6cGBmWEGUIfhERXEDCaaBKgoo6BWQIVYqyi
Why hardcode the icon for this widget? Currently there is no icon on the overview and preview screen. Also the widget title probably needs to be cleaned up.

https://user-images.githubusercontent.com/5798170/267653830-b671c69e-d160-49f7-bc28-74aaaecbcc9a.png

2023-09-14 06:04 UTC, pwltr commented on src/screens/Widgets/Widget.tsx
>  							<>
Unnecessary nesting, remove

```
{
<>
...
</>
}
```

2023-09-14 06:04 UTC, pwltr commented on src/hooks/widgets.ts
> +					// TODO: Use reader.getField(field.name) after merging and publishing https://github.com/synonymdev/slashtags-feeds/pull/11
This is merged now

2023-09-14 06:04 UTC, pwltr commented on src/hooks/widgets.ts
> +const cache: { [url: string]: { config: SlashFeedJSON } } = {};
Can we use the web relay client store as a caching layer since it already has all the data? Or what is the purpose of having it? Curious if you say this makes sense. Maybe the client/reader can be smart and use the store as cache by default (and take a param to skip the cache). I think this is a feature every user of the lib would like to have so should be included if possible.

2023-09-14 07:08 UTC, Nuhvi commented on src/components/LuganoFeedWidget.tsx
> +	'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAABQrSURBVHgB7V0LkJTVlf7+ZmCY6cGBmWEGUIfhERXEDCaaBKgoo6BWQIVYqyi
Hardcode because Bitkit still can't reliably load png images (raw binary), and converting this icon into SVG was an enormous pain that didn't work out in the end.

What do you mean by cleaning up the title?

2023-09-14 07:10 UTC, Nuhvi commented on src/hooks/widgets.ts
> +					// TODO: Use reader.getField(field.name) after merging and publishing https://github.com/synonymdev/slashtags-feeds/pull/11
Not published yet, will check with @rbndg

2023-09-14 07:12 UTC, Nuhvi commented on src/hooks/widgets.ts
> +const cache: { [url: string]: { config: SlashFeedJSON } } = {};
We can, but because it is async and on disk, React keeps having flashes of empty images until the web relay client loads the image. This cache is blocking and in memory.

Let me know if I should remove it and you don't care about such flashes.

2023-09-14 07:14 UTC, Nuhvi commented on src/hooks/widgets.ts
> +const cache: { [url: string]: { config: SlashFeedJSON } } = {};
I can make an in-memory cache in the web relay, but the interface is still async, which means React will still render the empty image slot then hydrate it it when the promise resolves on the nextTick, so again you will probably get this flash.

2023-09-14 08:46 UTC, pwltr commented on src/components/LuganoFeedWidget.tsx
> +	'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAABQrSURBVHgB7V0LkJTVlf7+ZmCY6cGBmWEGUIfhERXEDCaaBKgoo6BWQIVYqyi
Okay, for the title it should probably be 'Plan B Forum' instead of 'PlanB forum'. But can this hardcode as well since we're already doing that for the image.

2023-09-14 08:49 UTC, pwltr commented on src/hooks/widgets.ts
> +const cache: { [url: string]: { config: SlashFeedJSON } } = {};
I'm okay with leaving it this way, doesn't need to happen now. I feel like loading the image async from the store would allow us to show the fallback image while loading but we can try that another time.

2023-09-14 08:49 UTC, pwltr approved these changes

2023-09-14 12:35 UTC, limpbrains approved these changes

2023-09-14 12:37 UTC, merged