test(scan): improve scan tests
synonymdev/bitkit-react-native pull request #1272
Opened 2023-09-25 17:27 UTC by pwltr

### Description

Improved tests for scanning feature

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [x] Detox test
- [ ] Unit test
- [ ] No test

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2023-09-26 13:46 UTC, coreyphillips requested changes

2023-09-26 13:46 UTC, coreyphillips commented on src/screens/TreasureHunt/Airdrop.tsx
> +	const { attemptId, state, winType } = chest;
May need a wrapper or check around this. Managed to receive the following error. "Cannot read property 'attemptId' of undefined". The image is from an error in `Prize.tsx`, but the same logic applies.

![Simulator Screenshot - iPhone 14 - 2023-09-26 at 08 48 48](https://github.com/synonymdev/bitkit/assets/8532651/415a79c3-fd49-48d8-8901-6e8f8fb139ba)

2023-09-26 13:46 UTC, coreyphillips commented on src/screens/TreasureHunt/Airdrop.tsx
> +		};
If able, we should define these methods outside of useEffect.

2023-09-26 13:46 UTC, coreyphillips commented on src/navigation/bottom-sheet/TreasureHuntNavigation.tsx
> +		};
If able, we should define `getChest` outside of `useEffect`.

2023-09-26 13:46 UTC, coreyphillips commented on src/screens/TreasureHunt/Prize.tsx
> +	const { attemptId, state, winType } = chest;
May need a wrapper or check around this. Managed to receive the following error. "Cannot read property 'attemptId' of undefined".

![Simulator Screenshot - iPhone 14 - 2023-09-26 at 08 48 48](https://github.com/synonymdev/bitkit/assets/8532651/18c8ea17-6f6f-4380-a3fd-810f3d93568b)

2023-09-26 13:46 UTC, coreyphillips commented on src/screens/TreasureHunt/prizes.ts
> +				'Clouds gather, and a huge thunder bolt hits the treasure chest, liquifying most of the coins. Only 100 sats are left intact.',
```suggestion
				'Clouds gather, and a huge thunderbolt hits the treasure chest, liquifying most of the coins. Only 100 sats are left intact.',
```

2023-09-26 13:46 UTC, coreyphillips commented on src/utils/scanner.ts
>  	}
I don't think it's needed because I don't think it's likely, but it's possible some users may try testing Bitkit on testnet during the event. So for these two conditions, we may want to check that unless `__DEV__` they are using mainnet. If they are not using mainnet, we can display a toast message suggesting that they switch to it in Settings.

2023-09-27 14:12 UTC, pwltr commented on src/screens/TreasureHunt/Prize.tsx
> +	const { attemptId, state, winType } = chest;
Should be fixed by moving logic to reducer.

2023-09-27 14:14 UTC, pwltr commented on src/utils/scanner.ts
>  	}
Added checks

2023-09-27 14:17 UTC, pwltr commented on src/screens/TreasureHunt/Airdrop.tsx
> +		};
I wouldn't bother with optimizing performance for this code since it will be probably be removed again soon, if we do and up keeping it I'll clean it up in a couple of places. Also these functions are defined in an onMount useEffect so they will only ever be instantiated once anyways.

2023-09-27 21:27 UTC, coreyphillips approved these changes

2023-09-28 06:42 UTC, merged