feat: new ldk backup server restore
synonymdev/bitkit-react-native pull request #1294
Opened 2023-10-06 13:18 UTC by Jasonvdb

### Description

- Enables backing up and restoring from new backup server.
- Reverts back to deprecated backup server if no backup found on new server

### Linked Issues/Tasks

Does not resolve existing restore issues it should prevent further ones from occurring.
[Add any links to GitHub issues or Asana tasks that are relevant to this pull request.
](https://github.com/synonymdev/bitkit/issues/770)
https://github.com/synonymdev/bitkit/issues/770

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### QA Notes

Backup and restoring lightning funds should be reliable now

2023-10-09 09:56 UTC, limpbrains commented
should performRemoteLdkBackup be removed?

Also list in  Settings -> Backup and Restore screen doesn't represent actual state now. We need a way to get backup info from ldk to update it

2023-10-09 10:55 UTC, limpbrains requested changes

2023-10-09 10:55 UTC, limpbrains commented on src/store/actions/backup.ts
> +	}
this throws "Error: Request failed. Missing response from backup server."
I believe we should return { backupExists: false in this case  }

2023-10-09 13:21 UTC, Jasonvdb commented on src/store/actions/backup.ts
> +	}
Might be a server issue here, if there is no backup then the list is just empty. I don't want to assume an error means there's no backup. I'll get back to you on this.

2023-10-09 13:24 UTC, Jasonvdb commented
> should performRemoteLdkBackup be removed?

I was thinking let me remove it right after we've done a few rounds of live testing. Just in case.

> Also list in Settings -> Backup and Restore screen doesn't represent actual state now. We need a way to get backup info from ldk to update it

True. Now we don't really have a last backup time to display. I do have a self check function for the backups maybe we can  run this when this view is loaded to show the state.

2023-10-09 13:35 UTC, limpbrains commented on src/store/actions/backup.ts
> +	}
I'm testing with server from development.template. I've created a wallet using master branch, then I'm trying to restore in using new-ldk-backups and I'm getting this error

2023-10-09 17:03 UTC, limpbrains approved these changes

2023-10-10 16:20 UTC, Jasonvdb commented on src/store/actions/backup.ts
> +	}
I've updated the env with new backup server. SSL was required as well as a backend update.

2023-10-10 18:49 UTC, merged