feat: android e2e tests
synonymdev/bitkit-react-native pull request #1360
Opened 2023-11-01 16:37 UTC by limpbrains

### Description

Detox for android

### Type of change

Refactoring

### Tests

Detox test

2024-06-17 12:01 UTC, pwltr requested changes

2024-06-17 12:01 UTC, pwltr commented on e2e/helpers.js
> +	await sleep(100); // wtf?
Not sure if that fixes it but according to docs `waitFor` must have a `withTimeout` otherwise it doesn't do anything.

```suggestion
	await waitFor(element(by.id('NewWallet'))).toBeVisible().withTimeout(2000);
	await sleep(100); // wtf?
```

https://github.com/nubank/detox/blob/master/docs/APIRef.waitFor.md

2024-06-17 12:01 UTC, pwltr commented on package.json
> +    "react-native-camera-kit": "14.0.0-beta15",
Podfile needs to be updated too

2024-06-17 12:13 UTC, limpbrains commented on e2e/helpers.js
> +	await sleep(100); // wtf?
This is a link to outdated version of docs from 7 years ago.
I can't find anything like this on wix.github.io
https://wix.github.io/Detox/docs/api/expect

2024-06-17 12:16 UTC, limpbrains commented on package.json
> +    "react-native-camera-kit": "14.0.0-beta15",
updated

2024-06-17 12:17 UTC, limpbrains commented
Had to push an update, but before that there were a series of 5 uninterrupted successful test runs
And before that around 10

2024-06-17 12:19 UTC, pwltr approved these changes

2024-06-17 12:43 UTC, limpbrains commented
wtf
```
BUILD SUCCESSFUL in 15m 14s
3066 actionable tasks: 3066 executed
After running the build command, Detox could not find your app at the given binary path:
	android/app/build/outputs/apk/release/app-release.apk
```

2024-06-17 13:40 UTC, pwltr commented
It's probably because of https://github.com/synonymdev/bitkit/pull/1992, try changing it to `app-x86_64-release.apk` or `app-x86_64-debug.apk`

2024-06-17 14:09 UTC, limpbrains commented
Is it possible only do x86_64 build for detox tests? This might speedup the build/test

2024-06-17 14:35 UTC, pwltr commented
yeah I think like this in detoxrc should work:

`$ ./gradlew :app:assembleDebug -PreactNativeArchitectures=x86_64`

2024-06-17 17:34 UTC, merged

2024-07-04 11:08 UTC, catch-21 commented
Reviewed the tests and CI runs. We can definitely make some improvements such as remvoing hard-coded waits in favour of checking e.g. that backups have succeeded, but it looks stable and the time saving is not worthwhile at this time. LGTM.