refactor: use react-native-quick-crypto, remove rn-nodify
synonymdev/bitkit-react-native pull request #1392
Opened 2023-11-28 12:49 UTC by pwltr

### Description

Replaces `crypto` calls with `react-native-quick-crypto` which should offer way better performance since it's using JSI/C++. Allows us to remove `rn-nodify` and all Node core module polyfills. Also replaces `text-encoding` with [faster](https://github.com/anonyco/FastestSmallestTextEncoderDecoder#benchmarks) alternative `fastestsmallesttextencoderdecoder`.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2023-11-28 13:28 UTC, limpbrains requested changes

2023-11-28 13:28 UTC, limpbrains commented on package.json
> +    "@craftzdog/react-native-buffer": "^6.0.5",
please exact versions in dependencies

2023-11-28 13:31 UTC, limpbrains commented on ios/Podfile.lock
> +  - MMKVCore (1.3.0)
I'm qurious why MMKV version changed? I don't have it on my local maching when I do `pod install` maybe you should try `pod install --repo-update` ?

2023-11-28 13:35 UTC, pwltr commented on package.json
> +    "@craftzdog/react-native-buffer": "^6.0.5",
done

2023-11-28 13:35 UTC, pwltr commented on ios/Podfile.lock
> +  - MMKVCore (1.3.0)
done, but now it updated it to newer versions. Not sure why it always downgrades some packages on my machine.

2023-11-28 14:25 UTC, limpbrains approved these changes

2023-12-11 14:57 UTC, coreyphillips commented
Seems to break being able to set custom Electrum servers in Settings->Advanced->Electrum Server

2023-12-11 15:12 UTC, coreyphillips approved these changes

2023-12-12 10:47 UTC, merged