fix(profile): #1397 fix links not opening in app
synonymdev/bitkit-react-native pull request #1398
Opened 2023-11-30 10:47 UTC by flaviomoceri

### Description

If you add a valid link to your profile for example https://www.instagram.com/{username}, if the "Instagram" application is not present on your device, if you click on it it opens the link correctly via browser, but if instead I have the application installed on the device, even if I click it nothing happens.

This PR fixes this bug - https://github.com/synonymdev/bitkit/issues/1397

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/63161412/e39c251f-67ee-407a-9c36-e4f84b0825f1

2023-11-30 10:53 UTC, pwltr approved these changes

2023-11-30 16:23 UTC, limpbrains requested changes

2023-11-30 16:23 UTC, limpbrains commented on src/utils/helpers.ts
> +		const supported = await Linking.openURL(url);
Why are you using .openURL here, should it be .canOpenURL ?

2023-11-30 17:35 UTC, flaviomoceri commented on src/utils/helpers.ts
> +		const supported = await Linking.openURL(url);
Because if the url is valid like `https://www.instagram.com/bitfinex`, if I don't have the Instagram application and I click on the link it works correctly by opening the browser and the supported variable returns `true`, however if I have the application instagram for some reason even if I click, nothing happens because the supported variable returns `false`.

However, if I use `openURL` this bug does not occur and returns true if it can display the link via browser or app, or it returns error and prints it.

Instagram is obviously just one example.

Watch the video in this [PR](https://github.com/synonymdev/bitkit/pull/1398#issue-2018370058) and the video in [issue](https://github.com/synonymdev/bitkit/issues/1397#issue-2018358722) and you should see the difference.

2023-12-01 16:15 UTC, limpbrains commented on src/utils/helpers.ts
> +		const supported = await Linking.openURL(url);
Sorry, I wasn't clear.
I'm looking at the code and you are doing same 2 Linking.openURL calls
const supported = await Linking.openURL(url);
and then
await Linking.openURL(url);

Is this correct?

2023-12-01 16:40 UTC, flaviomoceri commented on src/utils/helpers.ts
> +		const supported = await Linking.openURL(url);
Yes, maybe I can write more cleanly so as not to repeat the same code

The first time I need it to check whether the URL is valid or not, if it returns `true` I open it, otherwise it prints what comes back

2023-12-04 12:11 UTC, pwltr commented on src/utils/helpers.ts
> +		const supported = await Linking.openURL(url);
`await Linking.openURL` doesn't return anything so the second call is definitely redundant, see https://reactnative.dev/docs/linking#openurl. That being said I'm not sure it's okay to remove the check with `canOpenURL()` for this helper, it may be needed for non-http(s) URLs. Can you check why `supported` would be `false` for your instagram with `canOpenURL` being there? Doesn't make sense to me maybe there is a bug with that method or we need to do something else?

2023-12-05 10:26 UTC, pwltr requested changes

2023-12-05 10:26 UTC, pwltr commented on src/components/ProfileLinks.tsx
> +};
We don't care about a return value in this case:

```suggestion
const openURL = async (url: string): Promise<boolean> => {
	try {
		await Linking.openURL(url);
	} catch (err) {
		console.log('Cannot open url: ', url);
	}
};
```

2023-12-05 11:00 UTC, pwltr approved these changes

2023-12-05 11:55 UTC, limpbrains commented on src/components/ProfileLinks.tsx
> +		console.error('Error opening URL: ', err);
console.error is redundant

2023-12-05 11:55 UTC, limpbrains approved these changes

2023-12-05 12:44 UTC, merged