New Slideshow screen
synonymdev/bitkit-react-native pull request #141
Opened 2022-03-28 19:51 UTC by limpbrains

- Slideshow on welcome screen
- new logos
- GlowingBarckground component based on `react-native-skia`
- new creating wallet animation
- NHaasGrotesk font

https://user-images.githubusercontent.com/155891/162168224-e29b3e57-724b-4d82-b7b6-72f94e51d948.mp4

2022-04-07 13:48 UTC, coreyphillips requested changes
I believe the MMKV version in the Podfile.lock file is off and refusing to install due to the updates.

I would suggest:
 - Deleting the Pods folder and Podfile.lock file in the ios directory.
 - Run pod install in the ios directory.
 - Commit the newly generated Podfile.lock file.

Otherwise, LGTM!

2022-04-10 13:26 UTC, limpbrains commented
fixed MMKV version and android swiper bug

2022-04-12 11:43 UTC, coreyphillips approved these changes

2022-04-14 07:29 UTC, Jasonvdb approved these changes

2022-04-14 07:33 UTC, merged