Add the Support section following the new design
synonymdev/bitkit-react-native pull request #1443
Opened 2023-12-20 07:42 UTC by flaviomoceri

### Description

I added the entire support section following the new design and I modified the about section in accordance with the design.

Everything works correctly, but before pushing the changes to master, this [PR](https://github.com/synonymdev/synonym-website/pull/87) must be sent to production

There are probably things to improve, so please feel free to provide me with feedback so I can make changes.

The only thing that needs to be added are the user logs and I have already asked @pwltr for help on this, I can push this into a separate PR because it's not sure we are capable of doing it

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [X] No test

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/63161412/4e031a91-8736-47e9-8053-cd3c41a479d7

2023-12-20 09:21 UTC, limpbrains commented on src/screens/Settings/ReportIssue/index.tsx
> +			/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
this is not a valid email regex. 
for example, email can contain cyrilic characters.
х@ыва.ру 
I suggest not to validate it using regex. Just test that it includes "@" and something before and after it

https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression

2023-12-20 10:44 UTC, flaviomoceri commented on src/screens/Settings/ReportIssue/index.tsx
> +			/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
Great to know, I got this feature from [here](https://github.com/synonymdev/synonym-website/blob/fc23e854f24c532fd1a562417f63ba6b07279a96/pages/synonym/contact.tsx#L107), so I probably need to do a PR for this

Would something like that be okay?

```
const validateEmail = (emailText: string): boolean => {
		if (emailText.indexOf('@') !== -1) {
			const [beforeAt, afterAt] = emailText.split('@');
			if (beforeAt.length > 0 && afterAt.length > 0) {
				return true;
			}
		}
		return false;
	};
```

2023-12-20 10:58 UTC, limpbrains commented on src/screens/Settings/ReportIssue/index.tsx
> +			/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
yes, something like this

2023-12-20 11:10 UTC, limpbrains commented on src/utils/i18n/locales/it/settings.json
> +    "label_message": "Problema o domanda",
these translations will be overwritten during next transifex -> bitkit sync.
It is better to do translations there, then in github PRs

2023-12-20 11:44 UTC, flaviomoceri commented on src/utils/i18n/locales/it/settings.json
> +    "label_message": "Problema o domanda",
So do I have to delete the changes made in it/settings.json and en/settings.json?

If I do this until the next transifex is done, it will show like this

![1](https://github.com/synonymdev/bitkit/assets/63161412/7e28b1da-25bf-4e60-979c-2778150b237e)

2023-12-20 12:08 UTC, limpbrains commented on src/utils/i18n/locales/it/settings.json
> +    "label_message": "Problema o domanda",
Keep all changes in en/settings
All translations you did for it/settings add to Transifex after PR is merged

2023-12-20 13:37 UTC, flaviomoceri commented on src/utils/i18n/locales/it/settings.json
> +    "label_message": "Problema o domanda",
Ok, thanks for the explanation

to be sure, do I delete the changes in it/settings and when PR is merged I report the translation to transifex or do I not need to delete anything and when PR is merged I report the translation to transifex?

2023-12-20 13:40 UTC, limpbrains commented on src/utils/i18n/locales/it/settings.json
> +    "label_message": "Problema o domanda",
Second option.

2023-12-22 13:19 UTC, pwltr requested changes

2023-12-22 13:19 UTC, pwltr commented on src/screens/Settings/About/index.tsx
> +					//},
I think we're okay to remove all this commented out code now.

2023-12-22 13:19 UTC, pwltr commented on src/screens/Settings/About/index.tsx
> +							<DiscordIcon height={24} width={24} />
The discord icon is visibly smaller than the other icons, should be roughly the same height.

2023-12-22 13:19 UTC, pwltr commented on .env.development.template
> +API_FORM=https://synonym.to/api/chatwoot
A more descriptive name would be good here like `CHATWOOT_API`. Also, this needs to be added in `env.ts` and `env.d.ts`

2023-12-22 13:19 UTC, pwltr commented on src/utils/i18n/locales/en/settings.json
> +		"report": "Report issue",
```suggestion
		"report": "Report Issue",
```

2023-12-22 13:19 UTC, pwltr commented on src/screens/Settings/SupportSettings/index.tsx
> +						</Pressable>
Again icons should have the same height here

2023-12-22 13:19 UTC, pwltr commented on src/utils/i18n/locales/en/settings.json
> +		"title_unsuccess": "Sent unsuccessfully",
"Sent unsuccessfully" doesn't make much sense. Please ask Aldert for the correct failed state for this.

2023-12-22 13:19 UTC, pwltr commented on src/utils/i18n/locales/en/settings.json
> +		"text_unsuccess_button": "Ok"
```suggestion
		"text_unsuccess_button": "OK"
```

2023-12-22 13:19 UTC, pwltr commented on src/screens/Settings/ReportIssue/index.tsx
> +				</Text01S>
Couple of unnecessary uses of `<Trans />` component, use the text directly like:

```suggestion
				<Text01S style={styles.text} color="gray1">
					{t('support.report_text')}
				</Text01S>
```

2023-12-22 13:19 UTC, pwltr commented on src/screens/Settings/ErrorFormSent/index.tsx
> +const ErrorFormSent = ({
Would move these files into the `ReportIssue` folder and name `FormError` and `FormSuccess`

2023-12-22 13:19 UTC, pwltr commented on src/components/LabeledInput.tsx
> +						minHeight={multiline ? 40 * numberOfLines : 52}
Make sure you don't break this component for other places like `AddContact` and `ProfileLink`. The text fields should be larger there.

2023-12-22 14:39 UTC, flaviomoceri commented
@pwltr Thanks so much, I should have made all the changes, if anything else needs to be changed, please tell me

2024-01-03 11:47 UTC, pwltr requested changes

2024-01-03 11:47 UTC, pwltr commented on .env.development.template
> +CHATWOOT_API=https://synonym.to/api/chatwoot
Do we have this running on staging as well?

2024-01-03 11:47 UTC, pwltr commented on src/screens/Settings/ReportIssue/index.tsx
> +							returnKeyType="done"
This is not behaving correctly together with `multiline={true}` on iOS. Should be okay to use "default" (line break) since we have scrolling now.

```suggestion
							returnKeyType="default"
```

2024-01-03 12:18 UTC, flaviomoceri commented on src/screens/Settings/ReportIssue/index.tsx
> +							returnKeyType="done"
Done

2024-01-03 12:22 UTC, flaviomoceri commented on .env.development.template
> +CHATWOOT_API=https://synonym.to/api/chatwoot
Not yet, Miguel needs to review the PR and send the code to staging

But I think that even in staging it will not be easy to test it because when bitkit sends the axios request to `/api/chatwoot` the staging site is blocked by credentials, so the request will not be successful. You can test it locally or when it goes into production

2024-01-03 12:33 UTC, pwltr approved these changes

2024-01-11 09:50 UTC, limpbrains approved these changes

2024-01-11 09:52 UTC, limpbrains commented on .env.development.template
> +CHATWOOT_API=https://synonym.to/api/chatwoot
please, add it to .env.test.template as well

2024-01-11 10:11 UTC, flaviomoceri commented on .env.development.template
> +CHATWOOT_API=https://synonym.to/api/chatwoot
Done, thanks!

2024-01-11 12:09 UTC, limpbrains commented
Squash and merge it!

2024-01-11 12:24 UTC, merged

2024-01-11 12:27 UTC, flaviomoceri commented
Note: Unfortunately until this [PR](https://github.com/synonymdev/synonym-website/pull/89/) goes into production properly, when bitkit sends the request to https://synonym.to/api/chatwoot it will not work

I hope Reza updates the .env file as soon as possible