refactor(send): Denomination label now matches selected currency unit
synonymdev/bitkit-react-native pull request #1445
Opened 2023-12-21 16:19 UTC by flaviomoceri

### Description

Denomination label now matches selected currency unit

### Linked Issues/Tasks

https://app.asana.com/0/0/1205905791108240/f

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [X] No test

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/63161412/a015c6ac-ed58-4226-847e-0f735893953e

2023-12-22 12:17 UTC, pwltr requested changes

2023-12-22 12:17 UTC, pwltr commented on src/screens/Wallets/NumberPadButtons.tsx
> +							{nextUnit === 'fiat' && 'sats'}
In this component we can use `unit` directly and get rid of `nextUnit` for a small cleanup.

```suggestion
							{unit === EUnit.BTC && 'BTC'}
							{unit === EUnit.satoshi && 'sats'}
							{unit === EUnit.fiat && fiatTicker}
```

2023-12-22 15:17 UTC, flaviomoceri commented on src/screens/Wallets/NumberPadButtons.tsx
> +							{nextUnit === 'fiat' && 'sats'}
I made the changes, but perhaps I didn't understand your request. If necessary, provide me with more details please.

2023-12-22 16:30 UTC, pwltr requested changes

2023-12-22 16:30 UTC, pwltr commented on src/screens/Wallets/NumberPadButtons.tsx
> +							{unit === EUnit.fiat && 'sats'}
```suggestion
							{unit === EUnit.BTC && 'BTC'}
							{unit === EUnit.satoshi && 'sats'}
							{unit === EUnit.fiat && fiatTicker}
```

2023-12-22 16:38 UTC, flaviomoceri commented on src/screens/Wallets/NumberPadButtons.tsx
> +							{unit === EUnit.fiat && 'sats'}
But if I do this, the denomination label does not correspond to the selected monetary unit as requested in the changes made by aldert or I am missing something?

2023-12-29 19:08 UTC, pwltr commented on src/screens/Wallets/NumberPadButtons.tsx
> +							{unit === EUnit.fiat && 'sats'}
You didn't quite apply the suggestions correctly, please double-check. Maybe the confusion comes from `nextUnit` vs `unit`, those two are not the same.

2023-12-29 19:19 UTC, flaviomoceri commented on src/screens/Wallets/NumberPadButtons.tsx
> +							{unit === EUnit.fiat && 'sats'}
Yes, I probably don't understand something, however I made the requested changes, sorry about that

2023-12-29 19:30 UTC, pwltr approved these changes

2024-01-01 10:50 UTC, merged