build: regtest app variant
synonymdev/bitkit-react-native pull request #1458
Opened 2024-01-04 20:10 UTC by ovitrif

### Description

This PR adds support to build an app variant having `regtest` as default bitcoin network.

Aside to the default network, the regtest variant has:
- a different name: `Bitkit Regtest`
- a different id: 
  - Android: `to.synonym.bitkit.wallet.regtest`
  - iOS `to.synonym.bitkit.regtest`
- a monochrome icon
  <img src="https://github.com/synonymdev/bitkit/assets/4588074/340b2b2d-8507-4cb7-aaaa-4ecf98391015" width="200">

### Considerations
- It is expected have a `.env.production` file with the corresponding configurations.
- It is expected if an `.env.production.local` already exists, that it doesn't include required configs for building.
  This is because of the node scripts that are creating a temp file with the same name, overriding only the value of `WALLET_DEFAULT_SELECTED_NETWORK`.
- We could drop the node scripts and simply change the ENV var when creating the manual builds, this could mitigate issues if there are other relevant configs in the local prod env file.  
  Given this isn't a very repetitive process, it won't be too much work added to the manual process of creating the internal releases.

### To Test
**Android prerequisite:** You should have `adb` in your path.

#### 1️⃣ Regtest Android
1. Open a terminal in the root repo directory
2. Run `yarn bundle:regtest`
3. After completion, open an emulator from Android Studio
4. In terminal run `adb install android/app/build/outputs/apk/regtest/release/app-regtest-release.apk`
5. **Expect** to have the app `Bitkit Regtest` installed on the emulator
6. Open the app, skip intro, create a `New Wallet`
7. Tap the Cog icon to open Settings
8. Tap the Cog illustration multiple times until you see `Dev Options Enabled` popup
9. Tap `Advanced`
10. **Expect** Bitcoin Network to be set to `Regtest`

#### 2️⃣ Mainnet Android
1. Run `yarn bundle` in the same terminal from previous step
2. Await completion
3. run `adb install android/app/build/outputs/apk/mainnet/release/app-mainnet-release.apk`
4. **Verify** using the same flow as for Regtest that the Bitcoin Network is `Mainnet`

#### 3️⃣ Regtest iOS
1. Run `yarn bundle:regtest:ios` in repo root dir
2. Open the workspace in XCode, switch to the `bitkit.regtest` scheme
   > **Note:** Additional 1-time setup is required as described in this [medium post](https://medium.com/@fadilah.arifki29/deployment-ios-in-app-store-react-native-d845e99e8329)
   > - need to register the new bundle id, get certificates, etc
   > - also might need to create a separate app in TestFlight App Store Connect
3. Build the app for release
4. **Verify** using the same flow as for Android that the Bitcoin Network is `Regtest`
7. Switch to the `bitkit` scheme and build the release app
   > **Note:** It might be needed to might need to delete the `main.jsbundle` from the `./ios/` dir before building, I'm not 100% sure how this works and there's little info/docs online about it.
9. **Verify** the `Bitkit` app has the Bitcoin Network `Mainnet` and that it doesn't override the `Bitkit Regtest` app.

#### ➕ Other configurations
- Ensure `yarn start` can still run build and run the app on Android / iOS
- Ensure `yarn android` & `yarn ios` still works

### Linked Issues/Tasks

https://app.asana.com/0/0/1205821036778041/f

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

N/a - build setup.

### QA Notes

N/a - build setup.

2024-01-04 20:40 UTC, pwltr commented
Just making sure that normal development workflow works as expected and seems to be the case 👍

2024-01-04 20:42 UTC, pwltr requested changes, later dismissed

2024-01-04 20:42 UTC, pwltr commented on package.json
> +    "prebundle:regtest": "node ./scripts/pre-regtest-bundle.js",
These scripts seems to be duplicated with the `:ios` ones and also seem to be unsused? Or undocumented?

2024-01-04 20:42 UTC, pwltr commented on scripts/post-regtest-bundle.js
If these are just to backup the `.env` file I wouldn't worry about that, were not doing that either for the other env files

2024-01-04 20:57 UTC, ovitrif commented on scripts/post-regtest-bundle.js
Thanks.
They also create/then-delete a `.production.local.env` which is used to override the config value for the default wallet.

Though the simpler it can get the better IMHO, so I could for now remove the backup part 👍🏻

2024-01-04 21:01 UTC, ovitrif commented on package.json
> +    "prebundle:regtest": "node ./scripts/pre-regtest-bundle.js",
Indeed, I went this route of duplicating the pre/post but I ain't a big fan of it either 🙈 .

The other option I see is to have a `pre:regtest` + a `post:regtest` and simply run them before and after the current commands for bundling the regtest version 

That might be cleaner indeed 👍🏻

2024-01-04 21:08 UTC, pwltr commented on scripts/post-regtest-bundle.js
If that is the goal maybe adding another line in `postinstall.js` does the trick?

```
const createRegtestEnvFile = 'cp .env.production.regtest .env.production.local';
...
exec(createRegtestEnvFile);
```

2024-01-04 21:08 UTC, pwltr commented on package.json
> +    "prebundle:regtest": "node ./scripts/pre-regtest-bundle.js",
Any reason for the duplication though? Are these commands picked up in a build step or something? All of these do the same to their non ":ios" counterpart:

"prebundle:regtest:ios", "postbundle:regtest:ios", "bundle:regtest:ios"

2024-01-04 21:11 UTC, pwltr commented on scripts/post-regtest-bundle.js
This will also be run after `yarn install` so that would remove the need to do it explicitly.

2024-01-04 21:17 UTC, ovitrif commented on package.json
> +    "prebundle:regtest": "node ./scripts/pre-regtest-bundle.js",
> Any reason for the duplication though?
Well there are ^^, they follow the pre/post prefix automatically picked up by node, so basically they remove the need to explicitly run the 2 commands before and after the main script.
I.e. without them, at least of the bundling scripts would need to have:
```
yarn pre… && _theCurrentScript_ && yarn post
```
For example, let's say we remove the ios ones, then the `bundle:regtest:ios` would become:
```sh
yarn prebundle:regtest && react-native bundle --reset-cache --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle && yarn postbundle:regtest
```

Still, as mentioned earlier, not really favoring to keep them 👍🏻

2024-01-04 21:28 UTC, pwltr commented on package.json
> +    "prebundle:regtest": "node ./scripts/pre-regtest-bundle.js",
Oh I see now, I admit I was not aware you could do custom pre-/post- scripts like that. I think you can see where I was coming from haha. In that case I totally get it 👍

2024-01-05 13:00 UTC, ovitrif commented on scripts/post-regtest-bundle.js
Coming back to this, the reason I set it up this way was to only **temporarily** set the network to `Regtest`, then revert it back.
It's basically because this is only to be done when prepping an internal release build.

2024-01-08 12:59 UTC, pwltr requested changes, later dismissed

2024-01-08 12:59 UTC, pwltr commented on android/app/src/regtest/res/mipmap-anydpi-v26/ic_launcher_round.xml
> +    <background android:drawable="@color/amber_dark" />
```suggestion
    <background android:drawable="@color/black" />>
```

2024-01-08 13:01 UTC, pwltr commented on scripts/post-regtest-bundle.js
For this did you mean to backup and use `.env.production`? That would make sense to me, but you'd also need to get all the other env values into the bundle if that is not the case yet.

2024-01-08 13:01 UTC, ovitrif commented on android/app/src/regtest/res/mipmap-anydpi-v26/ic_launcher_round.xml
> +    <background android:drawable="@color/amber_dark" />
Thanks for spotting this 👍🏻 , feels that I missed merging something, let me check again and in the process address this as well

2024-01-08 13:08 UTC, ovitrif commented on scripts/post-regtest-bundle.js
I've went the route to create `.env.production.local` which will partially override env vars declared in the `.env.production`, because IMHO that would most likely be non-existent.*
In this particular case we only care for the wallet default network, so the created `…local` file only declares that. The `react-native-dotenv` dependency we use handles that by merging the values from the two files, giving priority to the `….local` file. This works for different environments as well, in this case `production`. Since there is only one value to "overwrite", all the other configs will have the value from the `.production` file.


\*But if such a file does exist, I didn't want it to be overwritten directly, hence the backup script.

let me know if this is clear to understand 👍🏻

2024-01-08 13:11 UTC, pwltr commented on scripts/post-regtest-bundle.js
Ok that's cool, good solution imo.

2024-01-08 13:42 UTC, ovitrif commented on android/app/src/regtest/res/mipmap-anydpi-v26/ic_launcher_round.xml
> +    <background android:drawable="@color/amber_dark" />
I get it now, seems I forgot to update the `round` one 🤦🏻 
Thanks once for spotting i 🙇🏻

2024-01-08 13:46 UTC, ovitrif commented on android/app/src/regtest/res/mipmap-anydpi-v26/ic_launcher_round.xml
> +    <background android:drawable="@color/amber_dark" />
Resolved (and rebased with master)

2024-01-08 14:24 UTC, pwltr commented
Followed instructions and Android is working for me, when building for iOS I get:

`Unable to load contents of file list: '/Users/phil/Dev/synonymdev/bitkit/ios/Pods/Target Support Files/Pods-bitkit/Pods-bitkit-frameworks-Debug.Regtest-input-files.xcfilelist'`

@ovitrif Any ideas? Could have to do with the regtest assets

2024-01-08 14:32 UTC, ovitrif commented
> Followed instructions and Android is working for me, when building for iOS I get:
> 
> `Unable to load contents of file list: '/Users/phil/Dev/synonymdev/bitkit/ios/Pods/Target Support Files/Pods-bitkit/Pods-bitkit-frameworks-Debug.Regtest-input-files.xcfilelist'`
> 
> @ovitrif Any ideas? Could have to do with the regtest assets

Can you try a `yarn clean:ios` beforehand? 🤔 

Honestly I'm not sure which one of the commands have fixed it in my case, but I do recall having to resolve the same issue.

`clean:ios` seems to tap into the iOS dependencies, but it might have bean `clan` itself.

Xcode build issues feel very unstable to me, for example I couldn't get the app to build via Xcode for 2 days, then randomly it started to work 🤷🏻

2024-01-08 14:43 UTC, pwltr commented
> @pwltr Can you try a `yarn clean:ios` beforehand? 🤔

Yeah that works! Should have known 🤷‍♂️. It's stuck on the splash screen now though:

```
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
*** Terminating app due to uncaught exception 'RCTFatalException: No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.', reason: 'No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
	2   Bitkit Regtest                      0x0000000104b03d10 RCTGetFatalHandler + 0
	3   Bitkit Regtest                      0x0000000104b19ea4 __28-[RCTCxxBridge handleError:]_block_invoke + 516
	4   libdispatch.dylib                   0x0000000107c200f0 _dispatch_call_block_and_release + 24
	5   libdispatch.dylib                   0x0000000107c2193c _dispatch_client_callout + 16
	6   libdispatch.dylib                   0x0000000107c315e4 _dispatch_main_queue_drain + 1228
	7   libdispatch.dylib                   0x0000000107c31108 _dispatch_main_queue_callback_4CF + 40
	8   CoreFoundation                      0x00000001803f1a30 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	9   CoreFoundation                      0x00000001803ec148 __CFRunLoopRun + 1936
	10  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
	11  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
	12  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
	13  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
	14  Bitkit Regtest                      0x000000010494c74c main + 96
	15  dyld                                0x0000000106aa1544 start_sim + 20
	16  ???                                 0x0000000106bb20e0 0x0 + 4407894240
	17  ???                                 0x2962000000000000 0x0 + 2981945903272689664
)
libc++abi: terminating due to uncaught exception of type NSException
``` 

> Xcode build issues feel very unstable to me, for example I couldn't get the app to build via Xcode for 2 days, then randomly it started to work 🤷🏻

I doubt this was the issue in your case but I find myself having to delete `ios/.xcode.env.local` often times.

2024-01-10 20:31 UTC, ovitrif commented
> Yeah that works! Should have known 🤷‍♂️. It's stuck on the splash screen now though:
```
No bundle URL present.
```
Thank you @pwltr for testing and sharing this.

I tried again in a fresh clone and I got the same issue when running the `bitkit.regtest` scheme via Xcode.

The thing is, this won't work anyways to set the default network to regtest, because it takes configuration from `.env.development`. But I do agree for testing purposes it makes sense to be able to actually run the `regtest` app, not only install it.

After a lot of trial & error, I found a fix that got it working for me.

---

It's important mention that **the release configuration works differently**, and I can't test it given I don't have the certificates, so I personally can't tell for sure if it will work right.

I'd really appreciate if @Jasonvdb could check if the setup works for iOS `Regtest.Release`, since that's the main problem the PR is trying to solve.

2024-01-16 12:10 UTC, ovitrif commented
Note: if we can't get the current setup to work for iOS release builds, this might be an alternative, though it would take some time to set-up fastlane:
- [React Native DevOps Guide](https://medium.com/@tgpski/react-native-devops-guide-2d8e4755ebee)

2024-01-30 17:38 UTC, ovitrif commented
Updated with:
- rebase on `master` d62e7a2d
- squash into 2 commits:
  1. Android build
  2. iOS build

2024-02-13 12:17 UTC, ovitrif commented
Put on hold until we can build iOS releases using the self-hosted build machine. This way it will enable me to troubleshoot and verify it on iOS as well

2024-02-28 18:18 UTC, ovitrif commented
@Jasonvdb I revisited this changeset and made the setup much simpler, also now I'm pretty sure the iOS regtest app should build correctly.

I also updated the testing steps in PR description as well as build instructions for regtest app in `BUILD.md`.

Happy to get your feedback when you can check this again 🙏🏻

2024-04-30 18:25 UTC, ovitrif commented
Closing this for now, given it's stale for a long time.
We can always reopen if we reassess its priority.

2024-04-30 18:25 UTC, closed without merging