react-native-lightning Removal
synonymdev/bitkit-react-native pull request #146
Opened 2022-04-23 20:56 UTC by coreyphillips

This PR:
 - Removes all instances of react-native-lightning from the app.
 - Separates types from exchange-rate/index.ts.
 - Deletes LightningCard.tsx, lnd.conf, LndLogs.tsx.
 - Temporarily removes activity, fiat & backup tests.
 - Deletes react-native-lightning mock.
 - Adds protobufjs dependency to package.json.
 - Updates yarn.lock & Podfile.lock accordingly.

2022-04-23 21:04 UTC, coreyphillips commented
I tried my best to be surgical in this PR.
I left or commented out a few of the old Lightning components and methods in the event we can re-use some of the previous logic and flow when implementing LDK. High chance they too will be removed, but it makes for a good reference when implementing nonetheless.
Once some additional omnibolt logic and components are removed and LDK is in place we'll want to restore the tests removed in this PR.

2022-04-29 13:58 UTC, limpbrains requested changes

2022-04-29 13:58 UTC, limpbrains commented on package.json
> +    "react-native": "0.66.4",
It's already 0.67.3 in master

2022-04-29 14:01 UTC, Jasonvdb commented on __tests__/transactions.ts
> -		const signedPsbtRes = await signPsbt({
Can we not keep the above code? Up until LND signs. Because we'll use this test with LDK psbt channel funding. If it breaks things then also fine, we can add it back when it's time.

2022-04-29 14:04 UTC, Jasonvdb approved these changes

2022-04-29 14:07 UTC, coreyphillips commented on __tests__/transactions.ts
> -		const signedPsbtRes = await signPsbt({
`lnrpc.ReadyForPsbtFunding.create` was a removed dependency breaking the test so I pulled it. We'll have to reincorporate the psbt funding logic once ldk is added.

2022-04-29 14:08 UTC, Jasonvdb commented on __tests__/transactions.ts
> -		const signedPsbtRes = await signPsbt({
Ah right ok

2022-04-29 14:21 UTC, coreyphillips commented on package.json
> +    "react-native": "0.66.4",
- This version number was improperly upgraded to 0.67 from 0.66 and needs a proper upgrade in the future. 
- v0.67 also causes the ios build to fail after recent xcode/Mac OS updates after the introduction of skia in the project.

2022-04-29 14:28 UTC, limpbrains approved these changes

2022-04-29 14:56 UTC, merged