feat(wallet): Show info toast when hiding balance on Home
synonymdev/bitkit-react-native pull request #1498
Opened 2024-01-15 15:36 UTC by ovitrif

### Description

Added a toast message to explain the hidden wallet balance state for user clarity and resolution.

### Linked Issues/Tasks

Design v45 (see slack message or Figma file)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/4588074/c480a1dc-6cc8-4d60-9bee-b8eab383e4c0

### QA Notes

See above video.

2024-01-15 15:41 UTC, ovitrif commented
Checked with Aldert and confirmed this is needed also in the wallet detail view.

2024-01-15 17:25 UTC, pwltr approved these changes

2024-01-16 09:37 UTC, ovitrif commented
⚠️ to make the toast show only once (the first time the user performs the action),
as suggested by Alders (thanks @flaviomoceri)

2024-01-16 11:07 UTC, coreyphillips approved these changes

2024-01-16 13:21 UTC, ovitrif commented
> ⚠️ Need to make the toast show only once (the first time the user performs the action), as suggested by Aldert

Updated the PR with logic to show the toast only once.

2024-01-16 13:44 UTC, pwltr requested changes

2024-01-16 13:44 UTC, pwltr commented on src/store/slices/user.ts
> +	ignoresHideBalanceToast: false,
Looks good, but whenever you're adding a field to the redux store you have to add a migration in `store/migrations.ts` to add the new field to persisted store otherwise people updating the app will not have this field initially which will throw an error. Also update the version for `persistConfig` in `store/index.ts`

2024-01-16 14:03 UTC, ovitrif commented on src/store/slices/user.ts
> +	ignoresHideBalanceToast: false,
Thanks a lot for this remark, I've added the suggested changes for the store migration
Please have another look when possible 🙏🏻

2024-01-16 14:20 UTC, pwltr approved these changes

2024-01-16 17:29 UTC, coreyphillips approved these changes

2024-01-17 09:45 UTC, ovitrif commented
The PIN e2e test keeps failing repeatedly but I saw it failing on other PRs as well, don't really think the problem comes from the changes.

I will retrigger the e2e tests again.

2024-01-17 13:53 UTC, limpbrains commented
And now tests will fail because blocktank staging is down 🫠

2024-01-18 13:22 UTC, ovitrif commented
Blocktank staging still down, hence the tests kept failing

2024-01-18 13:29 UTC, merged