Slashtags integration
synonymdev/bitkit-react-native pull request #150
Opened 2022-05-05 13:57 UTC by Jasonvdb

- Added @synonymdev/react-native-slashtags 
- Updated to @react-native-clipboard/clipboard
- Add/update slashtags profiles
- Slashtags redux store
- React hook for keeping SDK in sync with redux store

https://user-images.githubusercontent.com/5300488/166933967-22884c09-7310-4f8d-a99a-bb42a2dfbe74.mov

2022-05-06 10:15 UTC, limpbrains requested changes

2022-05-06 10:15 UTC, limpbrains commented on src/store/actions/slashtags.ts
> +};
`resetSlashtagsStore` is not an async function, but you call it later with `await`

2022-05-06 10:15 UTC, limpbrains commented on src/hooks/slashtags.tsx
> +			for (let index = 0; index < profileNames.length; index++) {
You can use `for ... in` to iterate over Object keys

2022-05-06 10:15 UTC, limpbrains commented on src/hooks/slashtags.tsx
> +			}
Is it ok, that you can alter profile with `updateProfile`, but it will not be synced, because number of profiles has not been changed?

2022-05-06 10:21 UTC, limpbrains commented
Just a couple of questions:
- maybe it would be nicer, if `SlashtagsContext` would provide `slashtags` without `.current` prefix?
- as I understand, app waits while slashtags webview is ready. Maybe, while it is not, you can delay app render to prevent user from interacting with slashtags? Then you won't need in all those `api not ready` checks

2022-05-06 11:59 UTC, Jasonvdb commented on src/hooks/slashtags.tsx
> +			}
Yes this is fine, it does not need to be triggered again. The profile just needs to be updated with it's new slashtag after it's added to the SDK.

2022-05-06 12:08 UTC, Jasonvdb commented
> * maybe it would be nicer, if `SlashtagsContext` would provide `slashtags` without `.current` prefix?

I think I did try this but it caused the context to not automatically be updated. That `slashtags` value is actually a `useRef()` and it seemed to only work properly when the whole ref is passed to the provider [here](https://github.com/synonymdev/react-native-slashtags/blob/1bf00fb837960ca77b5de4726545b46eee52309d/lib/src/index.tsx#L43). 

>* as I understand, app waits while slashtags webview is ready. Maybe, while it is not, you can delay app render to prevent user from interacting with slashtags? Then you won't need in all those api not ready checks

I don't think it's necessary to add in an artificial delay every time the user opens the app. Nothing is remotely loaded, all slashtags web code is bundled with the app so it shouldn't take long to be ready. Especially when app is not in debug mode. The chances of someone scanning a QR or adding a new profile before it loads is unlikely but if it does happen we can look at this.

2022-05-06 12:49 UTC, Jasonvdb commented on src/hooks/slashtags.tsx
> +			for (let index = 0; index < profileNames.length; index++) {
Updated

2022-05-06 12:50 UTC, Jasonvdb commented on src/store/actions/slashtags.ts
> +};
Fixed. Same thing with all the reset functions, not sure why that happened.

2022-05-06 12:52 UTC, limpbrains commented on src/hooks/slashtags.tsx
> +			for (let index = 0; index < profileNames.length; index++) {
You can do even better `for (const i in profiles) {`

2022-05-06 12:52 UTC, limpbrains approved these changes

2022-05-06 12:54 UTC, Jasonvdb commented on src/hooks/slashtags.tsx
> +			for (let index = 0; index < profileNames.length; index++) {
I still need the `name` (key) inside the loop though?

2022-05-06 13:54 UTC, limpbrains commented on src/hooks/slashtags.tsx
> +			for (let index = 0; index < profileNames.length; index++) {
Sorry, missed that. It is fine

2022-05-09 17:04 UTC, coreyphillips approved these changes

2022-05-09 17:04 UTC, merged