fix(lightning): update transfer UI
synonymdev/bitkit-react-native pull request #1551
Opened 2024-02-09 14:55 UTC by pwltr

### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Add any links to GitHub issues or Asana tasks that are relevant to this pull request.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [x] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-02-09 15:38 UTC, pwltr commented on src/utils/wallet/index.ts
> -	});
@coreyphillips had to move this out of the function because a circular dependency causing weird issues.

2024-02-09 18:22 UTC, coreyphillips commented on src/utils/wallet/index.ts
> -	});
We need this to switch over everything to the new network. Where's the circular dependency?

2024-02-09 18:46 UTC, pwltr commented on src/utils/wallet/index.ts
> -	});
The line has been moved [here](https://github.com/synonymdev/bitkit/blob/d558994693f09d6315a530eaf667dd481d6d55ad/src/screens/Settings/Bitcoin/BitcoinNetworkSelection.tsx#L33) so it should still behave as expected. I wasn't able to track down the circular import. There also was another one causing `HEADER_HEIGHT` not to be applied which is why I duplicated the variable to where it was imported [here](https://github.com/synonymdev/bitkit/blob/d558994693f09d6315a530eaf667dd481d6d55ad/src/screens/Wallets/index.tsx#L42). Not sure why these are popping up all of a sudden, I know we have a ignore rule for the warnings that would show this but wasn't an issue until now.

2024-02-10 17:58 UTC, coreyphillips requested changes

2024-02-10 17:58 UTC, coreyphillips commented on src/store/actions/wallet.ts
> +			const confs = tx.height === -1 ? 1 : headerHeight - tx.height + 1;
```suggestion
			const confs = tx.height < 1 ? 0 : headerHeight - tx.height + 1;
```
Seeing a confirmation miscalculation. Possibly from this snippet.
<img width="662" alt="Screenshot 2024-02-10 at 12 48 03 PM" src="https://github.com/synonymdev/bitkit/assets/8532651/587d93cc-2edb-4745-9069-5d1796610852">

2024-02-10 17:59 UTC, coreyphillips commented
Other than that, everything LGTM!

2024-02-12 11:04 UTC, limpbrains approved these changes

2024-02-12 11:28 UTC, closed without merging