feat(wallet): Add isElectrumThrottled state
synonymdev/bitkit-react-native pull request #1586
Opened 2024-02-22 14:14 UTC by coreyphillips

### Description
- Bitkit now displays a toast whenever it receives an error when refreshing or rescanning to display to the user.
- Bitkit will also look for batch limit exception warnings when scanning or refreshing and inform the user accordingly.
- Adds `isElectrumThrottled` to `ui` state.
- Adds `handlerRefreshError` to `refreshBeignet` & `rescanAddresses` methods.
- Upgrades beignet to `0.0.24`.

### Type of change
- [x] New feature (non-breaking change which adds functionality)

### Tests
- [x] No test

### QA Notes
I believe Reza bumped the limits so hopefully we'll never see the throttle toast, but it can be triggered by continuously refreshing and rescanning Bitkit using a wallet with an extremely high gap limit and several spread out UTXO's. Beware, spreading out UTXO's, shrinking the gap limit and then rescanning from 0 may make it appear as though funds were lost and not related to being throttled.

2024-02-22 14:37 UTC, pwltr requested changes

2024-02-22 14:37 UTC, pwltr commented on src/store/migrations/index.ts
> +			},
The migration is not needed in this case since `ui` state is not persisted

2024-02-22 14:46 UTC, coreyphillips commented on src/store/migrations/index.ts
> +			},
Reverted [here](https://github.com/synonymdev/bitkit/pull/1586/commits/479f61b4bcdb9727eb08ef9598f69c1d29d42fb0).

2024-02-22 15:59 UTC, pwltr approved these changes

2024-02-22 17:07 UTC, merged

2024-02-23 10:05 UTC, JeanlChristophe commented
@coreyphillips please don't forget to add to each ticket:

- Project
- Sprint
- Milestone
Thanks