Slashtags SDK's integration
synonymdev/bitkit-react-native pull request #160
Opened 2022-06-13 06:12 UTC by Nuhvi

Read commit messages.

If you aren't running a DHT relay, it will show an error message, but I didn't want to add the script for running a relay in dev environment to this repo just yet.

You can run a DHT relay as follows:

```js
const { setupRelay } = require('dht-universal/setup-relay.js')

const main = async () => {
  const { port } = await setupRelay({
    wsServerOptions: { port: 8888 }
  })
  const relay = 'ws://localhost:' + port

  console.log('DHT mainnet Relay: ' + relay)
}

main()
```

And make sure it is in a directory with its own `package.json` not the same as Bitkit `package.json`.

```js
{
  "devDependencies": {
    "dht-universal": "^0.4.1"
  }
}
```
<img width="439" alt="Screen Shot 2022-06-20 at 11 11 12" src="https://user-images.githubusercontent.com/40009100/174555796-3b3bccc0-f4f6-47b0-8a62-32e9e429c6c0.png">

2022-06-20 10:19 UTC, limpbrains requested changes

2022-06-20 10:19 UTC, limpbrains commented on src/App.tsx
> +	}, [wallets[selectedWallet]['seedHash']]);
useMemo doen't support async functions, you need to use useEffect to call `getSlashtagsPrimaryKey` and then useState to store it in state component

2022-06-20 10:19 UTC, limpbrains commented on src/components/SlashtagsProvider.tsx
> +			});
Is it ok, that SDK.init will exception will be eaten by `.catch` and it will try to setState with broken sdk futher?

2022-06-20 10:22 UTC, Nuhvi commented on src/components/SlashtagsProvider.tsx
> +			});
Fair enough I will change that.

2022-06-20 12:17 UTC, Jasonvdb commented on package.json
>      "react-native-webview": "^11.18.2",
Remove react-native-webview while you're at it. It's only used for the previous hack.

2022-06-24 10:42 UTC, Jasonvdb approved these changes

2022-06-24 17:36 UTC, coreyphillips approved these changes

2022-06-24 17:48 UTC, limpbrains approved these changes

2022-06-24 20:23 UTC, merged