feat(wallet): Implement Rust Address Generator
synonymdev/bitkit-react-native pull request #1627
Opened 2024-04-09 15:01 UTC by coreyphillips

### Description

- Removes `nodejs-mobile` dependency and related files.
- Adds `react-native-address-generator` and implements it accordingly.
- This update brings with it a significant performance improvement when generating addresses.

### Linked Issues/Tasks
- #1617

### Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improving code without creating new functionality)

### Tests
- [x] No test

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-04-16 01:17 UTC, coreyphillips commented
@limpbrains, does the `react-native-address-generator` mock [here](https://github.com/synonymdev/bitkit/blob/a44eaf8283e7cc24b1d0714a08eef1f3902a2c9c/__mocks__/react-native-address-generator/index.ts) look right?

Can't seem to get it sorted.

2024-04-22 20:54 UTC, limpbrains requested changes

2024-04-22 20:54 UTC, limpbrains commented on src/utils/wallet/index.ts
> +				return '';
Why return empty string instead of throwing an error? Who will handle this empty string?

2024-04-22 20:58 UTC, coreyphillips commented on src/utils/wallet/index.ts
> +				return '';
This is for `react-native-ldk`, in the event an issue occurred generating an address since it only expects a string.

2024-04-22 21:00 UTC, coreyphillips commented
I'll be closing this PR in favor of [this one](https://github.com/synonymdev/bitkit/pull/1717).

2024-04-22 21:35 UTC, closed without merging