fix(settings): Fixes Change Pin Setting
synonymdev/bitkit-react-native pull request #1631
Opened 2024-04-11 14:24 UTC by coreyphillips

### Description
- Enforces pin attempt counter for the "Change Pin" setting.
- Closes #1630

### Linked Issues/Tasks
- #1630

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Tests
- [x] No test

### QA Notes
Forwards user to Auth screen when attempting to Change Pin in order to enforce the pin counter.

2024-04-19 09:28 UTC, pwltr commented
You have a failing e2e test @coreyphillips

2024-04-22 11:05 UTC, limpbrains requested changes

2024-04-22 11:05 UTC, limpbrains commented on src/screens/Settings/Security/index.tsx
> +									navigation.navigate('ChangePin2');
Should be `navigation.navigate('ChangePin');`
`ChangePin2` is a second screen where you confirm that your PIN is correct

2024-04-22 17:29 UTC, coreyphillips commented on src/screens/Settings/Security/index.tsx
> +									navigation.navigate('ChangePin2');
Thanks! Fixed [here](https://github.com/synonymdev/bitkit/pull/1631/commits/2105f508facb42e4ead5dcf19a154d990ef5bac8).

2024-04-22 17:29 UTC, coreyphillips commented
> You have a failing e2e test @coreyphillips

Resolved as of [this](https://github.com/synonymdev/bitkit/pull/1631/commits/2105f508facb42e4ead5dcf19a154d990ef5bac8) commit.

2024-04-22 17:33 UTC, limpbrains approved these changes

2024-04-22 18:05 UTC, pwltr approved these changes

2024-04-22 20:09 UTC, merged

2024-05-01 12:28 UTC, catch-21 commented
@coreyphillips This fixes the problem. Although, the user must now enter their PIN to unlock the option to enter their existing PIN to change their PIN. Would it be possible to add the countdown to the existing PIN entry to avoid the extra step?