Lightning onboarding
synonymdev/bitkit-react-native pull request #167
Opened 2022-06-28 14:56 UTC by limpbrains

https://user-images.githubusercontent.com/155891/176212074-f5587604-aa40-4abd-8189-f9c90a02adad.mp4

2022-06-28 18:52 UTC, coreyphillips approved these changes

2022-06-28 21:06 UTC, MiguelMedeiros commented
There is a problem with the alignment at the "spending balance".
The bitcoin symbol seems wrong (a little bit to the right).
Idk if it's the fontWeight, or the font it self.

![image](https://user-images.githubusercontent.com/5798170/176287390-1761fa1f-15ee-4629-8704-cc177e16d516.png)
![image](https://user-images.githubusercontent.com/5798170/176287830-3d6720ab-cf9d-4fe7-a85b-f09c9d29a31b.png)

We should also change the style of the amount in fiat. The decimals are colored in gray.

![image](https://user-images.githubusercontent.com/5798170/176292469-15222327-fdb0-4b07-ac01-b58a6c6d594b.png)

2022-06-28 21:27 UTC, MiguelMedeiros commented
Also found a leak here: "excessive number of pending callbacks"
How to simulate the error: Just go left and right with the slider a few times.

Suggestion: maybe the solution could be adding a debouncer to slow down the number of calculations.

![image](https://user-images.githubusercontent.com/5798170/176300400-9727e784-d084-4628-a25b-cf65a850a1f8.png)

![image](https://user-images.githubusercontent.com/5798170/176300771-4cd30946-3308-41fb-9ae0-5315ee2b12f5.png)

2022-06-28 21:31 UTC, MiguelMedeiros commented
I've found the "spending balance" alignment error. There is something wrong with the Bitcoin symbol that causes that misalignment. Take a look:

https://user-images.githubusercontent.com/5798170/176301771-09c9ba94-1803-47d8-b0fe-c29c86d18d76.mp4

2022-06-28 21:33 UTC, MiguelMedeiros requested changes

2022-06-28 21:33 UTC, MiguelMedeiros commented on src/screens/Lightning/Introduction.tsx
> +	},
Should add a `16px` margin (left and right) to the `buttonContainer`:
```suggestion
	buttonsContainer: {
		marginLeft: 16,
		marginRight: 16,
		flexDirection: 'row',
		marginTop: 70,
	},
```
![image](https://user-images.githubusercontent.com/5798170/176269909-0ca12cf9-e0bc-4e26-994d-c3792215bac5.png)

2022-06-28 21:33 UTC, MiguelMedeiros commented on src/screens/Lightning/CustomSetup.tsx
> +						/>
Following the v15 no Figma, Aldert removed the button Icon.

```suggestion
						<Button
							text="Enter custom amount"
							style={styles.buttonCustom}
							onPress={(): void => setKeybrd((k) => !k)}
						/>
```

## Figma Preview: 
![image](https://user-images.githubusercontent.com/5798170/176270841-6f990827-6903-4e84-a444-6c2dd2df6151.png)

2022-06-28 21:33 UTC, MiguelMedeiros commented on src/screens/Lightning/Introduction.tsx
> +					</DisplayHaas>
Change text of the main title to match v15 Figma.
![image](https://user-images.githubusercontent.com/5798170/176271591-7bdbbc16-293f-4fe4-85e9-7e2ae8f86769.png)

```suggestion
					<DisplayHaas>
						Instant{' '}
						<DisplayHaas style={styles.headline2}>
							payments.
						</DisplayHaas>
					</DisplayHaas>
```

2022-06-28 21:33 UTC, MiguelMedeiros commented on src/screens/Lightning/CustomSetup.tsx
> +						</ThemedView>
This button does not exist in Figma's layout.
```suggestion
```

![image](https://user-images.githubusercontent.com/5798170/176278528-df4eafd5-de17-4c01-899c-e6d67d2d540a.png)

2022-06-28 21:42 UTC, MiguelMedeiros requested changes

2022-06-28 21:42 UTC, MiguelMedeiros commented on src/screens/Lightning/QuickSetup.tsx
> +							<Caption13Up color="purple">SAVING</Caption13Up>
Should be "savings" instead of "saving".

```suggestion
							<Caption13Up color="purple">SAVINGS</Caption13Up>
```

2022-06-28 21:54 UTC, MiguelMedeiros commented
Also found a bug when you try to enter a big amount of `spending balance`.
It happens in the `quick setup` and also when you try to `enter a custom amount`.

https://user-images.githubusercontent.com/5798170/176306801-069479d6-1516-4c70-b13f-3c44bcf1f150.mp4

2022-06-29 09:48 UTC, limpbrains commented on src/screens/Lightning/Introduction.tsx
> +	},
fixed

2022-06-29 09:52 UTC, limpbrains commented on src/screens/Lightning/CustomSetup.tsx
> +						</ThemedView>
fixed

2022-06-29 09:55 UTC, limpbrains commented
I think these issues are outside of this PR scope:

**Memory leak**
I think it is not because of wrong slider behavior, I saw it before, but haven't debug it. After removing `AmountToggle` component from the screen I couldn't reproduce this issue. Probably this issue lies somewhere in bitcoins <-> fiat conversion logic. 
By the way FancySlider already has throttle under the hood

**Bitcoin sign** 
I'm aware of the problem. Probably, NHaasGrotesk font, that we are using misses this symbol and app falls back to some system default font, which is not suitable.

Overall fiat and bitcoin formatting and representation needs to be changed:
- lighning (sats) symbol
- grey decimals
- hiding balance
- switching sats/bitcoin/fiat
and etc, all of this should be another big PR.

2022-06-29 10:17 UTC, limpbrains commented
> Also found a bug when you try to enter a big amount of `spending balance`. It happens in the `quick setup` and also when you try to `enter a custom amount`.
> overflow-nan.mp4

fixed

2022-06-29 21:19 UTC, MiguelMedeiros requested changes

2022-06-29 21:19 UTC, MiguelMedeiros commented on src/screens/Lightning/NumberPadLightning.tsx
> +		}
The total amount is 21.000.000 not 210.000.000.
I think we should set the max supply to 21Mi btc instead of getting the default value.
Take a look:

https://user-images.githubusercontent.com/5798170/176546222-acd27f95-19a7-4216-9852-13512bd3e3ab.mp4



```suggestion
		if (amount > 2.1e15) {
			amount = 2.1e15;
		}
```

2022-06-30 08:14 UTC, limpbrains commented on src/screens/Lightning/NumberPadLightning.tsx
> +		}
correct

2022-06-30 11:21 UTC, MiguelMedeiros approved these changes

2022-06-30 13:24 UTC, Jasonvdb approved these changes

2022-06-30 13:25 UTC, merged