Create profile
synonymdev/bitkit-react-native pull request #168
Opened 2022-06-29 21:38 UTC by Nuhvi

This PR includes the Profile section of the Handoff v15, showing the Profile image and name in the header, navigating to the first Onboarding screen, Edit the profile for the first time and the profile page with its QR and details.

Feel free to point to any anti-patterns or inefficient ways for doing things the React[-native] way, I was mostly focused on getting Slashtags to work.

(details are left empty for now until Aldert gives as new UX for how to edit arbitrary details, or define few ones that Bitkit will support) 

~* Please check https://github.com/synonymdev/bitkit/pull/160 for instructions about how to run a relay (I will publish this in a CLI soon to make it easier I promise)~

Run a daemon, to enable a dht relay:

```
npm install -g @synonymdev/slashtags-cli && slash daemon start
```

![simulator_screenshot_689E39F5-EF78-4432-9765-5799F85281EE](https://user-images.githubusercontent.com/40009100/176548858-af56c4eb-8f2d-43fa-83d3-a2a46c46a0fc.png)

2022-06-30 08:46 UTC, limpbrains commented
You can run `npm run lint:fix` this will show eslint errors, like inline styles.

2022-06-30 08:46 UTC, limpbrains requested changes

2022-06-30 08:46 UTC, limpbrains commented on src/components/ProfileCard.tsx
> +					<SlashtagURL style={{ marginTop: 16 }} url={profile?.id} />
please avoid using inline styles

2022-06-30 08:46 UTC, limpbrains commented on src/components/SlashtagURL.tsx
> +			style={{ ...style, display: 'flex', flexDirection: 'row' }}
style is not always an Object and could be an array. The safe way of merging styles would be [StyleSheet.compose](https://reactnative.dev/docs/stylesheet#compose)

2022-06-30 08:46 UTC, limpbrains commented on src/navigation/root/RootNavigator.tsx
> -import ProfileNavigator from '../profile/ProfileNavigator';
Looks like you don't use ProfileNavigator anymore, can it be removed then?

2022-06-30 08:46 UTC, limpbrains commented on src/screens/Profile/ProfileOnboarding.tsx
> +				</TitleHaas>
Please, don't use inline colors, grab them from theme using `useHook` hook.

Or if you are using one of the components from `styles/components` all of them accept `color` prop,
like <TitleHaas color="brand" style={styles.headline}>own Profile</TitleHaas>

name of the colors in Figma are the same as in theme

2022-06-30 08:57 UTC, limpbrains requested changes

2022-06-30 08:57 UTC, limpbrains commented on src/screens/Profile/ProfileOnboarding.tsx
> +					}}>
We have a set of Typography components, like <Headline /> <Title /> <Tex01M /> they should cover 90% of all possible variations.
You can find name of the component in Figma, in Typography section
<img width="929" alt="изображение" src="https://user-images.githubusercontent.com/155891/176636366-8a0e779b-5d93-4fa2-a6e1-4431447ef5e3.png">

Here it would be `<Text01S color="gray1>...</Text01S>`

2022-06-30 09:25 UTC, Nuhvi commented on src/navigation/root/RootNavigator.tsx
> -import ProfileNavigator from '../profile/ProfileNavigator';
It can, wasn't sure if I should just yet though. I will consider this as a confirmation and remove it.

2022-07-07 14:16 UTC, limpbrains approved these changes

2022-07-08 12:53 UTC, Jasonvdb approved these changes

2022-07-08 12:54 UTC, merged