feat: update design
synonymdev/bitkit-react-native pull request #1696
Opened 2024-04-19 08:41 UTC by pwltr

### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Closes https://github.com/synonymdev/bitkit/issues/1684

### Tests

- [x] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-04-19 09:54 UTC, limpbrains requested changes

2024-04-19 09:54 UTC, limpbrains commented on e2e/backup.e2e.js
> +			.withTimeout(60000);
I prefer to keep the original logic. I remember there was an issue with the ﻿.toBeVisible() check. Maybe it is not an issue because we moved to a Mac Mini runner, but still.

2024-04-19 09:54 UTC, limpbrains commented on e2e/helpers.js
> -	}
same

2024-04-20 12:44 UTC, pwltr commented on e2e/backup.e2e.js
> +			.withTimeout(60000);
Fixed

2024-04-24 17:17 UTC, coreyphillips commented
Multiple "Advanced" & "Quick Setup" views get pushed to the navigation stack from the "Transfer Funds" view.


https://github.com/synonymdev/bitkit/assets/8532651/f77f0422-8275-4e88-8d95-9a07b30e8c9c

2024-04-24 17:59 UTC, pwltr commented
> Multiple "Advanced" & "Quick Setup" views get pushed to the navigation stack from the "Transfer Funds" view.

Fixed

2024-04-25 13:32 UTC, limpbrains approved these changes

2024-04-25 14:06 UTC, coreyphillips approved these changes

2024-04-25 16:48 UTC, merged