Bitcoin unit: change layout styles and add new icons
synonymdev/bitkit-react-native pull request #170
Opened 2022-07-01 18:09 UTC by MiguelMedeiros

## Description
New layout to Bitcoin unit screen:  `settings > general > bitcoin unit`

## Preview
https://user-images.githubusercontent.com/5798170/176947800-9ad27be1-73a6-4cfb-b4f0-03a1afbe6719.mp4

2022-07-02 10:26 UTC, limpbrains requested changes
`icons/check.svg` icon is not used

I don't like Idea to put new icons in assets/icons as svg images, since we have all other in .ts files. in this case you can't set custom color to this icon. 

I don't like current approach either, because it is hard to find correct icons. But if we want to switch the approach, we better do it all at once.

You can find bitcoin-unit-satoshis.svg as `<LightningIcon />`

2022-07-07 06:29 UTC, limpbrains requested changes

2022-07-07 06:29 UTC, limpbrains commented on src/assets/icons/wallet.ts
> -<path d="M0 16C0 7.16344 7.16344 0 16 0V0C24.8366 0 32 7.16344 32 16V16C32 24.8366 24.8366 32 16 32V32C7.16344 32 0 24.8366 0 16V16Z" fill="${color}" fill-opacity="0.08"/>
`fill="${color}"` allows you to change icon's color and you removed it, why?

2022-07-07 06:29 UTC, limpbrains commented on src/assets/icons/wallet.ts
> -<path d="M0 16C0 7.16344 7.16344 0 16 0C24.8366 0 32 7.16344 32 16C32 24.8366 24.8366 32 16 32C7.16344 32 0 24.8366 0 16Z" fill="${color}" fill-opacity="0.08"/>
same here

2022-07-07 13:24 UTC, MiguelMedeiros commented on src/assets/icons/wallet.ts
> -<path d="M0 16C0 7.16344 7.16344 0 16 0V0C24.8366 0 32 7.16344 32 16V16C32 24.8366 24.8366 32 16 32V32C7.16344 32 0 24.8366 0 16V16Z" fill="${color}" fill-opacity="0.08"/>
Ops! My bad! Will fix it!

2022-07-07 13:24 UTC, MiguelMedeiros commented on src/assets/icons/wallet.ts
> -<path d="M0 16C0 7.16344 7.16344 0 16 0C24.8366 0 32 7.16344 32 16C32 24.8366 24.8366 32 16 32C7.16344 32 0 24.8366 0 16Z" fill="${color}" fill-opacity="0.08"/>
Ops! My bad! Will fix it!

2022-07-07 14:12 UTC, limpbrains commented
also remove unused svg files

2022-07-08 12:29 UTC, limpbrains approved these changes

2022-07-08 12:58 UTC, Jasonvdb approved these changes

2022-07-08 12:58 UTC, merged