Easter egg screen
synonymdev/bitkit-react-native pull request #171
Opened 2022-07-01 21:56 UTC by MiguelMedeiros

## Description 
Add an easter egg screen to settings menu.

## Preview

https://user-images.githubusercontent.com/5798170/176972045-0f529c67-1c13-4900-b4ac-af8e417f6ded.mp4

2022-07-02 10:18 UTC, limpbrains requested changes

2022-07-02 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +		<GlowingBackground bottomRight="#FF6600">
Please use `useColors` hook to get colors

2022-07-02 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +				<Display style={styles.subtitle}>Orange Pill?</Display>
<Display already has all fontStyle, textAlign, fontWeight and etc you don't need to copy-past them again.

to set correct color, please use `<Display color="brand">` these are the same colors as in `styles/colors.ts`

2022-07-02 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +		width: 281,
I think instead of providing width, you need to set margin/padding = 48px, this will work correctly for all devices

2022-07-02 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +		gap: 40,
there is no gap support yet for React Native

2022-07-02 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +		borderRadius: 64,
There is no boxShadow, backdropFilter in RN

<Button already has correct borderRadius, height, flex and etc, no need to put them here

2022-07-03 18:10 UTC, coreyphillips commented
```
            ,`.
          ,'` |        _.-.
         ,`   |      ,',' /
         :    |    ,','  ;
          \   :   / /   /
           \   `.' (  ,'
          ,''     _  `.
        ,'      (o_)  `\
     . (,.)   _.--     :
   -..`/(  .-'_..-    `|
    .-'\,`. `-._       ;
        `._           /__
        ,':)-.._   _.(:::`.
        |'\         / /`:::|
      ,' \ :       : :   `:|
     /   : |       | |     \
    :    | |       : :..---.:
    |    | ;       ,`._`-.|_ `.
    |    |'      ,'._  `. `. |_\
    |    :      /`-. `.  `. `.  :
    :     \    : __ `. `.  `. \ ;
     \     \   |.  /  `. \   \ /
     |\     `..: `. __  \ \   /
     ' `  .:::::\  `. /  \ \,'
       .::::::::::-..'_..-'
```
cereal base crew egg plunge merge merit end bus kick snap match lab also high reopen task coconut fox adult boring dad bless release

2022-07-05 00:06 UTC, MiguelMedeiros commented
Fixed, @limpbrains ! :+1:

2022-07-05 10:18 UTC, limpbrains approved these changes
These are small imperfections, PR is ready

2022-07-05 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +		maxWidth: 281,
you should use margins instead of maxWidth

2022-07-05 10:18 UTC, limpbrains commented on src/screens/Settings/EasterEgg/index.tsx
> +		maxWidth: 343,
same here, maxWidth can be removed, since you have margings

2022-07-05 10:21 UTC, limpbrains commented
> cereal base crew egg plunge merge merit end bus kick snap match lab also high reopen task coconut fox adult boring dad bless release

This is correct BIP39, but empty :(

2022-07-05 12:24 UTC, MiguelMedeiros commented
> This is correct BIP39, but empty :(

Yeah hahaha, I've already tried to add passphrases like: bunny, easter egg, etc.
No success, yet! :)

2022-07-06 21:13 UTC, MiguelMedeiros commented
ops @coreyphillips hahahaha
`62e25ef7aa0e434516af020c78fd292cc73b5e4dea38d163bdc774fc112437bd`

2022-07-07 14:10 UTC, limpbrains commented
So, what was it ?

2022-07-07 14:11 UTC, limpbrains approved these changes

2022-07-07 16:56 UTC, MiguelMedeiros commented
@limpbrains  you've got to dig deeper to find the **rabbit** hole!

2022-07-08 12:55 UTC, Jasonvdb approved these changes

2022-07-08 12:56 UTC, merged