Contacts
synonymdev/bitkit-react-native pull request #172
Opened 2022-07-05 11:58 UTC by Nuhvi

2022-07-07 15:07 UTC, limpbrains requested changes

2022-07-07 15:07 UTC, limpbrains commented on src/components/LabeledInput.tsx
> +		color: '#8E8E93',
Here and bellow: 
When you insert <Text, please use components from styles/components.
Colors can be obtained using `useColors` hook, or by providing color to our components 
Here it would be <Caption13Up color="gray1"

2022-07-07 15:07 UTC, limpbrains commented on src/components/SlashtagURL.tsx
> +			}}
Looks like this function doesn't needs to be async

2022-07-07 15:07 UTC, limpbrains commented on src/screens/Contacts/Contacts.tsx
> +import { TouchableOpacity } from 'react-native-gesture-handler';
why do you need TouchableOpacity from react-native-gesture-handler and not from 'react-native'?

2022-07-07 15:07 UTC, limpbrains commented on src/screens/Contacts/ContactsOnboarding.tsx
> +	},
I think this will not work, because this styles will be applied to <TouchableOpacity in Button component, not to the text
If you really need to overwrite text style for button, you can do:
```
<Button text={<Text01B>bla bla bla</Text01B>}
```

2022-07-07 15:07 UTC, limpbrains commented on src/screens/Profile/ProfileEdit.tsx
> +						/>
Inside BottomSheetWrapper it is better to use BottomSheetTextInput, it will work nice with on screen keyboard.  
Please test this screen with on screen keyboard

2022-07-08 13:23 UTC, limpbrains commented
FYI: I renamed some components:
TitleHaas -> Title
DisplayHaas -> Display

2022-07-20 09:23 UTC, Nuhvi commented on src/screens/Profile/ProfileEdit.tsx
> +						/>
Used `BottomSheetTextInput` in `LabeledInput` not sure if this is enough, and didn't get a chance to test with an on screen keyboard yet. honestly, I don't know how even.

2022-07-27 04:21 UTC, Nuhvi commented
closing to open again from `synonymdev:contacts`

2022-07-27 04:21 UTC, closed without merging