fix(ui): fix share on Android
synonymdev/bitkit-react-native pull request #1724
Opened 2024-04-23 16:44 UTC by pwltr

### Description

Closes #1697

2024-04-23 17:32 UTC, limpbrains requested changes

2024-04-23 17:32 UTC, limpbrains commented on ios/Podfile.lock
> +  - MMKVCore (1.3.3)
Why MMKV is changing here? Looks like it is still the same at package.json

2024-04-23 17:53 UTC, pwltr commented on ios/Podfile.lock
> +  - MMKVCore (1.3.3)
I don't know it always sets it to this version for me. Looking at latest `react-native-mmkv` version this is the version of MMKV specified in podspec./

2024-04-23 18:00 UTC, pwltr commented on ios/Podfile.lock
> +  - MMKVCore (1.3.3)
If you do `yarn clean:ios` does it upgrade to MMKV 1.3.4 for you?

2024-04-24 11:47 UTC, limpbrains approved these changes

2024-04-24 11:57 UTC, merged