Fix Max Fee Checks
synonymdev/bitkit-react-native pull request #1732
Opened 2024-04-25 04:04 UTC by coreyphillips

### Description
- Adds max fee checks to the `FeeRate` & `FeeCustom` views to prevent users from selecting or setting a fee-rate above what the max is.
- Adds `getFeeInfo` method.
- Resolves UI bug in #1619

### Linked Issues/Tasks
- #1619

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Tests
- [x] No test

### QA Notes
When setting fees during the send flow, the max fee checks should be in place and prevent you from setting a value above the `maxFee` provided by Beignet's `getFeeInfo` method.

2024-04-25 10:57 UTC, limpbrains requested changes

2024-04-25 10:57 UTC, limpbrains commented on src/screens/Wallets/Send/FeeCustom.tsx
> +				description: `${maxFee} sats/vbyte`,
These strings should be added to i18n vocabulary

2024-04-25 13:06 UTC, coreyphillips commented on src/screens/Wallets/Send/FeeCustom.tsx
> +				description: `${maxFee} sats/vbyte`,
Updated [here](https://github.com/synonymdev/bitkit/pull/1732/commits/a5b326c9673a28feacc8ad6db39b87831f5da67e).

2024-04-25 15:22 UTC, limpbrains approved these changes

2024-04-25 16:01 UTC, merged

2024-05-27 15:10 UTC, catch-21 commented
Verified in v118