chore: remove ST v1
synonymdev/bitkit-react-native pull request #1748
Opened 2024-04-26 12:29 UTC by limpbrains

### Description

- remove v1 -> v2 migration code
- remove all v1 libs 
- remove ldk old restore
- remove ldk recover screen
- remove AuthWidget
- remove old env variables
- add error message if user tries to scan slashauth url

I will squash commits after review

### Linked Issues/Tasks

### Type of change

Refactoring

### Tests

No test

### QA Notes

Install prev version, add slashauth, upgrade, try to use slashauth. Widget should disapear

2024-05-12 08:45 UTC, Nuhvi commented
@limpbrains I wonder if we should just merge this PR, test the performance of the app, to confirm that the DHT is causing most of the issues, then consider our options to add slashauth again in the light of that expirement.

2024-05-12 09:26 UTC, limpbrains commented
Good idea, I will test it tomorrow

2024-05-15 11:40 UTC, pwltr requested changes

2024-05-15 11:40 UTC, pwltr commented on tsconfig.json
> +		"jsx": "react",
This option is set by `@react-native/typescript-config/tsconfig.json` with `"jsx": "react-native"

2024-05-15 11:48 UTC, limpbrains commented on tsconfig.json
> +		"jsx": "react",
Removed

2024-05-15 11:53 UTC, pwltr requested changes

2024-05-15 11:53 UTC, pwltr commented on src/utils/i18n/locales/en/slashtags.json
> +	"auth_depricated_msg": "Slashauth is deprecated. Please Bitkit Beta."
```suggestion
	"auth_depricated_msg": "Slashauth is deprecated. Please use Bitkit Beta."
```

2024-05-15 11:54 UTC, pwltr approved these changes
Tested and LGTM

2024-05-15 15:49 UTC, merged