fix: remove custom amount button from LN channel flow
synonymdev/bitkit-react-native pull request #1824
Opened 2024-05-14 13:47 UTC by limpbrains

### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Add any links to GitHub issues or Asana tasks that are relevant to this pull request.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-06-02 12:31 UTC, pwltr commented
> remove custom fee button from Custom and Quick flows. Keyboard now triggered by pressing on the Amount, as it is in Figma

You sure this is how it should work? The design still has this button.

2024-06-10 13:06 UTC, limpbrains commented
> > remove custom fee button from Custom and Quick flows. Keyboard now triggered by pressing on the Amount, as it is in Figma
> 
> You sure this is how it should work? The design still has this button.

I've updated the PR. Button is not removed

2024-06-12 10:23 UTC, pwltr requested changes

2024-06-12 10:23 UTC, pwltr commented on src/screens/Lightning/QuickConfirm.tsx
> +				</TouchableOpacity>
For consistency this should use `<Pressable />` and only wrap `<Money />` component

2024-06-12 10:23 UTC, pwltr commented on src/screens/Lightning/CustomSetup.tsx
> -		setTextFieldValue('0');
I believe this was added after a user asked for it so they don't have to delete the current amount themself

2024-06-12 10:34 UTC, limpbrains commented on src/screens/Lightning/QuickConfirm.tsx
> +				</TouchableOpacity>
fixed

2024-06-12 10:35 UTC, limpbrains commented on src/screens/Lightning/CustomSetup.tsx
> -		setTextFieldValue('0');
reverted

2024-06-12 10:37 UTC, pwltr approved these changes

2024-06-12 12:56 UTC, merged