fix: onboarding text layout
synonymdev/bitkit-react-native pull request #1858
Opened 2024-05-22 12:26 UTC by limpbrains

### Description

- Do not limit text width
- if Arrow can't fit, move it below the text
- move line breaking logic to language file

### Linked Issues/Tasks

#1840

### Type of change

Bug fix

### Tests

No test

### Screenshot / Video

<img width="200px" src="https://github.com/synonymdev/bitkit/assets/155891/78eaa2d3-e560-4f1d-a612-61562d899468" />

<img width="200px" src="https://github.com/synonymdev/bitkit/assets/155891/3daa8ba0-a85b-445a-8bd7-b34c7373030e" />

2024-05-23 11:33 UTC, pwltr requested changes

2024-05-23 11:33 UTC, pwltr commented on src/utils/i18n/locales/en/onboarding.json
> +	"empty_wallet": "To get\nstarted\n<accent>send\nBitcoinnBitcoin</accent>\nto your\nwallet.",
```suggestion
	"empty_wallet": "To get\nstarted\n<accent>send\nBitcoin</accent>\nto your\nwallet.",
```

2024-05-23 11:33 UTC, pwltr commented on src/screens/Lightning/Success.tsx
> +			navTitle={t('transfer.nav_title')}
Title should be "Transfer Successful" (typo in Figma):
![image](https://github.com/synonymdev/bitkit/assets/8538369/f32b9192-d0ce-4b51-a3a6-6872e5da52da)

2024-05-23 11:33 UTC, pwltr commented on src/components/WalletOnboarding.tsx
> +	const handleTextLayout = (e: any): void => {
Please avoid `any` if possible: `(e: LayoutChangeEvent)`

2024-05-23 12:00 UTC, pwltr approved these changes

2024-05-23 12:05 UTC, merged

2024-05-28 14:53 UTC, catch-21 commented
Tested on v118
Mostly LGTM, although I did see the arrow behind text for Russian so we probably should hide to when text is wider: https://github.com/synonymdev/bitkit/issues/1895