fix(settings): update channel details
synonymdev/bitkit-react-native pull request #2022
Opened 2024-06-28 09:45 UTC by pwltr

### Description

- Add order information for CJIT channels
- Add fee information
- Add order expiry date for pending channels

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

![Simulator Screenshot - iPhone 15 - 2024-06-28 at 11 28 26](https://github.com/synonymdev/bitkit/assets/8538369/b0d62bd4-76b6-47c1-826d-a26bdf9973ef)
![Simulator Screenshot - iPhone 15 - 2024-06-28 at 11 30 01](https://github.com/synonymdev/bitkit/assets/8538369/6f003532-ea14-4c35-ae32-eb223446afbf)
![Simulator Screenshot - iPhone 15 - 2024-06-28 at 11 30 46](https://github.com/synonymdev/bitkit/assets/8538369/5798fbdc-0f46-4908-8ab1-3753fdc2660d)

2024-06-28 12:23 UTC, limpbrains requested changes

2024-06-28 12:23 UTC, limpbrains commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> -							testID={channel.is_channel_ready ? 'IsReadyYes' : 'IsReadyNo'}
IsReadyYes is checked in e2e tests

2024-06-28 13:25 UTC, pwltr commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> -							testID={channel.is_channel_ready ? 'IsReadyYes' : 'IsReadyNo'}
I think it's ok to remove the test since it's only checking if the row exists. For debugging `is_channel_ready` hasn't really been useful so far

2024-07-02 20:16 UTC, limpbrains commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> -							testID={channel.is_channel_ready ? 'IsReadyYes' : 'IsReadyNo'}
If we are removing is_channel_ready from tests, than we need to add is_usable check.

2024-07-09 09:07 UTC, pwltr commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> -							testID={channel.is_channel_ready ? 'IsReadyYes' : 'IsReadyNo'}
The test was only checking if the row exists, now it will exist always (without developer mode on) so I don't see the point of testing this. @limpbrains thoughts?

2024-07-09 09:35 UTC, limpbrains commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> -							testID={channel.is_channel_ready ? 'IsReadyYes' : 'IsReadyNo'}
Not just the row. Test was checking if LDK api return `channel.is_channel_ready`

2024-07-09 10:53 UTC, limpbrains approved these changes

2024-07-09 11:06 UTC, merged