Add `Swipe to hide` switch feature to settings menu
synonymdev/bitkit-react-native pull request #206
Opened 2022-07-23 01:51 UTC by MiguelMedeiros

## Description
Add `Swipe to hide` switch feature to settings menu

## Preview

https://user-images.githubusercontent.com/5798170/180585919-9499aac6-66c9-4c49-8fbc-5a4e3863de2d.mp4

2022-07-23 07:10 UTC, limpbrains requested changes
please add `swipeBalanceToHide: true` to `store/shapes/settings.ts`, I think it should be turned on by default.

2022-07-23 07:11 UTC, limpbrains commented on src/store/types/settings.ts
> -	showSuggestions: boolean;
I'm not sure if showSuggestions should be removed

2022-07-25 23:00 UTC, MiguelMedeiros commented on src/store/types/settings.ts
> -	showSuggestions: boolean;
I can make this change in another PR if you want, but we need to remove it, because It is duplicated: line 41 and 43.

2022-07-26 08:32 UTC, limpbrains approved these changes

2022-07-27 07:52 UTC, Jasonvdb approved these changes

2022-07-27 07:52 UTC, merged