fix: Lazy load bottom-sheets
synonymdev/bitkit-react-native pull request #2063
Opened 2024-07-15 10:47 UTC by limpbrains

### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Add any links to GitHub issues or Asana tasks that are relevant to this pull request.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-07-19 14:14 UTC, pwltr requested changes

2024-07-19 14:14 UTC, pwltr commented on src/navigation/root/RootNavigator.tsx
> -			<ForgotPIN />
This sheet is not showing up, looks like it is because it is hidden below PIN screen.

https://github.com/user-attachments/assets/f42d1d19-1167-4968-a9f6-483b1a43cd4c

2024-07-19 18:29 UTC, limpbrains commented on src/navigation/root/RootNavigator.tsx
> -			<ForgotPIN />
Thank you! Fixed it and added test for it

2024-07-22 11:36 UTC, pwltr approved these changes

2024-07-22 12:40 UTC, merged