fix: new lnurl
synonymdev/bitkit-react-native pull request #2076
Opened 2024-07-19 16:12 UTC by limpbrains

### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Add any links to GitHub issues or Asana tasks that are relevant to this pull request.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-07-22 16:30 UTC, pwltr requested changes

2024-07-22 16:30 UTC, pwltr commented on src/navigation/bottom-sheet/SendNavigation.tsx
> +
remove unused code

2024-07-22 16:30 UTC, pwltr commented on src/store/types/ui.ts
> +	// lnurlPay: { pParams: LNURLPayParams };
remove unused code

2024-07-22 16:30 UTC, pwltr commented on src/screens/Wallets/Send/ReviewAndSend.tsx
> +		// refreshWallet({ onchain: false, lightning: true }).then();
remove unused code

2024-07-22 16:39 UTC, pwltr requested changes

2024-07-22 16:39 UTC, pwltr commented on src/screens/Wallets/LNURLPay/Confirm.tsx
>  					title={t('lnurl_p_title')}
Title should be "Pay Bitcoin"

2024-07-23 10:22 UTC, limpbrains commented
fixed

2024-07-23 10:28 UTC, pwltr approved these changes

2024-07-23 10:28 UTC, merged

2024-07-24 16:09 UTC, catch-21 commented
@limpbrains Is it possible to retain the input comment on navigate back to change value and returning to swip to pay screen?

2024-07-26 14:49 UTC, catch-21 commented
Verified functionally working in v130 d8f96e7d6475d2eef04ae08f9d9dd2c8894a8218 sending to Wallet of Satoshi LN address.

2024-07-26 15:05 UTC, catch-21 commented
Raised https://github.com/synonymdev/bitkit/issues/2104