Add @synonymdev/react-native-ldk
synonymdev/bitkit-react-native pull request #211
Opened 2022-07-26 20:17 UTC by coreyphillips

This PR:
 - Adds `@synonymdev/react-native-ldk` dependency to `package.json`.
- Updates `yarn.lock` & `Podfile.lock` accordingly.
- Updates `README.md`.
- Adds `onReceive` param to `subscribeToHeader` method in `electrum.ts`.
- Adds "Lightning Node Info" button to Networks in Settings to display the LDK node ID for testing.
- Adds nodeId to lightning redux store.
- Updates `LightningNodeInfo.tsx` component to only display LDK node ID at this time.

The LDK Node ID can be found when in Regtest by navigating to `Settings->Networks->Lightning Node Info`.

2022-07-27 15:32 UTC, limpbrains requested changes

2022-07-27 15:32 UTC, limpbrains commented on src/utils/lightning/index.ts
> +};
What happens if keychain save fails?Looks like result of `setAccount()` is not checked anywhere, is it safe to ignore it?

2022-07-27 16:36 UTC, coreyphillips commented on src/utils/lightning/index.ts
> +};
Fixed [here](https://github.com/synonymdev/bitkit/pull/211/commits/78e5e75224959c5d83007e088f5f365e87fddd9f).

2022-07-27 17:18 UTC, limpbrains approved these changes

2022-07-28 12:01 UTC, Jasonvdb commented on src/utils/lightning/index.ts
> +			return err(nodeIdResponse.error.message);
I think if we push Result to it's own lib and share it everywhere then you won't have to double wrap these calls just to get the same result

2022-07-28 12:18 UTC, Jasonvdb commented
I'm not coming right, in regtest but LDK won't start because of this:
![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 14 16 24](https://user-images.githubusercontent.com/5300488/181503034-5f6a59eb-1dc8-4806-bbb4-b3dcfed47429.png)

2022-07-28 13:10 UTC, coreyphillips commented on src/utils/lightning/index.ts
> +			return err(nodeIdResponse.error.message);
Agreed. We have multiple projects using `Result` that could benefit from pulling from the same source.

The code referenced above was unnecessary in the `getNodeId` method and updated [here](https://github.com/synonymdev/bitkit/commit/906154d5402a3e641f8b21e8645bcf9a7238a149#diff-3898c176b9ed4ed723d2e4c5e7ba04e4d07ff33d39ddc16386e6f4cd41748b1cL271)

2022-07-28 13:12 UTC, coreyphillips commented
> I'm not coming right, in regtest but LDK won't start because of this: ![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 14 16 24](https://user-images.githubusercontent.com/5300488/181503034-5f6a59eb-1dc8-4806-bbb4-b3dcfed47429.png)

Fixed [here](https://github.com/synonymdev/bitkit/commit/906154d5402a3e641f8b21e8645bcf9a7238a149#diff-3898c176b9ed4ed723d2e4c5e7ba04e4d07ff33d39ddc16386e6f4cd41748b1cL178).

2022-07-29 14:13 UTC, Jasonvdb approved these changes

2022-07-29 14:14 UTC, merged