fix: show channel id
synonymdev/bitkit-react-native pull request #2132
Opened 2024-08-12 11:10 UTC by limpbrains

### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Add any links to GitHub issues or Asana tasks that are relevant to this pull request.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

2024-08-27 12:09 UTC, pwltr requested changes

2024-08-27 12:09 UTC, pwltr commented on src/utils/i18n/locales/en/lightning.json
> +		"string": "Channel id"
for consistency:

```suggestion
		"string": "Channel ID"
```

2024-08-27 12:30 UTC, pwltr approved these changes

2024-08-27 14:39 UTC, merged

2024-08-29 14:59 UTC, catch-21 commented
Verified in 2e3cf89d424d3f05fe5c2727ab02b3c9f318454a
Channel ID is from LDK
Channel point is the opening `txid:ix`