feat(transfer): transfer notifications
synonymdev/bitkit-react-native pull request #2135
Opened 2024-08-12 13:16 UTC by pwltr

### Description

Adds local notifications to let the user know to open the app when channel open is ready.

### Linked Issues/Tasks

Closes https://github.com/synonymdev/bitkit/issues/2094

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

2024-08-13 13:46 UTC, limpbrains requested changes

2024-08-13 13:46 UTC, limpbrains commented on src/store/utils/blocktank.ts
> +	await notifee.requestPermission();
what if I deny, will it throw and break refreshAllBlocktankOrders function ?

2024-08-13 13:46 UTC, limpbrains commented on src/store/utils/blocktank.ts
> +			body: 'Open Bitkit to complete your transfer',
localization needed

2024-08-13 13:46 UTC, limpbrains commented on package.json
> +    "@notifee/react-native": "^7.8.2",
better to lock the exact version

2024-08-13 21:47 UTC, pwltr commented on src/store/utils/blocktank.ts
> +			body: 'Open Bitkit to complete your transfer',
fixed

2024-08-13 21:48 UTC, pwltr commented on package.json
> +    "@notifee/react-native": "^7.8.2",
fixed

2024-08-13 21:49 UTC, pwltr commented on src/store/utils/blocktank.ts
> +	await notifee.requestPermission();
The promise will still resolve, but with `AuthorizationStatus.DENIED`. Code will still run but no notifications won't show.

2024-08-14 06:15 UTC, limpbrains approved these changes

2024-08-14 09:22 UTC, merged