feat(transfer): update transfer flow
synonymdev/bitkit-react-native pull request #2165
Opened 2024-08-26 15:56 UTC by pwltr

### Description

Update transfer UI from design updates v50

### Linked Issues/Tasks

Closes https://github.com/synonymdev/bitkit/issues/2081 https://github.com/synonymdev/bitkit/issues/2159

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [x] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

https://github.com/user-attachments/assets/2301bafd-6c65-49ba-8d08-82d4880f1042

https://github.com/user-attachments/assets/50b34f46-fc25-4eed-bff8-d11302be5552

2024-08-26 17:54 UTC, limpbrains commented on src/screens/Transfer/Availability.tsx
> -		navigation.goBack();
If I understand correctly, if case of goBack you remove screen from the history, when you do .navigate('Wallet') you add new screen old one remains, maybe it is better to use goBack, where possible, to reduce memory usage?

2024-08-26 18:01 UTC, limpbrains requested changes

2024-08-26 18:01 UTC, limpbrains commented on src/screens/Transfer/SavingsProgress.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
can you please add a comment why something is not added into dependecies array?

2024-08-26 18:01 UTC, limpbrains commented on src/screens/Transfer/SavingsProgress.tsx
> +		navigation.navigate('Wallet');
can we use goBack here?

2024-08-26 18:01 UTC, limpbrains commented on src/screens/Transfer/SpendingAdvanced.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
same

2024-08-26 18:01 UTC, limpbrains commented on src/screens/Transfer/SpendingAdvanced.tsx
> +			// 	: t('error_channel_setup_msg', { raw: message });
can this be removed?

2024-08-26 18:01 UTC, limpbrains commented on src/screens/Transfer/SpendingAdvanced.tsx
> +						sats={feeEstimate[`${clientBalance}-${lspBalance}`] || 0}
I think it should not be 0 by default. Better to show loading indicator, or dash, IDK

2024-08-26 20:03 UTC, pwltr commented on src/screens/Transfer/Availability.tsx
> -		navigation.goBack();
From what I know if a screen is already in the stack `navigate` will remove all the screens after it. `goBack` & `popToTop` didn't work in this case.

See: https://reactnavigation.org/docs/navigation-prop/#navigate

2024-08-26 20:04 UTC, pwltr commented on src/screens/Transfer/SavingsProgress.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
there is a comment above the `useEffect` "on mount". Should be clear? Or should we move the comment down?

2024-08-27 09:06 UTC, pwltr commented on src/screens/Transfer/SpendingAdvanced.tsx
> +			// 	: t('error_channel_setup_msg', { raw: message });
removed

2024-08-27 09:06 UTC, pwltr commented on src/screens/Transfer/SpendingAdvanced.tsx
> +						sats={feeEstimate[`${clientBalance}-${lspBalance}`] || 0}
done

2024-08-27 11:06 UTC, limpbrains commented on src/utils/lightning/index.ts
> -		const refreshRes = await refreshLdk({ selectedWallet, selectedNetwork });
❤️

2024-08-27 11:06 UTC, limpbrains approved these changes

2024-08-27 11:17 UTC, merged