fix: prevent wallet from beeing initalized twice
synonymdev/bitkit-react-native pull request #2210
Opened 2024-09-06 13:58 UTC by limpbrains

### Description

After new wallet creation `setupOnChainWallet` was called twice resulting in 2 instances of Beignet competing against each other. 
I'm fixing it by `walletExists: true` setter to be executed later, after the `createDefaultWallet` function is completed

### Linked Issues/Tasks

closes #2177

### Type of change

Bug fix

### Tests

No test

### QA Notes

- make sure RBF is enabled by default
- create new wallet, do not restart the app
- create 2-3 onchain transactions
- make sure you don't have any error messages

2024-09-06 16:03 UTC, pwltr requested changes

2024-09-06 16:03 UTC, pwltr commented on src/store/slices/wallet.ts
Do we need to split `createWallet` into 2 reducers? They are dispatched at the same time anyway:

```
dispatch(createWallet(response.value));
dispatch(setWalletExits());
```

2024-09-06 16:13 UTC, pwltr commented on src/store/slices/wallet.ts
In `createDefaultWallet`, `createWallet()` action is also dispatched but not `setWalletExits()`. Doesn't seem right.

2024-09-06 16:22 UTC, pwltr commented on src/store/slices/wallet.ts
Ok I see what's going on, it's confusing that it has to dispatch `createWallet()` twice.

2024-09-06 16:31 UTC, pwltr commented
Can confirm this seems to fix https://github.com/synonymdev/bitkit/issues/2177 and https://github.com/synonymdev/bitkit/issues/1934

2024-09-06 18:40 UTC, limpbrains commented on src/store/slices/wallet.ts
The whole thing is confusig and compicated

2024-09-07 10:48 UTC, pwltr approved these changes

2024-09-07 12:16 UTC, merged