chore: version bump and min ios bump
synonymdev/bitkit-react-native pull request #2251
Opened 2024-09-26 14:31 UTC by Jasonvdb

Fixes for Xcode 16

2024-09-27 10:52 UTC, pwltr requested changes

2024-09-27 10:52 UTC, pwltr commented on ios/Podfile
> +  # pod "OpenSSL-Universal", "= 1.1.1100"
If it's working please remove the comment altogether

2024-09-30 09:15 UTC, limpbrains commented
I've also accidently upgraded to xcode v16. 
This patched helped me

2024-09-30 09:15 UTC, limpbrains approved these changes

2024-10-02 03:15 UTC, limpbrains commented
I think we can merge this

2024-10-02 10:29 UTC, pwltr approved these changes

2024-10-02 10:29 UTC, merged