feat: reduce exchange rate services to Blocktank
synonymdev/bitkit-react-native pull request #226
Opened 2022-08-03 17:23 UTC by pwltr

Blocked by https://github.com/synonymdev/blocktank-fx-service/pull/3

### Changes:
- use [Blocktank FX exchange rate service API](https://github.com/synonymdev/blocktank-fx-service)
- remove exchange rate service selection
- add SettingsView search filter, enable for Currencies screen
- navigate the user back on choice

### Notes:
Currency symbols should appear once linked PR is merged 

### Screenshots:
<img src="https://user-images.githubusercontent.com/8538369/182670129-a9b035ce-6888-4fc4-90f4-c49053093f8f.png" width="200" />

2022-08-03 23:30 UTC, MiguelMedeiros approved these changes

2022-08-03 23:32 UTC, MiguelMedeiros commented
Tested ACK.
Also tested https://github.com/synonymdev/blocktank-fx-service/pull/3.

## Review Preview
https://user-images.githubusercontent.com/5798170/182730050-56bbdb63-e67f-4814-8170-bdd449fa4327.mp4

2022-08-04 14:18 UTC, limpbrains requested changes

2022-08-04 14:18 UTC, limpbrains commented on src/components/SearchInput.tsx
> +		<View style={style ? rootStyle : null}>
If no style provided to SearchInput, it should use `styles.root`, not null
Also I suggest we swap `StyleSheet.compose(style, styles.root)` to `StyleSheet.compose(styles.root, style)` so that base styles can be overwritten.

2022-08-04 14:18 UTC, limpbrains commented on src/utils/exchange-rate/index.ts
> +	const { tickers } = await response.json();
this func should return err(e) in case of the error

2022-08-04 16:37 UTC, pwltr commented on src/components/SearchInput.tsx
> +		<View style={style ? rootStyle : null}>
What do you think of this syntax: `<View style={[styles.root, style]}>`? It's less pure but I have noticed it being used in the codebase in a lot of places.

2022-08-04 16:59 UTC, limpbrains commented on src/components/SearchInput.tsx
> +		<View style={style ? rootStyle : null}>
I'm ok with it. Technically, style property also could be an array, but we are not writing component library, so that is fine

2022-08-05 07:30 UTC, limpbrains approved these changes

2022-08-05 07:49 UTC, merged