fix: Show Info notification for LNURL-withdraw success
synonymdev/bitkit-react-native pull request #2329
Opened 2024-11-04 14:49 UTC by limpbrains

### Description

Instead of Success show Info, because payment is still not received yet.
Also alter text

### Linked Issues/Tasks

closes #2326

### Type of change

Bug fix

### Tests

No test

### Screenshot / Video

### QA Notes

2024-11-05 10:13 UTC, pwltr requested changes

2024-11-05 10:13 UTC, pwltr commented on src/utils/lnurl.ts
>  		});
This toast shows at the same time as the one in the component no?

2024-11-07 12:46 UTC, limpbrains commented on src/utils/lnurl.ts
>  		});
You are right, removed

2024-11-07 12:48 UTC, pwltr approved these changes

2024-11-07 14:33 UTC, merged