feat: show warning if user tries to switch apps during LN receive
synonymdev/bitkit-react-native pull request #2346
Opened 2024-11-11 13:57 UTC by limpbrains

### Description

It works better on iOS because it has `inactive` state, where but is not yet fully background.

### Linked Issues/Tasks

#2319

### Type of change

New feature

### Tests

No test

### Screenshot / Video

https://github.com/user-attachments/assets/a305f632-60b5-4df7-b93b-030bb7c62acb

### QA Notes

- open receive with LN invoice shown
- try to put app into background

2024-11-18 17:29 UTC, pwltr requested changes

2024-11-18 17:29 UTC, pwltr commented on src/screens/Wallets/Receive/ReceiveQR.tsx
> +	useEffect(() => {
The toast also shows in the send flow:

https://github.com/user-attachments/assets/390c501d-17ab-47c3-85fd-911b7f6c48cb

Maybe this needs to be `useFocusEffect` ?

2024-11-19 11:39 UTC, limpbrains commented on src/screens/Wallets/Receive/ReceiveQR.tsx
> +	useEffect(() => {
fixed by checking `receiveNavigationIsOpen`

2024-11-19 16:38 UTC, pwltr approved these changes

2024-11-19 16:39 UTC, merged

2024-11-28 16:48 UTC, catch-21 commented
Tested on [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [3b9a833]
Works well on iPhone.
Using android, it shows the message once you return to the app. This is still useful even if it is noticed after an attempted spend.


https://github.com/user-attachments/assets/74e342e4-aebc-4a61-b091-45f1e315ed86