feat: Scanner UI
synonymdev/bitkit-react-native pull request #236
Opened 2022-08-07 17:05 UTC by pwltr

### Changes:
- add Scanner UI
- add read QR from file
- fix Electrum Server port TextField value
- fix some typos

### Notes:
~The UI currently doesn't have the blurred overlay~ Blur only on iOS and missing rounded corners as per design. Additional Annotations below.

### Screenshots:
<img src="https://user-images.githubusercontent.com/8538369/183302490-64068d8c-440b-4e4a-a7e5-3af2bfb303bc.png" width="200" />

2022-08-07 17:12 UTC, pwltr commented on src/utils/wallet/transactions.ts
> +		});
This was returning the wrong network in regtest mode since Regtest and Testnet p2pkh/p2sh addresses are valid for both networks (see `networks.ts`).  So now we're passing the network we actually want to validate against.

2022-08-07 17:14 UTC, pwltr commented on src/utils/scanner.ts
> +			await refreshWallet({ showNotification: false });
This was logging an error, the argument is not optional

2022-08-07 17:16 UTC, pwltr commented on src/screens/Scanner/index.tsx
> +					message: 'Failed to detect any address data',
Changed this to be more specific to the error

2022-08-07 18:26 UTC, limpbrains requested changes

2022-08-07 18:26 UTC, limpbrains commented on src/components/Camera.tsx
> +							'An error was encountered when loading the camera. Please ensure BitKit has permission to use this feature in your phone settings.',
User will not see this error, perhaps we need to show Notification here

2022-08-08 08:48 UTC, pwltr commented on src/components/Camera.tsx
> +							'An error was encountered when loading the camera. Please ensure BitKit has permission to use this feature in your phone settings.',
added a toast for this error with a shorter text so it's not cut off.

2022-08-10 06:43 UTC, limpbrains approved these changes

2022-08-10 09:08 UTC, Jasonvdb commented on src/screens/Scanner/index.tsx
> +					message: 'Failed to detect any address data',
Maybe confirm with Alder/John for the copy here. We will support scanning much more than just addresses.

2022-08-10 09:15 UTC, Jasonvdb requested changes

2022-08-10 09:15 UTC, Jasonvdb commented on src/utils/scanner.ts
> +			await refreshWallet({ showNotification: false });
Refreshing can take a few seconds so I think that's why this wasn't using it this way. This way the scanning needs to wait for the whole wallet to be refreshed. Rather `refreshWallet({ showNotification: false }).catch(e => {handleMe(e)})`

2022-08-10 13:29 UTC, coreyphillips commented on src/utils/wallet/transactions.ts
> +		});
Good catch. The only time we may want to distinguish between testnet and regtest, however, is when we're specifically using regtest. Otherwise, we may lose the ability to distinguish and switch between mainnet and testing states. Even then, in most situations we'll be using bech32 address where it won't be necessary. So I would suggest the following condition for regtest in the `parseOnChainPaymentRequest` method:
```
if (!selectedNetwork) {
  selectedNetwork = getSelectedNetwork();
}
let validateAddressResult = validateAddress({
	address: data,
	selectedNetwork: selectedNetwork === 'bitcoinRegtest' ? EAvailableNetworks[selectedNetwork] : undefined,
});
```

2022-08-10 14:47 UTC, pwltr commented on src/utils/wallet/transactions.ts
> +		});
sounds good [6456f54](https://github.com/synonymdev/bitkit/pull/236/commits/6456f54e478773d89fcf1de362985d6b7708ee37)

2022-08-10 14:48 UTC, pwltr commented on src/screens/Scanner/index.tsx
> +					message: 'Failed to detect any address data',
I see, address is definitely not generic enough here. I reverted it for now.

2022-08-10 14:49 UTC, pwltr commented on src/utils/scanner.ts
> +			await refreshWallet({ showNotification: false });
fixed [85eacce](https://github.com/synonymdev/bitkit/pull/236/commits/85eacce8146fea47f27a2569776d1a0c20580cee)

2022-08-11 05:46 UTC, Jasonvdb approved these changes

2022-08-11 05:47 UTC, merged