Lightning Channels
synonymdev/bitkit-react-native pull request #240
Opened 2022-08-10 00:46 UTC by coreyphillips

In this PR the `lightning` reducer has been updated to include `channels` and `openChannelIds`. `channels` will hold all pending, open and closed channel data for a given wallet and network. `openChannelIds` will hold an array (`string[]`) of available channel ids for channels that are currently open. This data has been passed to the previously created Lightning Channel components as seen in the attached video. This video demonstrates how the app will render pending, open and closed channels. Once a channel is established, we are able to create and pay invoices using the dev buttons on the Lightning Channel view. We are also able to close channels using the UI, but until we resolve the channel closure bug we are not able to recover any of the funds. The Channel Detail view will need additional tweaks in a future PR. Specifically, the removal of the "Fee" section and an update to the timestamp will be needed once we tie that into `react-native-ldk`. Until then, they are hardcoded.

To test this PR, a channel will need to be created from Polar using Synonym's regtest network.

https://user-images.githubusercontent.com/8532651/183784584-430b40da-fa69-47b4-b7c9-01c5de482a72.mp4

This PR:
- Adds `UPDATE_LIGHTNING_NODE_ID`, `UPDATE_LIGHTNING_CHANNELS` & `UPDATE_LIGHTNING_NODE_VERSION` actions to `store/actions/actions.ts`.
- Adds stringTypeItems to `shapes/wallet.ts`.
- Adds `IDefaultLightningShape`, `TLightningNodeVersion` & `TUseChannelBalance` to `types/lightning.ts`.
- Updates `ILightning` shape in `types/lightning.ts`.
- Updates `defaultLightningShape` in `shapes/lightning.ts`.
- Adds `defaultLightningStoreShape` to `shapes/lightning.ts`.
- Adds `UPDATE_LIGHTNING_NODE_ID`, `UPDATE_LIGHTNING_NODE_ID` & `UPDATE_LIGHTNING_NODE_VERSION` actions to `reducer/lightning.ts`.
- Re-orders the `startWalletServices` method in `startup/index.ts` to attempt and connect up with an Electrum server before creating a wallet.
- Creates several lightning hooks in `hooks/lightning.ts`.
- Sets `PersistGate` loading background color to black in `Root.tsx`.
- Creates `updateLightningNodeId`, `updateLightningChannels` & `updateLightningNodeVersion` actions in `store/actions/lightning.ts`.
- Updates default `walletName` param in `createWallet` method in `store/actions/wallet.ts`.
- Creates `refreshLdk`, `getNodeIdFromStorage`, `addPeers`, `getLightningChannels`, `getNodeVersion`, `closeChannel`, `createLightningInvoice` & `payLightningInvoice` methods in `utils/lightning.ts`.
- Adds optional `onchain` & `lightning` params to the `refreshWallet` method in `utils/wallet.ts`.
- Adds `refreshLdk` method to the `refreshWallet` method in `utils/wallet.ts`.
- Renames `Connections.tsx` component to `Channels.tsx`.
- Renames `ConnectionDetails.tsx` to `ChannelDetails.tsx`.
- Renames `CloseConnection.tsx` to `CloseChannel.tsx`.
- Passes channel data to the aforementioned channel components.
- Updates `LightningChannel.tsx` component and params.
- Added `loading` condition to `disabled` prop in `Button.tsx`.

2022-08-10 06:15 UTC, limpbrains approved these changes

2022-08-10 06:15 UTC, limpbrains commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> +	}, [channel.counterparty_node_id]);
React text has [ellipsizeMode](https://reactnative.dev/docs/text#ellipsizemode) with it you can truncate string in the middle, if needed, depending on container size. This may be more convenient, than do it by hand

2022-08-10 06:15 UTC, limpbrains commented on src/screens/Settings/Lightning/Channels.tsx
> +								key={`${channelId}${i}`}
Does it necessarily to add index to `key` property? I guess channelId is already has unique value

2022-08-10 14:00 UTC, coreyphillips commented on src/screens/Settings/Lightning/Channels.tsx
> +								key={`${channelId}${i}`}
Updated [here](https://github.com/synonymdev/bitkit/pull/240/commits/277e7877fc2b41ecf040382fd347426a8839871b).

2022-08-10 14:14 UTC, coreyphillips commented on src/screens/Settings/Lightning/ChannelDetails.tsx
> +	}, [channel.counterparty_node_id]);
Updated [here](https://github.com/synonymdev/bitkit/pull/240/commits/7161ed1091ddc93bd6aaf888af695cda11f3bbf5).

2022-08-11 07:59 UTC, Jasonvdb commented on src/hooks/lightning.ts
> +export const useLightningBalance = (
Think it's possible (one day not now) to move these hooks to react-native-ldk? They'll be useful for every RN project that uses the lib.

2022-08-11 08:28 UTC, Jasonvdb commented on src/store/actions/lightning.ts
> +export const updateLightning = ({
Can this function be removed now? Don't think it's used anywhere. Little worried it could be used later to accidentally break the state with its `any` payload.

2022-08-11 08:36 UTC, Jasonvdb commented on src/utils/lightning/index.ts
> +export const getNodeVersion = async (): Promise<
What's the reason for wrapping all these ldk functions again with the exact same method signature? 

If it's to keep ldk imports separate from the rest of the app you could change to just `export const getNodeVersion = ldk.version;` instead of redefining same params and return types.

2022-08-11 08:46 UTC, Jasonvdb commented
Not coming right with this branch when I use it to update an existing app. Missing default state somewhere maybe? Works fine if I delete the app and fresh install.

![Simulator Screen Shot - iPhone 13 - 2022-08-11 at 10 25 38](https://user-images.githubusercontent.com/5300488/184095944-bdc3c120-6e6d-4745-b9fc-03efe4cf46de.png)

2022-08-11 08:48 UTC, Jasonvdb commented
New style error I think coming from `src/screens/Settings/Lightning/ChannelDetails.tsx`

```
ERROR  Warning: Failed prop type: Invalid props.style key `numberOfLines` supplied to `Text`.
Bad object: {
  "numberOfLines": 1,
  "children": "Next",
  "fontFamily": "System",
  "fontWeight": "600",
  "backgroundColor": "transparent",
  "color": "#FFFFFF",
  "fontSize": 13
}

```

2022-08-11 12:14 UTC, coreyphillips commented on src/store/actions/lightning.ts
> +export const updateLightning = ({
Removed [here](https://github.com/synonymdev/bitkit/pull/240/commits/8fc14dac3b9e55dda2f201ac0ecd6ea7eb44ead1).

2022-08-11 12:23 UTC, coreyphillips commented
> Not coming right with this branch when I use it to update an existing app. Missing default state somewhere maybe? Works fine if I delete the app and fresh install.
> 
> ![Simulator Screen Shot - iPhone 13 - 2022-08-11 at 10 25 38](https://user-images.githubusercontent.com/5300488/184095944-bdc3c120-6e6d-4745-b9fc-03efe4cf46de.png)

This is expected behavior after any significant update to the redux state since it's trying to access a part of the structure that doesn't exist in older versions. In a future PR we will need to implement a redux state tree update when it detects changes to the structure so that this error doesn't occur.

2022-08-11 12:26 UTC, coreyphillips commented on src/utils/lightning/index.ts
> +export const getNodeVersion = async (): Promise<
Updated [here](https://github.com/synonymdev/bitkit/pull/240/commits/e475d1bff19d7fd3167e5a6da036b9ccae79cb6f).

2022-08-11 12:36 UTC, coreyphillips commented
> New style error I think coming from `src/screens/Settings/Lightning/ChannelDetails.tsx`
> 
> ```
> ERROR  Warning: Failed prop type: Invalid props.style key `numberOfLines` supplied to `Text`.
> Bad object: {
>   "numberOfLines": 1,
>   "children": "Next",
>   "fontFamily": "System",
>   "fontWeight": "600",
>   "backgroundColor": "transparent",
>   "color": "#FFFFFF",
>   "fontSize": 13
> }
> ```

Fixed [here](https://github.com/synonymdev/bitkit/pull/240/commits/a1abc0487effe1eb93998cd210a72f9cfbab08ef).

2022-08-11 20:02 UTC, Jasonvdb commented on src/utils/lightning/index.ts
> +export const getNodeVersion = async (): Promise<
There's also getLightningChannels, createLightningInvoice and payLightningInvoice that just wrap with no changes

2022-08-11 23:04 UTC, coreyphillips commented on src/utils/lightning/index.ts
> +export const getNodeVersion = async (): Promise<
Updated [here](https://github.com/synonymdev/bitkit/pull/240/commits/41e27461853526cf4b45c2d6e0210c63bb673af1). I excluded  `payLightningInvoice` since additional logic will be needed with that method.

2022-08-12 08:03 UTC, Jasonvdb approved these changes

2022-08-12 11:03 UTC, pwltr requested changes
"Add Connection" screen is throwing an error, the example(?) LNBIG connection is missing the `channelId` now I think.

https://user-images.githubusercontent.com/8538369/184341031-244fb314-bec3-4809-8db1-9bdfdb8d09c5.mp4

2022-08-12 13:16 UTC, coreyphillips commented
> "Add Connection" screen is throwing an error, the example(?) LNBIG connection is missing the `channelId` now I think.
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2022-08-12.at.12.50.50.mp4

Unable to reproduce, but updated the `useLightningChannelBalance` hook [here](https://github.com/synonymdev/bitkit/pull/240/commits/61ac4e4f6eb0528975d32d836b05e84fa8b06700).

2022-08-12 13:42 UTC, pwltr approved these changes

2022-08-12 13:43 UTC, merged