feat: splash screen
synonymdev/bitkit-react-native pull request #242
Opened 2022-08-10 06:57 UTC by limpbrains

https://user-images.githubusercontent.com/155891/183834952-f72242a5-aefe-4d22-a87e-c3bc53cf57a7.mp4

I wanted to do this without adding extra dependencies, so I've followed [this tutorial](https://medium.com/@rfontes/splash-screens-on-react-native-without-libs-b487d08264ee). For iOS it is quite straightforward, but for android it requires additional code to hide loading screen.

in dev it still shows white screen when react is loading, should be fine in prod builds

2022-08-10 16:33 UTC, pwltr commented
On Android there is a bit of black space in the top left corner.

https://user-images.githubusercontent.com/8538369/183963647-bc0b7fc6-99bc-4e45-8021-c87811ea28d6.mov

I wasn't able to get the splash screen on iOS (probably be a cache issue).

2022-08-11 00:58 UTC, MiguelMedeiros commented
Yes, got the same here. 
Blank space on the left, also scrolling a little bit.

https://user-images.githubusercontent.com/5798170/184047477-a080ab81-e315-4bf6-8b19-afacd9211cfd.mp4

2022-08-11 05:53 UTC, Jasonvdb requested changes

2022-08-11 05:53 UTC, Jasonvdb commented on android/app/src/main/res/drawable/launch_screen.xml
> +        <bitmap android:src="@drawable/splash" android:gravity="center|clip_horizontal" />
I think if you change `clip_horizontal` to `fill_horizontal` that might do the trick. Or one of [these](https://developer.android.com/reference/android/widget/LinearLayout.LayoutParams.html#attr_android:layout_gravity).

2022-08-11 11:03 UTC, limpbrains commented
Do you css is hard? try center-crop image on Android

2022-08-12 06:57 UTC, Jasonvdb approved these changes

2022-08-12 06:57 UTC, merged