feat: unified receive flow
synonymdev/bitkit-react-native pull request #275
Opened 2022-08-22 16:10 UTC by pwltr

### Changes
- update receive flow UI
- add "receive" reducer
- update "metadata" reducer
- trigger tag matching logic on wallet sync
- add some helpers (reset metadata & a hook)
- fixed `wallet` type and resulting errors & related bugs

### Notes
- outstanding task wrt. onchain address reuse
- tags only work for onchain txs right now, will need to revisit when Lightning UI is implemented more
- some code duplication that could be improved (NumberPad, Tags screen)
- there is a weird issue with NumberPad popping up after reopening the app but I believe it's a general problem that I'll look at seperately

2022-08-24 09:47 UTC, pwltr commented on src/store/actions/wallet.ts
> +							});
@coreyphillips There was a bug here: `foundOutput` is an array and not a single `IOutput`. Can you confirm that this fix is what this was intending to do?

2022-08-24 12:06 UTC, limpbrains requested changes

2022-08-24 12:06 UTC, limpbrains commented on src/hooks/helpers.ts
> +export const useEffectOnlyOnce = (callback, dependencies, condition) => {
Looks like `useEffectOnlyOnce` not used anywhere

2022-08-24 12:06 UTC, limpbrains commented on src/navigation/bottom-sheet/ReceiveNavigation.tsx
> +	const snapPoints = useMemo(() => ['87%'], []);
Why switch to percentage?

2022-08-24 12:06 UTC, limpbrains commented on src/screens/Wallets/Receive/index.tsx
> +	}
receiveAddress generated in useMemo, it runs synchronously, so you don't need to wait for it.
But `receiveAddress` can be undefined if `getReceiveAddress` or `getReceiveNewAddress` fails. 
Maybe show error in this case? I'm not sure

2022-08-24 12:32 UTC, coreyphillips commented on src/store/actions/wallet.ts
> +							});
Good catch! However, we should either remove the` if (foundOutput.index) {` condition on line 748 or if we want to be really safe, replace it with `if (foundOutput?.address) {`

2022-08-24 12:42 UTC, pwltr commented on src/store/actions/wallet.ts
> +							});
We need to make sure `foundOutput.index` exists before using it as an index for the array as it is an optional field on `IOutput`. What should we do if the output doesn't have the index?

2022-08-24 12:44 UTC, pwltr commented on src/hooks/helpers.ts
> +export const useEffectOnlyOnce = (callback, dependencies, condition) => {
This was in anticipation of the `getNewAddress` method which is not yet implemented. I'm assuming it will be asynchronous as we might have to generate new addresses on demand. Will remove this if mistaken.

2022-08-24 12:45 UTC, pwltr commented on src/screens/Wallets/Receive/index.tsx
> +	}
This will also change with the `getNewAddress` function. Depending on if it's async or not I will change this.

2022-08-24 12:46 UTC, pwltr commented on src/navigation/bottom-sheet/ReceiveNavigation.tsx
> +	const snapPoints = useMemo(() => ['87%'], []);
No reason, but the sheet is larger now. Should we switch back to pixels?

2022-08-24 12:56 UTC, coreyphillips commented on src/store/actions/wallet.ts
> +							});
The index may be `0` so we'll just need to ensure it's not failing that condition. So something like, `if (foundOutput?.index >= 0)`

2022-08-24 13:00 UTC, coreyphillips commented on src/hooks/helpers.ts
> +export const useEffectOnlyOnce = (callback, dependencies, condition) => {
Leave it for now. If I end up not using it when implementing `getNewAddress` we can consider tossing it.

2022-08-24 13:05 UTC, limpbrains commented on src/navigation/bottom-sheet/ReceiveNavigation.tsx
> +	const snapPoints = useMemo(() => ['87%'], []);
I think yes, because of small screen devices. We don't test them well.

2022-08-24 16:23 UTC, pwltr commented on src/navigation/bottom-sheet/ReceiveNavigation.tsx
> +	const snapPoints = useMemo(() => ['87%'], []);
update here: https://github.com/synonymdev/bitkit/pull/275/commits/7eeeabdb0f210e97dd79478fff0d4cc6dfeeb839

Using screen height minus top SafeAreaInset + height of HeaderBar. I think this way it should look pretty much the same on all devices (untested). Seems ok?

2022-08-24 16:33 UTC, pwltr commented on src/store/actions/wallet.ts
> +							});
fixed here https://github.com/synonymdev/bitkit/pull/275/commits/f3bf95b745974f374f95eccf50ceee165a9302bc in a way that makes TS happy. Still seems off to me, if multiple `foundOutputs` are missing the index they are going to overwrite each other on `outputs[0]`. Not really sure what this code does tbh otherwise I would test.

2022-08-24 18:52 UTC, coreyphillips commented on src/store/actions/wallet.ts
> +							});
This code mostly applies when we add or specify more than one output beyond the changeAddress when sending a transaction. Because we currently only allow for sending to one address, it is unlikely that this change will impact the current transaction creation process. However, this change does affect the transaction creation flow.

With that said, this change is beyond the scope of this PR. Lets revert this change back to the original, create an issue for the bug you discovered here and I'll create a separate PR to test and review the needed changes.

2022-08-25 07:03 UTC, limpbrains commented on src/navigation/bottom-sheet/ReceiveNavigation.tsx
> +	const snapPoints = useMemo(() => ['87%'], []);
Still needs some adjustments for Android. probably limit qrcode size, when screen is wide 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/155891/186596373-8991454d-902b-483e-9233-52f870620097.png">

this is how 87% looks like:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/155891/186597465-82827f5d-ecca-4c08-b773-c3bb077626d6.png">

PS also eslint error

2022-08-25 08:56 UTC, pwltr commented on src/navigation/bottom-sheet/ReceiveNavigation.tsx
> +	const snapPoints = useMemo(() => ['87%'], []);
Added a `maxHeight` for the QR https://github.com/synonymdev/bitkit/pull/275/commits/ae5eb424a1f432c755a4ed74cabc2e30bd47c111

![Screenshot_1661416386](https://user-images.githubusercontent.com/8538369/186621277-fdaee5e6-537d-4928-8945-4963e55b2344.png)

2022-08-25 08:56 UTC, pwltr commented on src/store/actions/wallet.ts
> +							});
reverted https://github.com/synonymdev/bitkit/pull/275/commits/f73cde5e82ee79d87bfd29ed69a4f70812d118ac

2022-08-25 10:24 UTC, limpbrains approved these changes

2022-08-25 13:18 UTC, coreyphillips approved these changes

2022-08-25 13:18 UTC, merged