feat(wallet): Generate New Addresses
synonymdev/bitkit-react-native pull request #286
Opened 2022-08-26 03:33 UTC by coreyphillips

This PR:
- Adds and implements the `generateNewReceiveAddress` method when creating Bitcoin invoices.
- Adds `lastUsedAddressIndex` & `lastUsedChangeAddressIndex` to wallet reducer to track the gap limit as new addresses are generated.
  - The gap limit is only enforced when attempting to generate new addresses and is not yet implemented when scanning addresses for balances.

2022-08-29 08:21 UTC, pwltr requested changes

2022-08-29 08:21 UTC, pwltr commented on src/screens/Wallets/Receive/index.tsx
> +	}, [amount, message, selectedNetwork, selectedWallet]);
`getLightningInvoice()` is called twice here on mount, once in `setInvoiceDetails()`. Also the `.then()` doesn't do anything here and should be omitted.

2022-08-29 08:21 UTC, pwltr commented on src/utils/wallet/index.ts
> +		const addressIndex = currentWallet.addressIndex[addressType].index;
This throws an error for me, leading to no new address being generated: `currentWallet.addressIndex[addressType]` is undefined.

2022-08-29 16:05 UTC, coreyphillips commented on src/screens/Wallets/Receive/index.tsx
> +	}, [amount, message, selectedNetwork, selectedWallet]);
Fixed [here](https://github.com/synonymdev/bitkit/pull/286/commits/d0471e287bf139c0d9502c90790aa4f835fa6234).

The `.then()` is to acknowledge that a Promise is being returned and to remove the warning from certain IDE's.
<img width="530" alt="Screen Shot 2022-08-29 at 11 59 39 AM" src="https://user-images.githubusercontent.com/8532651/187244803-3d753941-8e30-4364-a2cd-d207c424fd62.png">

2022-08-29 16:06 UTC, coreyphillips commented on src/utils/wallet/index.ts
> +		const addressIndex = currentWallet.addressIndex[addressType].index;
Nice. Fixed [here](https://github.com/synonymdev/bitkit/pull/286/commits/5d4fa5fafcd1f82689e8696f82a11466ae8a1a48).

2022-08-29 18:38 UTC, pwltr commented on src/screens/Wallets/Receive/index.tsx
> +	}, [amount, message, selectedNetwork, selectedWallet]);
Interesting, never seen this but seems useful. Shame that ESLint doesn't have a rule for this.

2022-08-30 11:41 UTC, pwltr approved these changes

2022-08-30 13:56 UTC, merged