fix(wallet): improve handling of offline exchange rate API
synonymdev/bitkit-react-native pull request #324
Opened 2022-09-05 14:56 UTC by pwltr

Task: https://app.asana.com/0/1189635884316057/1202838628848168/f

### Changes
- show a toast when exchange rate API is down
- split up `getDisplayValues` into Bitcoin and fiat so we can handle errors & fallbacks separately
- update placeholders for fiat value if the exchange rate is not known
- fix some lint errors

### Notes
Easiest way to test is to change the e.g. the port in `exchange-rate/index.ts`. 

### Preview
Toast:
![Simulator Screen Shot - iPhone 13 - 2022-09-06 at 10 50 27](https://user-images.githubusercontent.com/8538369/188599648-f3e7898e-23cd-410f-b5d8-a5c1f613073c.png)

Receiving payment when API is down and no previous rate is known:
![Simulator Screen Shot - iPhone 13 - 2022-09-05 at 15 27 44](https://user-images.githubusercontent.com/8538369/188475890-822772ba-2dc3-45f2-8192-e40005abe087.png)

Fallback UI when API is down and no previous rate is known:
![Simulator Screen Shot - iPhone 13 - 2022-09-05 at 15 28 08](https://user-images.githubusercontent.com/8538369/188475969-5e45fe66-02f4-49fb-8cac-118be9d49d04.png)

If sats amount is zero we don't need the placeholder (-):

https://user-images.githubusercontent.com/8538369/188476141-68543a08-b1aa-4999-810d-52807f6c0cbf.mp4

Typing here doesn't do anything now:
![Simulator Screen Shot - iPhone 13 - 2022-09-05 at 16 15 48](https://user-images.githubusercontent.com/8538369/188476215-8d20ce2d-b6b7-4b70-8c41-32e4b66b0dae.png)

Can still transact normally:
![Simulator Screen Shot - iPhone 13 - 2022-09-05 at 16 17 41](https://user-images.githubusercontent.com/8538369/188476330-2bf96404-2a5a-402e-828b-54f12eaa1cdb.png)

2022-09-06 06:55 UTC, limpbrains requested changes
Awesome job!
Do you keep last successful update time? It would be nice to show it in error popup. Something like: "Using rates from 12/12/2009"
Can you please write a unit test for `getDisplayValues` with unknown rate ?

2022-09-06 12:14 UTC, limpbrains approved these changes

2022-09-07 15:09 UTC, coreyphillips commented on src/utils/exchange-rate/index.ts
> +				message: `Could not get exchange rate, using price from\n${date}`,
Replace comma with period so it reads as follows:
`Could not get exchange rate. Using price from\n${date}`

2022-09-07 15:11 UTC, coreyphillips approved these changes

2022-09-07 15:31 UTC, merged