feat(profile): upgrade playground to next version of the SDK
synonymdev/bitkit-react-native pull request #327
Opened 2022-09-05 17:41 UTC by Nuhvi

Switches to the latest version of the SDK, and add support for the seeder.

Added support for both p2wpkh and zero sats ln invoice... but the playground probably creates manner and non p2wpkh addresses, so it is never valid.

However, feel free to pay for this slashtag, it should always be resolvable (from seeder):
`slash:4c71h4rmdpddqroj7freshg34h59wqytde9nm654geide7yt3jqo`

https://user-images.githubusercontent.com/40009100/190394506-83a2be74-1d97-416e-8857-cd61b94da10f.mov

2022-09-15 12:38 UTC, limpbrains requested changes

2022-09-15 12:38 UTC, limpbrains commented on src/components/ContactsList.tsx
>  			.sort((a, b) => (a.name > b.name ? 1 : -1))
double sort

2022-09-15 12:38 UTC, limpbrains commented on src/screens/Profile/ProfileEdit.tsx
> +							placeholder="For example �Website�"
this need to be reverted. On my iOS simulator it can't render these chars

2022-09-16 06:12 UTC, limpbrains approved these changes

2022-09-16 09:17 UTC, Jasonvdb approved these changes

2022-09-16 09:17 UTC, merged

2022-09-16 10:09 UTC, pwltr commented
This one is a bit faulty. An unhandled promise rejection is making my simulators crash. Something in the `<SlashtagsProvider />` component. Looking into it.

2022-09-16 10:15 UTC, limpbrains commented
> This one is a bit faulty. An unhandled promise rejection is making my simulators crash. Something in the `<SlashtagsProvider />` component. Looking into it.

wiping wallet data solved this issue for me