feat: slashpay
synonymdev/bitkit-react-native pull request #367
Opened 2022-09-13 11:23 UTC by limpbrains

- allows you to choose contact on send
- assign/detach transactions to contact
- you can choose contact and then tap on pay button

Currently it uses same address for all contacts, this will be fixed in next PRs

https://user-images.githubusercontent.com/155891/189889263-b49ca300-2743-4d0c-91bd-e48e6c3b8e1e.mp4

closes #367

2022-09-13 11:25 UTC, limpbrains commented on src/screens/Wallets/SendOnChainTransaction/Contacts.tsx
> +
This needs to be changed @Nazeh

2022-09-13 11:25 UTC, limpbrains commented on src/screens/Contacts/Contact.tsx
> +								});
This needs to be changed @Nazeh

2022-09-13 11:42 UTC, Nuhvi commented on src/screens/Contacts/Contact.tsx
> +								});
Noted

2022-09-14 10:47 UTC, pwltr requested changes

2022-09-14 10:47 UTC, pwltr commented on src/screens/Activity/ActivityDetail.tsx
> +								) : (
use `<UserMinusIcon />` here

2022-09-14 10:47 UTC, pwltr commented on src/store/types/metadata.ts
> +	slashTagsUrls: {};
Type should be:

```suggestion
	slashTagsUrls: { [txId: string]: string };
```

2022-09-14 10:47 UTC, pwltr commented on src/screens/Wallets/Receive/ReceiveDetails.tsx
>  				<View style={buttonContainer}>
Why remove the image here?

2022-09-14 14:03 UTC, limpbrains commented on src/screens/Wallets/Receive/ReceiveDetails.tsx
>  				<View style={buttonContainer}>
Because it looks ugly on Android and I don't know how to fix it nicely.
Image was removed from Send, I think it should be also removed here as well
<img width="397" alt="изображение" src="https://user-images.githubusercontent.com/155891/190175726-0239ddfc-63da-49a5-a4e5-b406d57cb3d4.png">

2022-09-14 14:32 UTC, pwltr commented on src/screens/Wallets/Receive/ReceiveDetails.tsx
>  				<View style={buttonContainer}>
The design said to just hide the image when user is editing note but I agree it should be consistent with Send flow.

2022-09-14 15:00 UTC, limpbrains commented on src/store/types/metadata.ts
> +	slashTagsUrls: {};
Yeah, I've tried that. But I have TS error because of `removeKeysFromObject`
I don't know how to fix it, please help :)

```
src/store/reducers/metadata.ts:121:5 - error TS2322: Type 'object' is not assignable to type '{ [txId: string]: string; }'.
  Index signature for type 'string' is missing in type '{}'.

121     slashTagsUrls,
        ~~~~~~~~~~~~~

  src/store/types/metadata.ts:5:2
    5  slashTagsUrls: { [txId: string]: string };
       ~~~~~~~~~~~~~
    The expected type comes from property 'slashTagsUrls' which is declared here on type 'IMetadata'


Found 1 error in src/store/reducers/metadata.ts:121
```

2022-09-14 15:12 UTC, limpbrains commented on src/screens/Activity/ActivityDetail.tsx
> +								) : (
Fixed, thanks!

2022-09-14 15:39 UTC, pwltr commented on src/store/types/metadata.ts
> +	slashTagsUrls: {};
return type for `removeKeysFromObject` was wrong

2022-09-14 15:39 UTC, pwltr approved these changes

2022-09-14 15:42 UTC, merged