feat(lightning): Pull Blocktank Node Info From API
synonymdev/bitkit-react-native pull request #411
Opened 2022-09-23 15:24 UTC by coreyphillips

This PR:
- We no longer rely on the hardcoded lightning peer list when adding peers. We now retrieve and save the current Blocktank peer info from Blocktank's `getInfo` method.
- Adds `info` to the `blocktank` reducer.
- Adds a `refreshBlocktankInfo` method that will refresh/update Blocktank's node info on app start.

2022-09-23 20:48 UTC, Jasonvdb approved these changes

2022-09-24 18:17 UTC, pwltr requested changes

2022-09-24 18:17 UTC, pwltr commented on src/store/actions/blocktank.ts
> +	const infoResponse = await getBlocktankInfo();
Should handle errors here since this is a network request.

2022-09-24 20:22 UTC, coreyphillips commented on src/store/actions/blocktank.ts
> +	const infoResponse = await getBlocktankInfo();
This error will need to be handled by `@synonymdev/blocktank-client` and respond with `Promise<Result<IGetInfoResponse>>`. Until then, I've added a condition to check for a valid response prior to updating [here](https://github.com/synonymdev/bitkit/pull/411/commits/aa22d02f703499cb96c34d0bf3f16098afbbfec2).

2022-09-26 10:52 UTC, pwltr approved these changes

2022-09-26 10:53 UTC, merged