fix(lightning): Channel Purchase Improvements
synonymdev/bitkit-react-native pull request #412
Opened 2022-09-23 20:13 UTC by coreyphillips

This PR:
- Adds on-chain transaction fees to the channel purchase cost in the `QuickConfirm` & `CustomConfirm` components.
- Updates the max spend/receive calculations in the `CustomSetup` and `QuickSetup` channel purchase flows.
- Fixes slider divide by zero bug.
- Updates lightning todo logic.
- Updated `ADD_TODO` reducer to add new todos to the front.

2022-09-24 18:30 UTC, pwltr requested changes

2022-09-24 18:30 UTC, pwltr commented on src/utils/todos/index.ts
> +	const lightningIsDismissed = 'lightning' in dismissedTodos;
I don't believe the `in` operator can be used like this on arrays.

```suggestion
	const lightningIsDismissed = dismissedTodos.includes('lightning');
```

2022-09-24 20:15 UTC, coreyphillips commented on src/utils/todos/index.ts
> +	const lightningIsDismissed = 'lightning' in dismissedTodos;
Updated [here](https://github.com/synonymdev/bitkit/pull/412/commits/5f0094d296b49e0489545d9b795243ece3742ae0). It appears several of the todos were using the faulty logic so I updated them accordingly. We may need to consider adding additional data to these dismissed todos in the future.

2022-09-24 20:22 UTC, pwltr approved these changes

2022-09-25 10:25 UTC, limpbrains approved these changes

2022-09-25 10:25 UTC, merged