feat: rebalance flow
synonymdev/bitkit-react-native pull request #424
Opened 2022-09-28 16:07 UTC by limpbrains

All data is currently fake. It is just to add dashed line to PieChart component and a place for a future rebalance logic

https://user-images.githubusercontent.com/155891/192829949-920c1937-fc77-4b4e-8a15-29e127a4368f.mp4

2022-09-28 16:20 UTC, pwltr requested changes

2022-09-28 16:20 UTC, pwltr commented on src/screens/Lightning/RebalanceResult.tsx
> +			<NavigationHeader title="Rebalance Succesful" displayBackButton={false} />
small typo:

```suggestion
			<NavigationHeader title="Rebalance Successful" displayBackButton={false} />
```

2022-09-28 16:20 UTC, pwltr commented on src/screens/Lightning/RebalanceResult.tsx
> +						You have succesfully rebalanced your savings and instant spending
```suggestion
						You have successfully rebalanced your savings and instant spending
```

2022-09-28 17:10 UTC, pwltr commented on src/screens/Wallets/WalletsDetail/BitcoinBreakdown.tsx
>  					}}>
Do we maybe need to check here if the user has setup Lightning yet, and depending on it navigate to either `Introduction` or `RebalanceSetup`?

2022-09-29 10:38 UTC, limpbrains commented on src/screens/Wallets/WalletsDetail/BitcoinBreakdown.tsx
>  					}}>
Nice catch! I added same check as in lightning todo card

2022-09-29 12:09 UTC, pwltr approved these changes

2022-09-29 12:14 UTC, merged