Remote backups and restoring
synonymdev/bitkit-react-native pull request #561
Opened 2022-10-21 18:27 UTC by Jasonvdb

- Automated LDK state backups
- Right now it's just restoring the LDK state as is but I would like it to auto sweep all funds from channels for safety. Will update react-native-ldk with that settings.
- There's a bit of a flash between the 2 restoring screens I need to fix still. The reason for 2 screens is because the first one restores the seed and the 2nd one is inside the slashtags provider which is needed to restore remote data. I'd like to circle back and still rethink this later as it seems a little too messy.
- Fixes ldk wipe directory and resets ldk before wiping else content is just written back right away by the ldk process.
- Replaced `funding_txo` with corrected `funding_txid` field

2022-10-21 19:34 UTC, pwltr requested changes

2022-10-21 19:34 UTC, pwltr commented on src/screens/Onboarding/RestoreFromSeed.tsx
> +			Alert.alert(res.error.message);
Should use the styled toast to show user facing error messages:

```suggestion
			showErrorNotification({
				title: 'Error Restoring Wallet',
				message: res.error.message,
			});
```

2022-10-22 14:20 UTC, Jasonvdb commented on src/screens/Onboarding/RestoreFromSeed.tsx
> +			Alert.alert(res.error.message);
Thanks done!

2022-10-23 15:38 UTC, coreyphillips approved these changes

2022-10-23 16:37 UTC, pwltr approved these changes

2022-10-23 17:02 UTC, merged