fix(wallet): Limit Address Scanning
synonymdev/bitkit-react-native pull request #645
Opened 2022-11-01 18:17 UTC by coreyphillips

This PR:
- Adds `scanAllAddresses` param to several methods.
- Setting `scanAllAddresses` to `false` will force adherence to the set gap limit (20 at the moment) in order to limit scanning all addresses every time the user refreshes.
- Adds condition to `QuickConfirm` & `CustomConfirm` components to enable lightning testing on iOS devices for `regtest` and `testnet` networks.

2022-11-01 19:48 UTC, limpbrains commented on src/utils/wallet/electrum.ts
> +						}),
Sorry, can you please explain the logic here.
Let's say we have 100 addresses. AddressIndex = 99, Looks like this condition will always be true.

2022-11-01 20:07 UTC, coreyphillips commented on src/utils/wallet/electrum.ts
> +						}),
Sure thing! Here's an example:
```
const addresses = [1,2,3,4,5,6,7,8,9,10]; // This represents an array of address indexes.
const addressIndex = 4; // This is our current index.
const gapLimit = 2;

const addressesToScan = addresses.filter((a) => Math.abs(a - addressIndex) <= gapLimit);

console.log(addressesToScan);
// [2, 3, 4, 5, 6]
```

Grabbing the absolute value of an address index minus the current index allows us to retrieve the specified gap limit both behind and in front of the current index.

2022-11-01 20:12 UTC, limpbrains commented on src/utils/wallet/electrum.ts
> +						}),
What if user receives transaction to address at index 1 ? He will not be able to get it on pull-to-refresh on main screen?

2022-11-01 20:17 UTC, coreyphillips commented on src/utils/wallet/electrum.ts
> +						}),
Two things on that:
- When the app starts up it will scan all addresses [here](https://github.com/synonymdev/bitkit/blob/cc7ce8cda3bc6c14a90dc142930618a8d3b22ecc/src/utils/startup/index.ts#L152). Subsequent refreshes after startup will adhere to the gap limit standard of 20.
- The app will not generate receiving addresses beyond the specified gap limit from the receive view.

2022-11-01 20:19 UTC, coreyphillips commented on src/utils/wallet/electrum.ts
> +						}),
Scratch that. I need to replace `restore` with `true`. Getting a quick fix in now.

2022-11-01 20:23 UTC, coreyphillips commented on src/utils/wallet/electrum.ts
> +						}),
Like other wallets, we may need to add a rescan button to the Settings menu.

2022-11-02 07:41 UTC, pwltr requested changes

2022-11-02 07:41 UTC, pwltr commented on src/utils/startup/index.ts
> +						scanAllAddresses: restore,
This only scans all addresses when restoring a wallet, above you said it should run on every app start

2022-11-02 10:31 UTC, limpbrains commented
I think pull-to-refresh on main screen should act like a Rescan everything button

2022-11-02 11:16 UTC, coreyphillips commented on src/utils/startup/index.ts
> +						scanAllAddresses: restore,
I corrected my comment. Scanning all addresses on every start can get demanding when the app starts to manage hundreds of addresses. We need something more controlled and manageable for a mobile wallet like John suggested (Rotating a subset of old addresses outside of the scanning threshold on every start and/ or refresh).

2022-11-02 11:23 UTC, coreyphillips commented
> I think pull-to-refresh on main screen should act like a Rescan everything button

I think this is a good solution. This would make pull to refresh behave how the user expects it and keeps the default demand on scanning performant by using the gap limit as the basis for setting the scanning threshold.

2022-11-02 11:42 UTC, pwltr approved these changes

2022-11-02 19:56 UTC, limpbrains approved these changes

2022-11-03 11:10 UTC, merged