Feat/delete auth widget
synonymdev/bitkit-react-native pull request #650
Opened 2022-11-03 09:53 UTC by Nazeh

closes #648

2022-11-03 15:30 UTC, limpbrains approved these changes

2022-11-03 15:37 UTC, pwltr requested changes

2022-11-03 15:37 UTC, pwltr commented on src/components/HeadlinesWidget.tsx
> +				title={`Delete ${name} widget?`}
`name` here should always be just the widget name imo

2022-11-04 08:51 UTC, pwltr approved these changes

2022-11-04 11:11 UTC, merged