Feat: add bip39 passphrase support
synonymdev/bitkit-react-native pull request #711
Opened 2022-11-17 12:26 UTC by limpbrains

- create new wallet + passphrase
- recover wallet + passphrase
- backup flow with passphrase
- react-native-swiper replaced with react-native-reanimated-carousel

Also I've renamed `password` to `bip39Passphrase` in a few places to make code more consistent

2022-11-17 15:51 UTC, coreyphillips commented on src/utils/startup/index.ts
If we have a mnemonic phrase and no wallet exists, should we also attempt to grab the bip39Passphrase, if one exists, and pass that to createWallet as well?

2022-11-17 16:00 UTC, limpbrains commented on src/utils/startup/index.ts
yes, we should! fixed in #c2a1a0c8

2022-11-17 18:05 UTC, coreyphillips commented on src/screens/Onboarding/Passphrase.tsx
> +						<TextInput
We should ensure the following `TextInput` params are set to `false` when setting the passphrase:
- autoCapitalize
- autoComplete
- autoCorrect

2022-11-17 21:51 UTC, limpbrains commented on src/screens/Onboarding/Passphrase.tsx
> +						<TextInput
Done

2022-11-17 22:52 UTC, pwltr requested changes

2022-11-17 22:52 UTC, pwltr commented on src/screens/Onboarding/Slideshow.tsx
> +					</AnimatedView>
On small screens this is too far on the bottom:

![image](https://user-images.githubusercontent.com/8538369/202570345-02f4fbad-b3c8-4a41-8df0-760cb6adbb20.png)

2022-11-17 22:52 UTC, pwltr commented on src/screens/Onboarding/Passphrase.tsx
> +						/>
missing placeholder "Passphrase"

2022-11-17 22:52 UTC, pwltr commented on src/screens/Onboarding/Passphrase.tsx
> +							Secure with <Display color="purple">Passphrase</Display>
```suggestion
							Secure with <Display color="brand">Passphrase</Display>
```

2022-11-18 10:36 UTC, pwltr requested changes

2022-11-18 10:36 UTC, pwltr commented on src/screens/Settings/Backup/ShowPassphrase.tsx
> +
NavigationHeader needs to go outside of the container otherwise too much padding

2022-11-18 10:36 UTC, pwltr commented on src/screens/Onboarding/Slideshow.tsx
> +					</AnimatedView>
I think it should go between the buttons and the dots

2022-11-18 10:49 UTC, pwltr requested changes

2022-11-18 10:49 UTC, pwltr commented on src/screens/Settings/Backup/ConfirmMnemonic.tsx
>  const ConfirmMnemonic = ({ navigation, route }): ReactElement => {
```suggestion
const ConfirmMnemonic = ({ navigation, route }: BackupScreenProps<'ConfirmMnemonic'>): ReactElement => {
```

2022-11-18 11:26 UTC, pwltr requested changes

2022-11-18 11:26 UTC, pwltr commented on src/utils/startup/index.ts
> +	await updateWallet({ walletExists: true });
`createWallet` action already sets `walletExists: true` I believe

2022-11-18 11:31 UTC, limpbrains commented on src/screens/Onboarding/Slideshow.tsx
> +					</AnimatedView>
agree

2022-11-18 11:49 UTC, pwltr commented
Can you try restoring the following seed without passphrase: `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about`

It is stuck restoring for me, but maybe problem with remote backup like with my own seed.

2022-11-18 12:10 UTC, limpbrains commented on src/utils/startup/index.ts
> +	await updateWallet({ walletExists: true });
indeed

2022-11-18 12:11 UTC, limpbrains commented
> Can you try restoring the following seed without passphrase: `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about`
> 
> It is stuck restoring for me, but maybe problem with remote backup like with my own seed.

Yeah, It doesn't work for me either. It is definitely another issue #651

2022-11-18 12:48 UTC, pwltr commented
Can we got some padding below the dots for phones without a SafeArea at the bottom?
![image](https://user-images.githubusercontent.com/8538369/202708623-a09abfaa-579e-49c0-a920-848d2a08b003.png)

2022-11-18 14:08 UTC, limpbrains commented
done
![image](https://user-images.githubusercontent.com/155891/202723479-a3b00c6d-d597-4235-adfd-bf9a7e6daee9.png)

2022-11-18 14:17 UTC, pwltr approved these changes

2022-11-18 14:41 UTC, coreyphillips approved these changes

2022-11-18 14:44 UTC, merged