fix: various fixes
synonymdev/bitkit-react-native pull request #714
Opened 2022-11-17 16:26 UTC by pwltr

### Changes
- fix(widgets): fix types for WidgetFeedEdit
- fix(wallet): state mutation when creating wallet
- fix(settings): update activity on network change
- fix(send): amount spacing
- chore: add some types & cleanup

2022-11-17 21:40 UTC, limpbrains requested changes

2022-11-17 21:40 UTC, limpbrains commented on package.json
> +    "immer": "^9.0.16",
Can use lodash cloneDeep or `JSON.parse(JSON.stringify(x))` hack from https://github.com/synonymdev/bitkit/blob/master/src/store/helpers.ts#L9 instead of adding another dependency here?

2022-11-17 21:40 UTC, limpbrains commented on src/styles/components.ts
> -	lineHeight: props.lineHeight ?? '49px',
If I remeber correctly, it is not a default value for this font size/type. Are you sure we can remove this?

2022-11-17 21:57 UTC, pwltr commented on package.json
> +    "immer": "^9.0.16",
It is already a peerDependency of `@reduxjs/toolkit`. It let's us write mutable code in reducers which I would like to use more in the near future.

2022-11-17 22:01 UTC, limpbrains commented on package.json
> +    "immer": "^9.0.16",
Nice, let's use it then

2022-11-18 13:43 UTC, pwltr commented on src/styles/components.ts
> -	lineHeight: props.lineHeight ?? '49px',
It is not the correct lineHeight for this font which causes it to be uncentered in the lineHeight. Not really noticeable anywhere but in `<Money />` component so I'm overwriting it there now.

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-11-18 at 14 35 28](https://user-images.githubusercontent.com/8538369/202718201-76be352b-93b8-44d6-97a0-81b68f768bb0.png)

2022-11-18 13:59 UTC, limpbrains commented on src/styles/components.ts
> -	lineHeight: props.lineHeight ?? '49px',
Yeah, but without it all other places, where we are using Display, like on Slideshow. Will be broken

2022-11-18 13:59 UTC, limpbrains approved these changes

2022-11-18 14:23 UTC, merged