feat(profile): add prefix to profile links if suggestions were used
synonymdev/bitkit-react-native pull request #762
Opened 2022-12-07 16:08 UTC by Nazeh

This PR tries to improve profile links input, without going too crazy with regex and validating every URI under the sun!

I regret that I couldn't use `useRef` to focus on the input text too.

![simulator_screenshot_4174559E-0242-4448-AAE3-27B7CFC9F3C3](https://user-images.githubusercontent.com/40009100/206230348-336457c2-114f-4669-b6df-94e18a68daff.png)

2022-12-07 18:10 UTC, pwltr requested changes

2022-12-07 18:10 UTC, pwltr commented on src/screens/Profile/ProfileLinkSuggestions.tsx
> +	Phone: { prefix: 'tel:' },
I feel like pre-filling especially these two strings will be confusing to the avg user. I suggest we move these prefixes to the render code in `ProfileLinks`.

EDIT:
Or maybe add the prefix before saving, whatever the intention is here.

2022-12-07 18:20 UTC, Nazeh commented on src/screens/Profile/ProfileLinkSuggestions.tsx
> +	Phone: { prefix: 'tel:' },
I started with adding the prefix before saving, but it is kinda tough, for example this looks benign:
```js
const url = form.url.startsWith(prefix)) ? form.url : prefix + form.url 
```

But if the prefix is `https://twitter.com/` and the user enters `https://www.twitter.com` or vice versa, then you get a bad url. I basically chose the easry road that will just nudge users just a step closer to the correct url formats.

If you have any more elaborate checks and transformations, feel free to close this PR, I just wanted to suggest a quick fix.

2022-12-07 18:22 UTC, Nuhvi commented on src/screens/Profile/ProfileLinkSuggestions.tsx
> +	Phone: { prefix: 'tel:' },
Also ... none of this actually solve the issue of validating each suffix according to the `form.title` for example phone numbers require different validation than a website or an email, and if someone writes `https://twitter.com/foo/bar` that shouldn't be valid either!

2022-12-07 18:46 UTC, pwltr commented on src/screens/Profile/ProfileLinkSuggestions.tsx
> +	Phone: { prefix: 'tel:' },
I think the links are fine as a first step just the phone number and email I wouldn't do this way. Usually they aren't saved to a database in that format. Leave it up to the consumer how to render these two. I'm down to work on validation soon.

2023-06-02 15:30 UTC, pwltr commented
Closing in favor of https://github.com/synonymdev/bitkit/pull/1080

2023-06-02 15:30 UTC, closed without merging