fix(wallet): Wipe Previous Install During Onboarding
synonymdev/bitkit-react-native pull request #844
Opened 2023-01-20 21:41 UTC by coreyphillips

This PR:
- Adds `wipeApp` function to "Continue" button in `TermsOfUse` component.
- Updates `wipeApp` params in `actions/settings.ts`.
- Updates `wipeKeychain` method to iterate through and remove all known key/values.
- Sets `updateAllAddressTypes` param to `true` in `startWalletServices`.
- Updates `RESET_SELECTED_WALLET` reducer.
- Removes `resetSelectedWallet` from `actions/wallet.ts`.
- Updates `refreshWallet` params in `resetWalletStore` in `actions/wallet.ts`.

2023-01-21 14:48 UTC, coreyphillips commented
The tests are failing due to the change address changes [here](https://github.com/synonymdev/bitkit/pull/841). I'll resolve this in a separate PR.

2023-01-21 22:37 UTC, pwltr requested changes

2023-01-21 22:37 UTC, pwltr commented on src/screens/Onboarding/TermsOfUse.tsx
> +		wipeApp({
I feel like we should `await` and handle any errors here (e.g. disable the button) since this call failing can end up losing money for the user.

2023-01-22 12:56 UTC, pwltr approved these changes

2023-01-22 13:08 UTC, merged