feat: i18n
synonymdev/bitkit-react-native pull request #891
Opened 2023-02-15 18:50 UTC by limpbrains

2023-02-28 23:12 UTC, pwltr requested changes

2023-02-28 23:12 UTC, pwltr commented on src/screens/Settings/General/index.tsx
> -			/>
Why remove the `<Dialog/>` here?

2023-03-01 09:34 UTC, limpbrains commented on src/screens/Settings/General/index.tsx
> -			/>
Because it was moved to Settings/Backup/ResetAndRestore.tsx and this one is not used

2023-03-01 10:18 UTC, pwltr requested changes

2023-03-01 10:18 UTC, pwltr commented on src/utils/i18n/locales/en/onboarding.json
> +	"toolkit": "Your Bitcoin\n<brans>Toolkit.</brans>",
typo:
```suggestion
	"toolkit": "Your Bitcoin\n<brand>Toolkit.</brand>",
```

2023-03-01 10:27 UTC, limpbrains commented on src/utils/i18n/locales/en/onboarding.json
> +	"toolkit": "Your Bitcoin\n<brans>Toolkit.</brans>",
fixedd

2023-03-01 10:36 UTC, pwltr requested changes

2023-03-01 10:36 UTC, pwltr commented on src/components/ContactsList.tsx
> +			<Text01M>{t('contacts_no_found')}</Text01M>
missing english translation here

2023-03-01 10:36 UTC, pwltr commented on src/utils/i18n/locales/en/security.json
> +	"bio_phone_settings": "Phone Settings}",
typo:
```suggestion
	"bio_phone_settings": "Phone Settings",
```

2023-03-01 10:41 UTC, limpbrains commented on src/components/ContactsList.tsx
> +			<Text01M>{t('contacts_no_found')}</Text01M>
fixed

2023-03-01 10:41 UTC, limpbrains commented on src/utils/i18n/locales/en/security.json
> +	"bio_phone_settings": "Phone Settings}",
fixed

2023-03-01 10:44 UTC, pwltr approved these changes

2023-03-01 12:11 UTC, merged