fix: Lightning UI & channel open/close issues
synonymdev/bitkit-react-native pull request #928
Opened 2023-03-13 12:28 UTC by pwltr

Closes https://github.com/synonymdev/bitkit/issues/659, https://github.com/synonymdev/bitkit/issues/872, [Asana #1](https://app.asana.com/0/0/1202464022210897/1203975785881699/f), [Asana #2](https://app.asana.com/0/1189635884316057/1204116236827217/f)

### Changes
- UI: fix spacing inconsistency in List views / rows
- UI: fix some style in LN onboarding & transfer, fix small design deltas for widgets
- Send: fix missing redirect when pasting non BIP21 invoices
- Settings: fix some issues in the Channel UI (list & detail screen)
- Lightning: fix issues when closing channels, fix suggestion cards when transferring
- Activity: show transfer to savings tx, hide receive notification when it's a transfer
- Receive: add waitForLdk helper, fix LN invoice missing when opening Receive sheet too quickly after opening Bitkit
- Lightning: improve fee setting for LDK
- remove some unnecessary async code, cleanup

### Notes
We're now adding the tx inputs to the store so that we don't have to fetch them when needed. Using `order.channel_close_tx` from BT to determing correct channel status and to show transfers to savings in activity.

2023-03-13 12:44 UTC, pwltr commented on src/utils/i18n/locales/ru/lightning.json
> +	"closed_on": "TODO",
@limpbrains Okay to say 'TODO' here? Is there a better way to add new fields without translation?

2023-03-13 14:26 UTC, limpbrains commented on src/utils/i18n/locales/ru/lightning.json
> +	"closed_on": "TODO",
You don't have to add anything to the translation files, except for the English.
If some string is missing in the RU translation, one from EN will be used instead automatically.
Please remove this

2023-03-13 14:41 UTC, limpbrains requested changes

2023-03-13 14:41 UTC, limpbrains commented on src/screens/Wallets/Receive/index.tsx
> +		await waitForLdk();
If LDK is not available, will user see any error?

2023-03-13 15:32 UTC, pwltr commented on src/screens/Wallets/Receive/index.tsx
> +		await waitForLdk();
No not at the moment, when testing it was usually available on the second or third retry. I would like to add some error handling for this but we should think of a good approach first to give the user some action to follow if LDK doesn't start at all. (Will be needed in other places too). Got some stability improvements coming as well in RN-LDK afaik.

2023-03-14 17:07 UTC, coreyphillips approved these changes

2023-03-14 17:31 UTC, limpbrains approved these changes

2023-03-14 17:49 UTC, merged