feat: backup LDK activity and blocktank orders
synonymdev/bitkit-react-native pull request #931
Opened 2023-03-14 18:44 UTC by limpbrains

Because we can't restore LN activity from onchain data or ldk backup we now backup it on every new LN transaction. Same for blocktank orders

2023-03-16 15:38 UTC, pwltr requested changes

2023-03-16 15:38 UTC, pwltr commented on src/utils/backup/backups-subscriber.tsx
> +	// Attempts to backup ldkActivity anytime remoteMetadataBackupSynced is set to false.
```suggestion
	// Attempts to backup ldkActivity anytime remoteLdkActivityBackupSynced is set to false.
```

2023-03-16 15:38 UTC, pwltr commented on src/store/actions/backup.ts
> +	const backupRes = await getBackup<IMetadata>({
wrong type `IMetadata` ?

2023-03-16 15:38 UTC, pwltr commented on src/store/actions/backup.ts
> +	const backupRes = await getBackup<IMetadata>({
wrong type `IMetadata` ?

2023-03-17 11:25 UTC, limpbrains commented on src/utils/backup/backups-subscriber.tsx
> +	// Attempts to backup ldkActivity anytime remoteMetadataBackupSynced is set to false.
fixed

2023-03-17 11:25 UTC, limpbrains commented on src/store/actions/backup.ts
> +	const backupRes = await getBackup<IMetadata>({
fixed

2023-03-17 11:25 UTC, limpbrains commented on src/store/actions/backup.ts
> +	const backupRes = await getBackup<IMetadata>({
fixed

2023-03-17 11:40 UTC, pwltr approved these changes

2023-03-17 13:13 UTC, merged