feat: v35
synonymdev/bitkit-react-native pull request #933
Opened 2023-03-15 14:16 UTC by limpbrains

- new layout for NavigationHeader to allow 2 buttons on right and how it work nicely with long titles
- new Beta warnings
- new No Multidevince warnings
- new screen for Profile details
- HighBalance warning level decreased to 100 USD
- fix e2e tests for all of that

<img width="429" alt="Screenshot 2023-03-15 at 14 10 46" src="https://user-images.githubusercontent.com/155891/226642324-1afb4e8a-cd72-4188-831e-fe175139756f.png">

2023-03-21 15:49 UTC, pwltr requested changes

2023-03-21 15:49 UTC, pwltr commented on src/screens/Settings/Backup/MultipleDevices.tsx
> +const imageSrc = require('../../../assets/illustrations/exclamation-mark.png');
```suggestion
const imageSrc = require('../../../assets/illustrations/phone.png');
```

2023-03-21 15:49 UTC, pwltr commented on src/screens/Settings/Backup/MultipleDevices.tsx
> +const imageSrc = require('../../../assets/illustrations/exclamation-mark.png');
Also, text for `mnemonic_data_text` has been updated.

2023-03-21 15:49 UTC, pwltr commented on src/screens/Profile/ProfileDetails.tsx
> +					/>
Missing horizontal margin on this button

2023-03-21 19:19 UTC, limpbrains commented on src/screens/Profile/ProfileDetails.tsx
> +					/>
fixed

2023-03-21 19:19 UTC, limpbrains commented on src/screens/Settings/Backup/MultipleDevices.tsx
> +const imageSrc = require('../../../assets/illustrations/exclamation-mark.png');
fixed

2023-03-23 10:41 UTC, pwltr approved these changes

2023-03-23 11:01 UTC, merged