fix(wallet): #780 skipping addressIndex
synonymdev/bitkit-react-native pull request #934
Opened 2023-03-15 15:40 UTC by pwltr

Closes https://github.com/synonymdev/bitkit/issues/780

~This PR fixes some incorrect usages of `.map()` together with `async` that most likely caused a race condition when generating addresses causing the above issue. Also removes other unnecessary async code.~

~I'll probably enable the `@typescript-eslint/no-misused-promises` eslint rule and fix other occurrences of this type in another PR.~

This PR fixes a race condition caused by calling `updateAddressIndexes()` twice when switching networks causing the above issue. Also removes other unnecessary async code.

### Changes
- remove all function calls in `BitcoinNetworkSelection.tsx` that are already called in `startWalletServices()`
- remove unnecessary async code, cleanup

2023-03-15 16:14 UTC, limpbrains requested changes
I think that using Promise.all with map to just iterate over something is very confusing and may lead to race condition bugs.

2023-03-15 16:14 UTC, limpbrains commented on src/utils/wallet/index.ts
> +				}
If you return in map, you only skip one element
If you return in for loop, you exit from it
IMHO here should be return, but let's check if @coreyphillips

2023-03-15 16:14 UTC, limpbrains commented on src/store/actions/wallet.ts
>  	}
Not sure if this can be removed without adding giant try/catch for the whole function

2023-03-15 16:14 UTC, limpbrains commented on src/utils/wallet/index.ts
> +		});
Same here. With promise.all if any `addAddresses` call throws an error, it will be ignored. With for ... loop this will stop the loop.

IMHO for loop is better here, but what if `addAddresses` return an error? Should we handle stop the loop or ignore it?

2023-03-15 16:15 UTC, limpbrains commented on src/store/actions/wallet.ts
>  			throw response.error;
replace with return

2023-03-15 16:26 UTC, pwltr commented on src/utils/wallet/index.ts
> +				}
I think we should definitely let it error out and not ignore because it's critical that this does what it should. But need to handle errors here.

2023-03-15 16:45 UTC, pwltr commented on src/store/actions/wallet.ts
>  	}
This code was redundant since `promises` is of type `Promise<void>` since the `.map()` didn't return anything. I think with [this](https://github.com/synonymdev/bitkit/pull/934#discussion_r1137383518) changed there isn't any need for more error handling here? Other than `getNextAvailableAddress` (handled) there isn't a lot going on.

2023-03-15 17:21 UTC, pwltr commented on src/store/actions/wallet.ts
>  	}
Apparently you don't need to return anything in `.map()` in cases like this for it to run as intended. So some of these changes are unnecessary.

2023-03-16 13:20 UTC, pwltr commented
Found the problem is not caused by the promises being resolved in parallel but rather the whole `updateAddressIndexes()` function being called twice racing against each other. I still believe error handling should be improved in some of the async/await loops but that would be for another PR.

2023-03-16 14:41 UTC, limpbrains commented
How is this possible? We wait `updateAddressIndexes` to be completed before calling `startWalletServices`. 
If `await updateAddressIndexes()` resolves before the job is completed, there may be a bug in this function. Have we resolved this issue?

As far as I recall, the purpose of calling updateAddressIndexes here is to generate more addresses than what is typically done in startWalletServices. By default, startWalletServices only generates five native segwit addresses, similar to when creating a new wallet. However, when switching networks or restoring a wallet, it is necessary to scan for alternative wallet types that the user may have used. If they have used a wallet type other than native segwit, they will be unable to access their funds.

2023-03-16 14:52 UTC, pwltr commented
Good question, let me check again.

2023-03-16 15:57 UTC, coreyphillips commented on src/utils/wallet/index.ts
> +				}
We should be most careful about exiting from the loop entirely when iterating over any method performing calls to electrum. This could result in unsaved work.

2023-03-17 15:49 UTC, pwltr commented on src/store/actions/wallet.ts
>  	}
return value of `.filter()` was not used.

2023-03-17 15:51 UTC, pwltr commented on src/utils/wallet/index.ts
> -				const key = Object.keys(generatedAddresses.value.addresses)[0];
It was wrongly assumed that the `addresses` object was sorted by `address.index` here. In effect `key` pointed to a random address of the newly generated.

2023-03-17 15:51 UTC, pwltr commented on src/utils/wallet/index.ts
> -					generatedChangeAddresses.value.changeAddresses,
same here

2023-03-17 23:00 UTC, limpbrains approved these changes

2023-03-18 10:17 UTC, merged