feat: Activity calendar filter
synonymdev/bitkit-react-native pull request #956
Opened 2023-03-28 13:12 UTC by limpbrains

2023-04-05 19:21 UTC, pwltr requested changes

2023-04-05 19:21 UTC, pwltr commented on src/components/TabBar.tsx
> +			.filter((view) => view !== 'backupPrompt')
remove exception for `backupPrompt`

2023-04-05 19:21 UTC, pwltr commented on src/store/migrations/index.ts
> +	},
No need for a migration here since `ui` reducer is not persisted. See `persistConfig`

2023-04-05 19:21 UTC, pwltr commented on src/screens/Activity/ActivityFiltered.tsx
> +	const addTag = (tag): void => {
```suggestion
	const addTag = (tag: string): void => {
```

2023-04-05 19:21 UTC, pwltr commented on src/screens/Activity/TagsPrompt.tsx
> +	onAddTag: Function;
```suggestion
	onAddTag: (tag: string) => void;
```

2023-04-05 19:21 UTC, pwltr commented on src/components/SearchInput.tsx
> +		minHeight: 48,
Is there an issue with the height here? Aldert asked me to fix it in the past, it needs to be exactly 48px

2023-04-05 19:23 UTC, pwltr commented
Maybe show an empty state here or hide the tags icon when there are no tags?

![Simulator Screen Shot - iPhone 13 - 2023-04-05 at 21 19 28](https://user-images.githubusercontent.com/8538369/230183558-47aa3708-d3c0-4f62-a8a7-b930d8cba2bc.png)

2023-04-05 19:24 UTC, pwltr commented
There is a bug when you select a range at the end of the month and it shows the first day of the next month as selected. Maybe only for when Monday is set as first day of the week.

![Screenshot_1680722488](https://user-images.githubusercontent.com/8538369/230183695-df815d01-6193-492a-ac62-175f2114e827.png)
![Screenshot_1680722491](https://user-images.githubusercontent.com/8538369/230183699-0cd3ad34-8459-4110-ac06-340995009197.png)

2023-04-06 07:39 UTC, pwltr commented
Sometimes the calendar has 6 rows and the spacing is not 100% right.

![Simulator Screen Shot - iPhone 13 - 2023-04-06 at 01 18 11](https://user-images.githubusercontent.com/8538369/230307636-56bd961c-adea-4681-aa98-bf17960f4bcb.png)

2023-04-06 08:44 UTC, limpbrains commented on src/components/TabBar.tsx
> +			.filter((view) => view !== 'backupPrompt')
fixed in #0f70dea

2023-04-06 08:44 UTC, limpbrains commented on src/store/migrations/index.ts
> +	},
fixed

2023-04-06 08:44 UTC, limpbrains commented on src/screens/Activity/ActivityFiltered.tsx
> +	const addTag = (tag): void => {
fixed

2023-04-06 08:44 UTC, limpbrains commented on src/screens/Activity/TagsPrompt.tsx
> +	onAddTag: Function;
fixed

2023-04-06 08:46 UTC, limpbrains commented on src/components/SearchInput.tsx
> +		minHeight: 48,
Before your fix searchInput was able to stretch vertically if there are many tags. I was trying to restore this behaviour. But I couldn't, so I'm reverting it. Still waiting for the discussion in figma

2023-04-06 09:47 UTC, limpbrains commented
> Maybe show an empty state here or hide the tags icon when there are no tags?

done

> There is a bug when you select a range at the end of the month and it shows the first day of the next month as selected. Maybe only for when Monday is set as first day of the week.

Can't reproduce, even tried to set different timezone and date of 5th March. Maybe you changed time or timezone without restarting the app?

2023-04-06 10:10 UTC, limpbrains commented
> Sometimes the calendar has 6 rows and the spacing is not 100% right.

After discussing it with Alders, I added another BottomSheet size just for this case 

![image](https://user-images.githubusercontent.com/155891/230346179-86beb1c7-421e-4f86-8369-fe0a18cc94b0.png)

2023-04-06 10:21 UTC, pwltr requested changes

2023-04-06 10:21 UTC, pwltr commented on src/screens/Activity/TimeRangePrompt.tsx
> +	},
I would change these styles to avoid the text jumping when the number of rows changes:

```suggestion
	range: {
		marginTop: 'auto',
		marginBottom: 36,
		alignItems: 'center',
	},
```

2023-04-06 10:27 UTC, pwltr commented
> > Maybe show an empty state here or hide the tags icon when there are no tags?
> 
> done
> 
> > There is a bug when you select a range at the end of the month and it shows the first day of the next month as selected. Maybe only for when Monday is set as first day of the week.
> 
> Can't reproduce, even tried to set different timezone and date of 5th March. Maybe you changed time or timezone without restarting the app?

I can't reproduce it anymore either

2023-04-06 10:40 UTC, limpbrains commented on src/screens/Activity/TimeRangePrompt.tsx
> +	},
Still jumps for me

2023-04-06 10:49 UTC, pwltr commented on src/screens/Activity/TimeRangePrompt.tsx
> +	},
I forgot, also need to  remove `marginTop: 'auto',` from `buttonContainer` styles

2023-04-06 10:54 UTC, limpbrains commented on src/screens/Activity/TimeRangePrompt.tsx
> +	},
Nice, added

2023-04-06 11:01 UTC, pwltr approved these changes
Really nice work

2023-04-06 12:50 UTC, merged