feat(wallet): Report Warnings
synonymdev/bitkit-react-native pull request #960
Opened 2023-04-06 18:12 UTC by coreyphillips

This PR:
- Updates `TStorageWarning` object to include `warningId` and `warningReported` status.
- Attempts to report warnings immediately after detection.
- Updates `defaultChecksShape`.
- Attempts to report any unreported warnings on each start.

Notes:
- We're still waiting on the correct url for reporting warnings, but wanted to create the PR to start review in the meantime.
- Once the endpoint is up, I'll update the fetch request in the `reportImpactedAddressBalance` method, uncomment the code snippet and remove the `TODO`.

2023-04-11 15:33 UTC, limpbrains commented
Type check is failing

2023-04-11 16:56 UTC, coreyphillips commented
@pwltr any idea what's triggering the type-check to fail?

Edit: nvm, I believe I found it.

2023-04-11 20:54 UTC, limpbrains approved these changes

2023-04-12 09:26 UTC, pwltr requested changes

2023-04-12 09:26 UTC, pwltr commented on src/components/List.tsx
> +	type: EItemType;
Avoid changing this type if possible, see other suggestion below to fix the type error.

```suggestion
	type: EItemType.switch;
```

2023-04-12 09:26 UTC, pwltr commented on src/screens/Settings/DevSettings/index.tsx
> +				},
```suggestion
				{
					title: `Warnings: ${warnings.length}`,
					type: EItemType.textButton,
					value: ''.
					testID: 'Warnings',
				},
```

2023-04-12 12:39 UTC, pwltr approved these changes

2023-04-13 11:35 UTC, merged