UI: Improve NumberPad UX
synonymdev/bitkit-react-native pull request #968
Opened 2023-04-13 15:37 UTC by pwltr

# Description

### Changes
- improve NumberPad UX
- update all NumberPads (except SendNumberPad & NumberPadLightning)
- remove redundant `unitPreference`
- fix TextField font weight
- add e2e tests for ChangePIN
- add e2e tests for Receive

### Notes
Rewrite for SendNumberPad & NumberPadLightning will come in another PR. Dealing with the edge cases there would've blown up the scope.

---

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Tests
- [x] Detox test
- [x] Unit test

## Screenshot / Video

https://user-images.githubusercontent.com/8538369/231811417-8bb4b980-7773-4a60-a55a-e64cd7063584.mp4

## QA Notes

100% Coverage by automated tests

2023-04-17 15:24 UTC, limpbrains requested changes
Why on Send screen I don't have this nice grey hightlightning for Amount input? It is hard to enter amount in BTC.

Amazing work, especially all the tests !

2023-04-17 15:24 UTC, limpbrains commented on src/components/MoneySymbol.tsx
> +				<Display color="white5" money={true} testID="MoneyFiatSymbol">
I removed `money` from Display props

2023-04-17 15:24 UTC, limpbrains commented on __tests__/numberpad.ts
> +updateUi;
I fixed same issue by adding 
`import '../src/utils/i18n';` to the beginning of the test

2023-04-17 15:24 UTC, limpbrains commented on src/components/NumberPad.tsx
> +			<Text style={[styles.button, hasError && { color: '#ff6600' }]}>
inline style

2023-04-17 15:31 UTC, pwltr commented
> Why on Send screen I don't have this nice grey hightlightning for Amount input? It is hard to enter amount in BTC.

Thanks, for the Send and Lightning onboarding NumberPads I will open a separate PR. There are a lot of edge cases to handle so I split the work up a bit.

2023-04-23 07:49 UTC, limpbrains approved these changes

2023-04-26 20:24 UTC, merged