chore(wallet): Upgrade react-native to 0.71.6
synonymdev/bitkit-react-native pull request #982
Opened 2023-04-19 18:12 UTC by coreyphillips

# Description

- Upgrades `react-native` to `0.71.6`.
- Upgrades dependencies in `package.json`.
- Android is now using `hermes` instead of the `v8` engine.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## QA Notes

- Prior to running Bitkit we need to first specify either `yarn setup-ios` or `yarn setup-android`.
    - This will be removed once we have a stable `libsodium` branch for both iOS & Android.
- Please suggest changes or create PR's against this branch if you see anything that needs fixing or additional attention.
- All functionality throughout the app should be tested to ensure that functionality is retained or improved.

2023-04-21 13:44 UTC, pwltr commented
Very nice to see this. Has anyone managed to build on Android? I'm getting
```
error: cannot find symbol
import com.bitkit.R;
```
both on Linux and MacOS.

2023-04-21 13:45 UTC, pwltr requested changes

2023-04-21 13:45 UTC, pwltr commented on package.json
> +    "clean": "yarn clean:rn && yarn clean:ios && yarn start --reset-cache",
Revert this?

2023-04-21 13:45 UTC, pwltr commented on BUILD.md
> +```
No "Run" step needed in `Build.md`

2023-04-21 13:45 UTC, pwltr commented on BUILD.md
> +```
Also add this to `Development.md`

2023-04-21 13:45 UTC, pwltr commented on _node-version
What is this file for? I usually do `nvm use` and it sets the right version for the project. You using something else?

2023-04-21 13:51 UTC, coreyphillips commented on _node-version
This file was created and included during the `npx react-native init bitkit` command.

2023-04-21 13:54 UTC, coreyphillips commented on package.json
> +    "clean": "yarn clean:rn && yarn clean:ios && yarn start --reset-cache",
Reverted [here](https://github.com/synonymdev/bitkit/pull/982/commits/0ef1f88599bdc827efae4a7a4490924337d23777).

2023-04-21 13:54 UTC, coreyphillips commented on BUILD.md
> +```
Updated [here](https://github.com/synonymdev/bitkit/pull/982/commits/0ef1f88599bdc827efae4a7a4490924337d23777).

2023-04-21 13:55 UTC, coreyphillips commented on BUILD.md
> +```
Updated [here](https://github.com/synonymdev/bitkit/pull/982/commits/0ef1f88599bdc827efae4a7a4490924337d23777).

2023-04-21 14:03 UTC, coreyphillips commented
> Very nice to see this. Has anyone managed to build on Android? I'm getting
> 
> ```
> error: cannot find symbol
> import com.bitkit.R;
> ```
> 
> both on Linux and MacOS.

Prior to running Android are you running `yarn setup-android`? Perhaps `yarn setup-android && yarn clean && yarn android` if the `setup-android` command alone is not working.

2023-04-21 17:50 UTC, pwltr commented
> Prior to running Android are you running `yarn setup-android`? Perhaps `yarn setup-android && yarn clean && yarn android` if the `setup-android` command alone is not working.

No luck, here's the full output of `yarn android`:

```
yarn run v1.22.19
$ react-native run-android
warn Package nodejs-mobile-react-native contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info JS server already running.
info Installing the app...

> Configure project :lottie-react-native
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-flipper
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-rate
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/phil/Dev/synonymdev/bitkit-test/node_modules/react-native-reanimated/android/react-native-reanimated-71-hermes.aar

> Configure project :shopify_react-native-skia
react-native-skia: node_modules/ found at: /Users/phil/Dev/synonymdev/bitkit-test/node_modules
react-native-skia: RN Version: 71 / 0.71.6
react-native-skia: isSourceBuild: false
react-native-skia: PrebuiltDir: /Users/phil/Dev/synonymdev/bitkit-test/node_modules/@shopify/react-native-skia/android/build/react-native-0*/jni
react-native-skia: buildType: debug
react-native-skia: buildDir: /Users/phil/Dev/synonymdev/bitkit-test/node_modules/@shopify/react-native-skia/android/build
react-native-skia: node_modules: /Users/phil/Dev/synonymdev/bitkit-test/node_modules
react-native-skia: Enable Prefab: true
react-native-skia: aar state post 70, do nothing
WARNING:The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (30.0.3) for Android Gradle Plugin 7.4.2.
Android SDK Build Tools 30.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
436 actionable tasks: 3 executed, 433 up-to-date
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/modules/SplashScreen/SplashScreenModule.java:9: error: cannot find symbol
import com.bitkit.R;
                 ^
  symbol:   class R
  location: package com.bitkit
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:20: error: cannot find symbol
          return BuildConfig.DEBUG;
                 ^
  symbol: variable BuildConfig
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:40: error: cannot find symbol
          return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                 ^
  symbol: variable BuildConfig
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:45: error: cannot find symbol
          return BuildConfig.IS_HERMES_ENABLED;
                 ^
  symbol: variable BuildConfig
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:58: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:58: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainActivity.java:24: error: package R does not exist
    setTheme(R.style.AppTheme);
              ^
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/modules/SplashScreen/SplashScreenModule.java:72: error: package R does not exist
            splashDialog = new Dialog(activity, R.style.AppTheme_SplashDialog);
                                                 ^
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/modules/SplashScreen/SplashScreenModule.java:73: error: package R does not exist
            splashDialog.setContentView(R.layout.splash_screen);
                                         ^
9 errors

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/modules/SplashScreen/SplashScreenModule.java:9: error: cannot find symbol
import com.bitkit.R;
                 ^
  symbol:   class R
  location: package com.bitkit
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:20: error: cannot find symbol
          return BuildConfig.DEBUG;
                 ^
  symbol: variable BuildConfig
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:40: error: cannot find symbol
          return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                 ^
  symbol: variable BuildConfig
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:45: error: cannot find symbol
          return BuildConfig.IS_HERMES_ENABLED;
                 ^
  symbol: variable BuildConfig
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:58: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainApplication.java:58: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
/Users/phil/Dev/synonymdev/bitkit-test/android/app/src/main/java/com/bitkit/MainActivity.java:24: error: packa [...]

2023-04-21 18:17 UTC, coreyphillips commented
@pwltr Found the issue. Sorry about that. Should be sorted as of [this](https://github.com/synonymdev/bitkit/pull/982/commits/a29d37fe1e1a60ca9ce3343ac72f81320a8f272a) commit.

2023-04-22 06:22 UTC, pwltr commented
> @pwltr Found the issue. Sorry about that. Should be sorted as of [this](https://github.com/synonymdev/bitkit/pull/982/commits/a29d37fe1e1a60ca9ce3343ac72f81320a8f272a) commit.

Good now! I'm seeing a performance improvement and smoother animations on Android. 🤩 
No issues so far in terms of breakage in the app. Just need to get the tests to run.

2023-04-22 07:26 UTC, pwltr commented
App is crashing on the WalletDetails screen (iOS & Android)

![image](https://user-images.githubusercontent.com/8538369/233769816-c792c431-5cfc-4cb9-86b4-c75cf7ec2314.png)

2023-04-22 07:27 UTC, pwltr commented
E2E tests are working in debug mode on iOS. Not for release though. Looks like something to do with Flipper.

2023-04-24 16:16 UTC, limpbrains commented
I can't compile it in Release configuration for iOS:

```
> npx react-native run-ios --simulator="iPhone 14" --configuration Release

▸ Compiling bitkit_vers.c
▸ Compiling bitkit_vers.c
▸ Linking bitkit
⚠️  ld: Could not find or use auto-linked library 'libldk.a'

❌  ld: symbol(s) not found for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

▸ Linking bitkit
⚠️  ld: Could not find or use auto-linked library 'libldk.a'

❌  ld: symbol(s) not found for architecture arm64
```

2023-04-24 21:47 UTC, coreyphillips commented
@Jasonvdb, any thoughts on why we could be getting [this](https://github.com/synonymdev/bitkit/pull/982#issuecomment-1520468696) error?

2023-04-25 06:24 UTC, Jasonvdb commented
> @Jasonvdb, any thoughts on why we could be getting [this](https://github.com/synonymdev/bitkit/pull/982#issuecomment-1520468696) error?

Looking into it today. It comes up a lot but can be related to many different issues.

2023-04-26 06:48 UTC, limpbrains approved these changes

2023-04-26 06:48 UTC, limpbrains commented on package.json
> +    "nodejs-mobile-react-native": "https://github.com/Shopify/nodejs-mobile-react-native",
I think we should pin commit hash here, so we don't upgrade it accidently

2023-04-26 06:48 UTC, limpbrains commented on package.json
> +    "LocationWhenInUse",
do we need location?

2023-04-26 06:48 UTC, limpbrains commented on ios/bitkit/AppDelegate.mm
> -  // adding it for boot splash END
We need to try to keep it, it shows logo while running RN. I will try to do it

2023-04-26 06:48 UTC, limpbrains commented on ios/bitkit/AppDelegate.mm
> -  // adding it for boot splash END
fixed

2023-04-26 10:24 UTC, limpbrains commented
> I can't compile it in Release configuration for iOS:
> 
> ```
> > npx react-native run-ios --simulator="iPhone 14" --configuration Release
> 
> ▸ Compiling bitkit_vers.c
> ▸ Compiling bitkit_vers.c
> ▸ Linking bitkit
> ⚠️  ld: Could not find or use auto-linked library 'libldk.a'
> 
> ❌  ld: symbol(s) not found for architecture x86_64
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ▸ Linking bitkit
> ⚠️  ld: Could not find or use auto-linked library 'libldk.a'
> 
> ❌  ld: symbol(s) not found for architecture arm64
> ```

I was able to compile in release mode with `NO_FLIPPER=1`
```sh
rm -rf node_modules
NO_FLIPPER=1 yarn
npx react-native run-ios --simulator="iPhone 14" --configuration Release
```

2023-04-26 11:33 UTC, pwltr approved these changes

2023-04-26 11:50 UTC, Jasonvdb approved these changes

2023-04-26 15:05 UTC, merged